### ISSUE TITLE
No notification on lock screen when app is terminated

### ISSUE THREAD

**Issue by olegys** [hiennguyen92/flutter_callkit_incoming#1]
Good day! Thank you for such a great plugin! I really like him !)

But I found one problem on android:
When my application is closed and the screen is locked, then there is a call sound, but after unlocking the screen I do not see the call notification, but the sound continues to play (

Phone: Xiaomi mi 9
Android: 11.0

I would be grateful for any answer!

**Comment by hiennguyen92** [comment]
Hi @olegys,
I don't have a Xiaomi device. 
can you record screen of the whole process? I will check and fix it easier.
 thanks

**Comment by olegys** [comment]
@hiennguyen92 

> Hi @olegys, I don't have a Xiaomi device. can you record screen of the whole process? I will check and fix it easier. thanks

https://user-images.githubusercontent.com/18525409/139870356-490b3b9b-4433-4362-9cf3-a2112b94e0b9.mp4

**Comment by hiennguyen92** [comment]
@olegys thank you. Please re-check with version 1.0.0+3

**Comment by olegys** [comment]
@hiennguyen92 

Wonderful!
Works great )
Thank you for your quick reply!)
Good luck developing this awesome plugin!

**Comment by hiennguyen92** [comment]
@olegys thanks you.
