### ISSUE TITLE
I have questions about DevicePushTokenVoIP.

### ISSUE THREAD

**Issue by sokpheng** [hiennguyen92/flutter_callkit_incoming#100]
1. Will DevicePushTokenVoIP expire? How long?
2. How can I update DevicePushTokenVoIP ?

**Comment by zionnite** [comment]
1) Yes Device Push Token does expire, it expires for various many reasons check Firebase and Apple regarding that.
2) You can do a normal check like this
   ```
get user device token and update it to the user data in db
    now fetch that device token and called it tokenX
    get current token and call it currentToken
    if(currentToke == tokenX){
      //do nothing
    }else{
      //update the token in the db with the current token
      //tokenX will now be currentToken
    }

```

**Comment by zionnite** [comment]
Did it work for you??

**Comment by sokpheng** [comment]
> Did it work for you??

I do not yet start working on it.

**Comment by zionnite** [comment]
ok, when u need help, let me know
