### ISSUE TITLE
I just got this error when Press Accept call. IOS

### ISSUE THREAD

**Issue by sokpheng** [hiennguyen92/flutter_callkit_incoming#101]
Error Domain=NSOSStatusErrorDomain Code=561017449 "(null)"

**Comment by ycherniavskyi** [comment]
Are you sure that this is enough to troubleshoot the issue?

**Comment by sokpheng** [comment]
I found the issue. I have resolved it.

**Comment by tigranelyazyan** [comment]
@sokpheng  how you solved the issue?
