### ISSUE TITLE
about v1.0.1+8 , update

### ISSUE THREAD

**Issue by suhail600** [hiennguyen92/flutter_callkit_incoming#103]
> I just published v1.0.1+8, please check again.

@hiennguyen92 this is the only package was stable till previous version with small problems, and thank you for this package , since the latest update , 
1. app is crashing on receiving the call accept (checked in vivo, oneplus, redmi, samsung phones)
2. call is not accepted when clicked and tapping two three times somewhat opens the app
3. black screen is gone in debug mode , but app needs restart to route to the specific page , and all was fine working in previous version in profile mode (no crashing , routing properly ,).
5. receiving 2 call popup for a single call.
6. all routing doesn't working in debug and profile mode

**Comment by hiennguyen92** [comment]
you can try new version 1.0.2

**Comment by suhail600** [comment]
> you can try new version 1.0.2

@hiennguyen92  thank you for this update, since the latest update ,

1. app is crashing sometimes on receiving the call accept (checked in vivo, oneplus, redmi, samsung phones), only arises sometimes , please check .
2. ringtone played when in headset mode.

and can u please tell how to route to a specific screen with decoded data from notification

1. in terminated state notification payload is decoded but , cannot store it any where , so how can we achive routing to a specific screeen with message payload data, please help

**Comment by suhail600** [comment]
1. app is crashing on receiving the call accept (checked in vivo, oneplus, redmi, samsung phones), only arises sometimes,

other than this all other solved in 1.0.2

thanku

**Comment by faisalmushtaq007** [comment]
@suhail600 brother can you help me. I am not able to navigate when app is closed or when app is in background. Please help me. I am very much depressed due to this

**Comment by suhail600** [comment]
> @suhail600 brother can you help me. I am not able to navigate when app is closed or when app is in background. Please help me. I am very much depressed due to this

Use the new update , uninstall existing package and instal latest one, and see example , if your problem if just navigation , for navigation u should use context less navigation with global navigation , use google to see that or theres a link about that refered by package ahthor in one of the issues that was closed , please check that

**Comment by faisalmushtaq007** [comment]
@suhail600 i am using context less navigation. When the app is open or closed, navigation works fine. But when app is in background i.e., minimized, and i accept the call, it doesnt navigate to desired screen.
