### ISSUE TITLE
Sound not working in release mode

### ISSUE THREAD

**Issue by Omar-Khaium** [hiennguyen92/flutter_callkit_incoming#105]
I've tried using a custom ringtone sound by using `ringtonePath: system_ringtone_default`, 
![image](https://user-images.githubusercontent.com/40541185/166207733-12f0aa6f-7b97-4bdb-8b77-52b1c0b6dfac.png)

I've also placed my custom ringtone file in your package's android/app/src/main/res/raw folder by renaming it to system_ringtone_default.mp3
![image](https://user-images.githubusercontent.com/40541185/166207658-8dbb102b-7bc0-406c-a43f-2e2cf59cd1ad.png)

Funny thing is, the custom ringtone actually works in debug mode, while the app is on foreground, background, locked screen, and even while terminated. But in release mode, I was unable to play the custom ringtone file. When I push the notification, it goes without any sound, completely silent.

**Comment by hiennguyen92** [comment]
please try using another name

**Comment by colbapnauj** [comment]
I have the same issue.

**Comment by jbalani09** [comment]
I have the same Issue .
