### ISSUE TITLE
navigation issue is still there when app is in background

### ISSUE THREAD

**Issue by faisalmushtaq007** [hiennguyen92/flutter_callkit_incoming#106]
This issue:
Unhandled Exception: Null check operator used on a null value
E/flutter (11514): #0      NavigationService.isCurrent
package:kaidah/…/service/nav_service.dart:45
E/flutter (11514): #1      NavigationService.pushNamedIfNotCurrent
package:kaidah/…/service/nav_service.dart:37
E/flutter (11514): #2      listenerEvent.<anonymous closure>
package:kaidah/main.dart:73
E/flutter (11514): #3      listenerEvent.<anonymous closure>
package:kaidah/main.dart:54
E/flutter (11514): #4      _rootRunUnary (dart:async/zone.dart:1436:47)

**Comment by hiennguyen92** [comment]
Please check with example

**Comment by faisalmushtaq007** [comment]
@hiennguyen92 i am already using same. 
Have you tried when app is minimized????

**Comment by hiennguyen92** [comment]
have you tried with example? i have tried and tested on all cases
