### ISSUE TITLE
Ability invalidate voip token

### ISSUE THREAD

**Issue by olegys** [hiennguyen92/flutter_callkit_incoming#107]
Greetings @hiennguyen92 !  I'm glad to talk with you again :) Please tell me if we can remove the viop token and get a new one?  (for example, if I log out of one account and log into another on the same phone)

**Comment by hiennguyen92** [comment]
you should map token with user login on backend.

**Comment by olegys** [comment]
> you should map token with user login on backend.

Thanks for the quick response!  It turns out there is no way to do this programmatically, as with the firebase token?

**Comment by suhail600** [comment]
@zionnite 
can u help with naviagting to a page with payload data from notification in backgound and terminated state . payload data is fetched in all states but  how to use it when app is in background or terminated state

**Comment by olegys** [comment]
> 

I don't need a regular token, I need to renew the VoIP token

**Comment by zionnite** [comment]
> @zionnite 
> @hiennguyen92 
> can u help with naviagting to a page with payload data from notification in backgound and terminated state . payload data is fetched in all states but  how to use it when app is in background or terminated state
> 

Create an issue for that,

Let's not mixed up everything here

**Comment by suhail600** [comment]
> > @zionnite
> > @hiennguyen92
> > can u help with naviagting to a page with payload data from notification in backgound and terminated state . payload data is fetched in all states but  how to use it when app is in background or terminated state
> 
> Create an issue for that,
> 
> Let's not mixed up everything here

already done check about 
https://github.com/hiennguyen92/flutter_callkit_incoming/issues/104#issuecomment-1116918712

issue #104
