### ISSUE TITLE
Push Voip stop working after sometime period of times.

### ISSUE THREAD

**Issue by sokpheng** [hiennguyen92/flutter_callkit_incoming#108]
Hello Admin. How are you doing? I'm sorry to disturb you again.
I implemented push VoIP followed your instruction and made it work as expected. However, it stops receiving any VoIP after some time around 10mins. Can you tell me what I have missed?

**Comment by hiennguyen92** [comment]
if you send voip too much for testing. Maybe Apple added you to the blacklist. you can try restarting the device and try again

**Comment by sokpheng** [comment]
My app I in testflight.

**Comment by ycherniavskyi** [comment]
@sokpheng did you resolve your issue? It yes could you please explain how.
