### ISSUE TITLE
how can i open some screen when click accept call.It works when app open but click accept when app close it open Splash screen

### ISSUE THREAD

**Issue by Davud44** [hiennguyen92/flutter_callkit_incoming#11]

**Comment by hiennguyen92** [comment]
Hi @Davud44 
you should use `FlutterCallkitIncoming.activeCalls()` to check the call is active and natigation to screen in this case.

**Comment by Davud44** [comment]
> Hi @Davud44 you should use `FlutterCallkitIncoming.activeCalls()` to check the call is active and natigation to screen in this case.

Hi @hiennguyen92 Thanks for reply
