### ISSUE TITLE
On ios, no audio when create webrtc connection after accept incoming call

### ISSUE THREAD

**Issue by hieplee2997** [hiennguyen92/flutter_callkit_incoming#111]
I show incoming call from native with 
```let id = alert!["apns_session_id"] as? String ?? ""
    let nameCaller = alert!["caller"] as? String ?? ""
    let avatar = alert!["avatar_url"] as? String ?? ""
    let handle = alert!["handle"] as? String ?? ""
    let type = alert!["type"] as? String ?? ""
    
    

    let data = flutter_callkit_incoming.Data(id: id, nameCaller: nameCaller, handle: handle, type: type == "video" ? 1 : 0)
    SwiftFlutterCallkitIncomingPlugin.sharedInstance?.showCallkitIncoming(data, fromPushKit: true)
```
After tap answer button from Callkit, i will create stream and establish webrtc connection, but no audio in connection, just video works. I guest it conflict with audio session in Callkit.
The problem occurs when didActiveAudiosession callback run before webrtc connected. If after, it works fine.
Is it a bug or Is there something I missed? Thanks

P/s: If i set category is AVAudioSessionCategoryPlayback instead of AVAudioSessionCategoryPlayAndRecord it has audio but button enable speaker cannot toggle

Test on iOS 12.5
Plugin version 2.0.0

**Comment by hiennguyen92** [comment]
You can try with 1.0.2+1

**Comment by datpt11** [comment]
same issue in android. Some calls have no sound, some calls have sound but very low

**Comment by datpt11** [comment]
package version: 2.0.1+12
