### ISSUE TITLE
Running on IOS Emulator

### ISSUE THREAD

**Issue by luzayadio** [hiennguyen92/flutter_callkit_incoming#112]
Hi, I'm having a problem and I would like to know something. I installed the package and it works fine on android, but on my IOS emulator it doesn't accept to run the app, since you said it doesn't work on the IOS emulator, but at least it runs the app on the emulator it just doesn't work the notifications and others!?
<img width="951" alt="Screen Shot 2022-05-09 at 1 56 09 PM" src="https://user-images.githubusercontent.com/71708339/167414464-e621098a-c400-469a-b460-9b9d284b3dd7.png">

**Comment by ycherniavskyi** [comment]
In [README.md](../blob/master/README.md) clearly signed: iOS: ONLY WORKING ON REAL DEVICE, not on simulator(Callkit framework not working on simulator).

**Comment by mbilalakmal** [comment]
> In [README.md](../blob/master/README.md) clearly signed: iOS: ONLY WORKING ON REAL DEVICE, not on simulator(Callkit framework not working on simulator).

Maybe it should be clarified that the builds will no longer work on a Simulator. The current disclaimer can be misinterpreted as the functionality of the plugin not working on a Simulator.

**Comment by ozalisky** [comment]
> Maybe it should be clarified that the builds will no longer work on a Simulator. The current disclaimer can be misinterpreted as the functionality of the plugin not working on a Simulator.

The package won't crash your app on the simulator. Probably you missed something from the installation of the readme.

**Comment by luzayadio** [comment]
> > Maybe it should be clarified that the builds will no longer work on a Simulator. The current disclaimer can be misinterpreted as the functionality of the plugin not working on a Simulator.
> 
> The package won't crash your app on the simulator. Probably you missed something from the installation of the readme.

the app doesn't even want to run when I use the package, I don't know what to do anymore

**Comment by ozalisky** [comment]
Have you tried `flutter clean` and `pod install`?

**Comment by luzayadio** [comment]
I solved my problem with this example https://github.com/flutter/flutter/issues/94914#issuecomment-992898782
