### ISSUE TITLE
checkAndNavigationCallingPage()  running many times 3 to 4 times and thus resulting in screen duplication,

### ISSUE THREAD

**Issue by suhail600** [hiennguyen92/flutter_callkit_incoming#114]
> Ok. I will check it

@hiennguyen92  checkAndNavigationCallingPage(); is running many times 3 to 4 times and thus resulting in screen duplication, pushing same screen 3 to four times  please help with this

**Comment by hiennguyen92** [comment]
Please using https://github.com/hiennguyen92/flutter_callkit_incoming/blob/5ca15b339bca4f593ef1b09c9737130c1c122542/example/lib/main.dart#L106 for make sure not duplication

**Comment by suhail600** [comment]
i cant use this as i used another logic for navigaion , and solved in other way,
any way thanks brother
