### ISSUE TITLE
I am not able to get the call in IOS

### ISSUE THREAD

**Issue by hiren-devstree** [hiennguyen92/flutter_callkit_incoming#115]
import UIKit
import Flutter
import PushKit
import flutter_callkit_incoming
@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate , PKPushRegistryDelegate{
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    GeneratedPluginRegistrant.register(with: self)
    if #available(iOS 10.0, *) {
      UNUserNotificationCenter.current().delegate = self as? UNUserNotificationCenterDelegate
    }
      //Setup VOIP
       let mainQueue = DispatchQueue.main
       let voipRegistry: PKPushRegistry = PKPushRegistry(queue: mainQueue)
       voipRegistry.delegate = self
       voipRegistry.desiredPushTypes = [PKPushType.voIP]
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
    
  }
  // Call back from Recent history
      override func application(_ application: UIApplication,
                                continue userActivity: NSUserActivity,
                                restorationHandler: @escaping ([UIUserActivityRestoring]?) -> Void) -> Bool {

          guard let handleObj = userActivity.handle else {
              return false
          }

          guard let isVideo = userActivity.isVideo else {
              return false
          }
          let nameCaller = handleObj.getDecryptHandle()["nameCaller"] as? String ?? ""
          let handle = handleObj.getDecryptHandle()["handle"] as? String ?? ""
          let data = flutter_callkit_incoming.Data(id: UUID().uuidString, nameCaller: nameCaller, handle: handle, type: isVideo ? 1 : 0)
          //set more data
          data.nameCaller = "Johnny"
          SwiftFlutterCallkitIncomingPlugin.sharedInstance?.startCall(data, fromPushKit: true)

          return super.application(application, continue: userActivity, restorationHandler: restorationHandler)
      }

    // Handle updated push credentials
      func pushRegistry(_ registry: PKPushRegistry, didUpdate credentials: PKPushCredentials, for type: PKPushType) {
          print(credentials.token)
          let deviceToken = credentials.token.map { String(format: "%02x", $0) }.joined()
          print(deviceToken)
          //Save deviceToken to your server
          SwiftFlutterCallkitIncomingPlugin.sharedInstance?.setDevicePushTokenVoIP(deviceToken)
      }

      func pushRegistry(_ registry: PKPushRegistry, didInvalidatePushTokenFor type: PKPushType) {
          print("didInvalidatePushTokenFor")
          SwiftFlutterCallkitIncomingPlugin.sharedInstance?.setDevicePushTokenVoIP("")
      }
         // Handle incoming pushes
          func pushRegistry(_ registry: PKPushRegistry, didReceiveIncomingPushWith payload: PKPushPayload, for type: PKPushType, completion: @escaping () -> Void) {
              print("didReceiveIncomingPushWith")
              guard type == .voIP else { return }

              let id = payload.dictionaryPayload["id"] as? String ?? ""
              let nameCaller = payload.dictionaryPayload["nameCaller"] as? String ?? ""
              let handle = payload.dictionaryPayload["handle"] as? String ?? ""
              let isVideo = payload.dictionaryPayload["isVideo"] as? Bool ?? false

              let data = flutter_callkit_incoming.Data(id: id, nameCaller: nameCaller, handle: handle, type: isVideo ? 1 : 0)
              //set more data
              data.extra = ["user": "abc@123", "platform": "ios"]
              //data.iconName = ...
              //data.....
              SwiftFlutterCallkitIncomingPlugin.sharedInstance?.showCallkitIncoming(data, fromPushKit: true)
          }
}

**Comment by hiren-devstree** [comment]
@hiennguyen92 could you help me?
I have processed same steps from this https://github.com/hiennguyen92/flutter_callkit_incoming/blob/master/PUSHKIT.md.

**Comment by hiren-devstree** [comment]
when I am sending notification the app is working when in foreground but not in background or terminated mode.

**Comment by hiennguyen92** [comment]
Please make sure restart device and try again.(May be blocked by Apple due to spam)

**Comment by itsthetaste** [comment]
Looks like a bug in the example app.

getCurrentCall() async {
    //check current call from pushkit if possible
    var calls = await FlutterCallkitIncoming.activeCalls();
    final objCalls = json.decode(calls);
    if (objCalls is List) {
      if (objCalls.isNotEmpty) {
        print('DATA: $objCalls');
        this._currentUuid = objCalls[0]['id'];
        return objCalls[0];
      } else {
        this._currentUuid = "";
        return null;
      }
    }
  }

FlutterCallkitIncoming.activeCalls() returns a List not a String, so it's throwing an error.

Looks like it can be written as

getCurrentCall() async {
    //check current call from pushkit if possible
    var calls = await FlutterCallkitIncoming.activeCalls();
    if (calls is List) {
      if (calls.isNotEmpty) {
        print('DATA: $calls');
        this._currentUuid = calls[0]['id'];
        return calls[0];
      } else {
        this._currentUuid = "";
        return null;
      }
    }
  }

I think this might be the same issue others are mentioning as well.

**Comment by hiennguyen92** [comment]
thank
