### ISSUE TITLE
Encrypted data instead of email in call details

### ISSUE THREAD

**Issue by ozalisky** [hiennguyen92/flutter_callkit_incoming#116]
Hi, 
flutter_callkit_incoming 1.0.2 
Instead of email contact has encrypted data in call details:  

<img src="https://user-images.githubusercontent.com/40992789/167817891-954e04d5-ad84-4698-9ac5-b4c34a86e4fd.jpeg" width="50%" height="50%">

Parameters passed to package are correct:
```dart
{
    required String id,
    required String nameCaller,
    required String? avatar,
    required String? handle,
  }) {
    return <String, dynamic>{
      'id': id,
      'nameCaller': nameCaller,
      'avatar': avatar,
      'appName': kAppName,
      'handle': handle,
      'type': 1,
      'duration': 30000,
      'android': <String, dynamic>{
        'isCustomNotification': false,
        'isShowLogo': false,
        'ringtonePath': 'ringtone_default',
        'backgroundColor': '#0955fa',
        'actionColor': '#4CAF50',
        'isShowCallback': false
      },
      'ios': <String, dynamic>{
        'handleType': 'email',
        'supportsVideo': true,
        'maximumCallGroups': 1,
        'maximumCallsPerCallGroup': 1,
        'audioSessionMode': 'videoChat',
        'audioSessionActive': true,
        'audioSessionPreferredSampleRate': 44100.0,
        'audioSessionPreferredIOBufferDuration': 0.005,
        'supportsDTMF': false,
        'supportsHolding': false,
        'supportsGrouping': false,
        'supportsUngrouping': false,
        'ringtonePath': 'Ringtone.caf'
      }
    };

**Comment by bartonip** [comment]
Are you using LiveKit by any chance?

**Comment by ozalisky** [comment]
Nope.

**Comment by bartonip** [comment]
I've fixed this in my fork. The plugin stores the nameCaller and handle in the handle as an encrypted base64 string and uses that to get the correct data to CallKit. @hiennguyen92 The correct thing to do should be to pass that call to Flutter and have Flutter trigger a CXUpdate to set the localizedCallerName.

**Comment by hiennguyen92** [comment]
@bartonip it is used in case you open app from recent history phone book.(then you won't have any data input other than saved info)

**Comment by bartonip** [comment]
It causes the handle to be mangled in the Recent History list though, which is probably worse.

I think that we should have a method call on the Flutter plugin that allows us to send through a localizedCallerName so that can be set. Ideally we are storing the contacts on the Flutter side, storing them in native UI state is not pretty and feels hacky to me. What do you think? I am happy to write a PR.

**Comment by hiennguyen92** [comment]
I find the wrong handle is normal.  you can check it with Facebook messenger.  they also use it as id and hash. I would also be happy if you have some PR.
