### ISSUE TITLE
End & Accept button provides wrong data

### ISSUE THREAD

**Issue by ozalisky** [hiennguyen92/flutter_callkit_incoming#118]
package version 1.0.2  

Press `End & Accept` while there is another ongoing call will provide `event.body` data of an incoming videocall with `CallEvent.ACTION_CALL_ENDED` event.

Expectation: pressing `End & Accept` should provide data of the ongoing call with `CallEvent.ACTION_CALL_ENDED` event to end it and new parameters from an accepted call with `CallEvent.ACTION_CALL_ACCEPT` event.

**Comment by ozalisky** [comment]
@hiennguyen92 I can't create a PR for you to check it. 

For iOS I'm creating an additional variable 
```dart
    private var incomingData: Data?
```

and then in `case "showCallkitIncoming":` package checks if data is not null:  
```dart
    if (self.data == nil) {
        self.data = Data(args: getArgs)
        showCallkitIncoming(self.data!, fromPushKit: false)
    } else {
        self.incomingData = Data(args: getArgs)
        showCallkitIncoming(self.incomingData!, fromPushKit: false)
    }
```                

Then in provider 
```dart
            sendEvent(SwiftFlutterCallkitIncomingPlugin.ACTION_CALL_ENDED, self.data?.toJSON())
            
            self.data = Data(id: self.incomingData!.uuid, nameCaller: self.incomingData!.nameCaller, handle: self.incomingData!.handle, type: self.incomingData!.type)
            self.incomingData = nil
            action.fulfill()
```

This fix sends correct data back to the app.

Would this approach work for android?

**Comment by vedranivicatos** [comment]
Yes I have noticed this too. The issue I believe is in: SwiftFlutterCallkitIncomingPlugin.swift:
```
public func provider(_ provider: CXProvider, perform action: CXEndCallAction) {
        guard let call = self.callManager?.callWithUUID(uuid: action.callUUID) else {
            action.fail()
            return
        }
        call.endCall()
        self.callManager?.removeCall(call)
        if (self.answerCall == nil && self.outgoingCall == nil) {
            sendEvent(SwiftFlutterCallkitIncomingPlugin.ACTION_CALL_DECLINE, self.data?.toJSON())
            DispatchQueue.main.asyncAfter(deadline: .now() + 3.0) {
                action.fulfill()
            }
        }else {
            sendEvent(SwiftFlutterCallkitIncomingPlugin.ACTION_CALL_ENDED, self.data?.toJSON())
            action.fulfill()
        }
    }
```
The `sendEvent(SwiftFlutterCallkitIncomingPlugin.ACTION_CALL_ENDED, self.data?.toJSON())` to be precise. The call UUID is correct and the correct call will get ended, however the data passed to app side is wrong, it should be `call.data.toJSON()`. Due to this, I will probably fork it and create a PR.
Also, is there a specific reason as to why is there 3s delay on the call decline?

**Comment by hiennguyen92** [comment]
Ok. Let me check

**Comment by vedranivicatos** [comment]
Also, when doing the End & Accept call feature, the 
`public func provider(_ provider: CXProvider, didDeactivate audioSession: AVAudioSession)` 
triggers, which in return causes 
`self.callManager?.removeAllCalls()` 
to be called, removing all the calls from callManager object, even though there is still a CXCall in `callController.callObserver.calls`. So when you want to end the newly accepted call, that call is no longer in callManager's calls hence the `callManager.activeCalls() `will return just the UUID of the CXCall (no other data or extras which I'm personally using to search for and end the call via FlutterCallkitIncoming.endCall). Some of the workarounds would be to keep track of the UUID and then use it to end the call explicitly. However, I found commenting that line `self.callManager?.removeAllCalls()` seems to fix the issue as the call does not get removed and I can use FlutterCallkitIncoming.activeCalls() with some extra filtering to get the id of the call and end it. What exactly is the purpose of that line there?
