### ISSUE TITLE
Event handler not working on ios

### ISSUE THREAD

**Issue by senkia24** [hiennguyen92/flutter_callkit_incoming#124]
when CallEvent.ACTION_CALL_ACCEPT 
CallEvent.ACTION_CALL_DECLINE
not working on ios what am i miss

**Comment by wahabsohail** [comment]
how I perform the reject call function when the application is terminated or killed. I'm using flutter_callkit_incoming: 1.0.1+6 .

**Comment by vkamani23** [comment]
So how do I start my FlutterEngine and attach it to open the app when a call is received on the device when the app is terminated?

**Comment by tigranelyazyan** [comment]
@senkia24 Did you solve the issue?

**Comment by hiteshgarg002** [comment]
To solve this issue, start listener after 5-6 seconds after the app opens
Something like this

Future.delayed(Duration(seconds: 5),(){
        _flutterCallKitIncomingStreamSubscription =
          CallKitIncomingUtils.setupListener();
      });
