### ISSUE TITLE
ringtone not working

### ISSUE THREAD

**Issue by Davud44** [hiennguyen92/flutter_callkit_incoming#13]
Ringtone not working on release mode, android xiamo redmi 4x

**Comment by hiennguyen92** [comment]
I don't have a device(xiamo redmi 4x) to check this issue.

**Comment by ljsharp** [comment]
> Ringtone not working on release mode, android xiamo redmi 4x

How about you try out this package [flutter_ringtone_player](https://pub.dev/packages/flutter_ringtone_player)?

**Comment by baron7272** [comment]
How do i make it to use my default ringing tone?

**Comment by hiennguyen92** [comment]
Hi @Davud44 @ljsharp @baron7272 

I just deployed version 1.0.1.
please update it

using `ringtonePath: 'system_ringtone_default'`  or remove it for using system ringtone.

**Comment by baron7272** [comment]
thanks a lot

    On Monday, February 21, 2022, 10:00:07 AM GMT+1, Hien Nguyen ***@***.***> wrote:  
 
 


Hi @Davud44 @ljsharp @baron7272

I just deployed version 1.0.1.
please update it

using ringtonePath: 'system_ringtone_default' or remove it for using system ringtone.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
