### ISSUE TITLE
No Accept && Decline Button on Notification && No ringtone

### ISSUE THREAD

**Issue by mtellect** [hiennguyen92/flutter_callkit_incoming#130]
Hi, when the app is terminated, i get no action buttons on the notifications && no ringTone as well
![WhatsApp Image 2022-05-22 at 8 38 03 AM](https://user-images.githubusercontent.com/29234654/169684291-5ba2da28-3903-4df7-a141-9029b75d0405.jpeg)
l

**Comment by hiennguyen92** [comment]
Ca you give me model device and android version?

**Comment by mtellect** [comment]
Android s8, s10, Huawei p30 && Xiaomi Redmi Note 8 pro
Android 9 and 10

**Comment by mtellect** [comment]
https://user-images.githubusercontent.com/29234654/169693157-4b71e8c9-e1a8-438a-bc6a-b3226d8de135.mp4

**Comment by mtellect** [comment]
The call works well from a terminated when using this plugin version is fixed to flutter_callkit_incoming 1.0.1+6
