### ISSUE TITLE
Error when do await FlutterCallkitIncoming.activeCalls();

### ISSUE THREAD

**Issue by dkramorov** [hiennguyen92/flutter_callkit_incoming#132]
E/flutter (31530): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(error, Unsupported value: 'Data(args={})' of type 'class com.hiennv.flutter_callkit_incoming.Data', , null)
E/flutter (31530): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
E/flutter (31530): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
E/flutter (31530): <asynchronous suspension>
E/flutter (31530): #2      FlutterCallkitIncoming.activeCalls (package:flutter_callkit_incoming/flutter_callkit_incoming.dart:72:12)
E/flutter (31530): <asynchronous suspension>
E/flutter (31530): #3      SIPUAManager.checkCurrentCall (package:calleriha/sip_ua/sip_ua_manager.dart:211:17)
E/flutter (31530): <asynchronous suspension>
E/flutter (31530): #4      _MyCallScreenWidget._buildActionButtons.<anonymous closure> (package:calleriha/sip_ua/callscreen.dart:409:41)
E/flutter (31530): <asynchronous suspension>
E/flutter (31530):

**Comment by faizanMayo786** [comment]
This error is caused when you are not connected to internet. Check your internet connectino and try again:
As it is mentioned in the link Given:  [here](https://stackoverflow.com/questions/70140855/flutter-errorflutter-lib-ui-ui-dart-state-cc209-unhandled-exception-platf)

**Comment by VijaiCPrasad** [comment]
> This error is caused when you are not connected to internet. Check your internet connectino and try again: As it is mentioned in the link Given: [here](https://stackoverflow.com/questions/70140855/flutter-errorflutter-lib-ui-ui-dart-state-cc209-unhandled-exception-platf)

This error is not caused because of lack of connectivity. I face this too in android. Also, there is nothing common between the link you provided and the log in this issue except that both are "PlatformException".

**Comment by faizanMayo786** [comment]
Ok I am sorry for this I will look into it again

**Comment by PaulBout1** [comment]
Same error with version **^1.0.1+6** I'm downgrading to **^1.0.1+6**

**Comment by wahabsohail** [comment]
I am also facing the same issue. flutter_callkit_incoming: ^1.0.2+1
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(error, Unsupported value: 'Data(args={})' of type 'class com.hiennv.flutter_callkit_incoming.Data', , null)

**Comment by PaulBout1** [comment]
try that fork :  https://github.com/PaulBout1/flutter_callkit_incoming.git

**Comment by zionnite** [comment]
> try that fork : https://github.com/PaulBout1/flutter_callkit_incoming.git it works for me

I can see that this repo is directly linking up to @hiennguyen92 original repo, but please what version its working for you let me downgrade my version

**Comment by zionnite** [comment]
![Screen Shot 2022-06-01 at 10 29 10 AM](https://user-images.githubusercontent.com/10984801/171373367-7a5e1229-d9b6-4b1f-b9a1-c35e68d1004a.png)

@hiennguyen92 please see this

**Comment by suriyaKalidoss21** [comment]
I'm also facing this issue.

**Comment by suriyaKalidoss21** [comment]
> try that fork : https://github.com/PaulBout1/flutter_callkit_incoming.git
> it works for me

its having bugs

**Comment by suriyaKalidoss21** [comment]
get call not returning current call details

**Comment by rohithmahesh3** [comment]
I have fixed it for my project.
The function returning the data upon call was on `SharedPreferencesUtils.kt`
```kotlin
fun getDataActiveCalls(context: Context?): ArrayList<Data> {
    val json = getString(context, "ACTIVE_CALLS", "[]")
    return Utils.getGsonInstance()
        .fromJson(json, object : TypeToken<ArrayList<Data>>() {}.type)
}
```
I just created a new function 
```kotlin
fun getDataActiveCallsForFlutter(context: Context?): ArrayList<Data> {
    val json = getString(context, "ACTIVE_CALLS", "[]")
    return Utils.getGsonInstance().fromJson(json, object: TypeToken<ArrayList< Map<String, Any?>>>() {}.type)
}
```
and replaced the old one with it in `FlutterCallKitIncomingPlugin.kt`
```kotlin
  "activeCalls" -> {
      result.success(getDataActiveCallsForFlutter(context))
  }
```
here is my fork [flutter_callkit_incoming](https://github.com/rohithmahesh3/flutter_callkit_incoming). Hope it helps somebody.

**Comment by zionnite** [comment]
thanks @rohithmahesh3 , let me try it out.

**Comment by wahabsohail** [comment]
how I perform the reject call function when the application is terminated or killed. I'm using flutter_callkit_incoming: 1.0.1+6.

**Comment by zionnite** [comment]
@rohithmahesh3 , please how do i console the `FlutterCallkitIncoming.activeCalls()` payload (params) so as to know how to pass it to my calling page?

**Comment by VijaiCPrasad** [comment]
> Bro, please help me with which plugin version should I use?

Please do not hijack the issue. Open a new issue to ask your question or search for existing ones

**Comment by zionnite** [comment]
go with current version, a lot of bugs has been fixed and do well to make some changes according to @rohithmahesh3 suggestion and that should help

by the way @wahabsohail we are all learning, learn to learn

**Comment by suriyaKalidoss21** [comment]
In release mode its returning invalid json
[
{a: {}, b: 647334, c: Sanjay, d: , e: https://i.pravatar.cc/100, f: 1.0, g: 30000.0, h: Accept, i: Decline, j: Missed call, k: Call back, l: {oppositeUserId: 3233, roomId: 23}, m: {}, n: notification, o: true, p: true, q: false, r: system_ringtone_default, s: #0955fa, t: , u: #4CAF50, v: true, w: true}

]

**Comment by PaulBout1** [comment]
> In release mode its returning invalid json [ {a: {}, b: 647334, c: Sanjay, d: , e: https://i.pravatar.cc/100, f: 1.0, g: 30000.0, h: Accept, i: Decline, j: Missed call, k: Call back, l: {oppositeUserId: 3233, roomId: 23}, m: {}, n: notification, o: true, p: true, q: false, r: system_ringtone_default, s: #0955fa, t: , u: #4CAF50, v: true, w: true}
> 
> ]

Off topic. solution is here : https://github.com/hiennguyen92/flutter_callkit_incoming/issues/83#issuecomment-1096545652

**Comment by suriyaKalidoss21** [comment]
For production which is best version this : https://github.com/PaulBout1/flutter_callkit_incoming.git.   or. https://github.com/rohithmahesh3/flutter_callkit_incoming.git. Please suggest
