### ISSUE TITLE
on iOS -> Unexpectedly found nil while unwrapping an Optional value: file 

### ISSUE THREAD

**Issue by ahsanlaeiq** [hiennguyen92/flutter_callkit_incoming#135]
Hi i'm encountering issue with flutter_callkit_incoming on iOS;

ios/Runner/AppDelegate.swift

in pushRegistry i'm also getting my device token below;

pushRegistry -> deviceToken :b0471188f184d03dcef8efc81ea88daf51ea5b077cf22eb4a073121607049cb5

I'm passing below params on `await FlutterCallkitIncoming.showCallkitIncoming(params)`
`params=> {id: 7407, nameCaller: Mohammed Ahsan, appName: Mentor Health, avatar: https://i.pravatar.cc/100, handle: General Physician, type: 1, duration: 30000, extra: {caller_id: 1, calling_to: 7407, consultation_type: Online, appointment_id: 0, title: Mohammed Ahsan, caller_image: male.jpg}, textAccept: Accept, textDecline: Decline, textMissedCall: Missed call, textCallback: Call back, headers: {apiKey: Abc@123!, platform: flutter}, android: {isCustomNotification: true, isShowLogo: false, isShowCallback: false, ringtonePath: system_ringtone_default, backgroundColor: #FF162535, background: null, actionColor: #FFF1971A}, ios: {iconName: AppIcon, handleType: generic, supportsVideo: true, maximumCallGroups: 2, maximumCallsPerCallGroup: 1, audioSessionMode: videoChat, audioSessionActive: true, audioSessionPreferredSampleRate: 44100.0, audioSessionPreferredIOBufferDuration: 0.005, supportsDTMF: true, supportsHolding: true, supportsGrouping: false, supportsUngrouping: false, ringtonePath: system_ringtone_default}}`

```
Fatal error: Unexpectedly found nil while unwrapping an Optional value: file flutter_callkit_incoming/SwiftFlutterCallkitIncomingPlugin.swift, line 155
Fatal error: Unexpectedly found nil while unwrapping an Optional value: file flutter_callkit_incoming/SwiftFlutterCallkitIncomingPlugin.swift, line 155
* thread #1, queue = 'com.apple.main-thread', stop reason = Fatal error: Unexpectedly found nil while unwrapping an Optional value
    frame #0: 0x0000000191f2b650 libswiftCore.dylib`_swift_runtime_on_report
libswiftCore.dylib`_swift_runtime_on_report:
->  0x191f2b650 <+0>: ret    
libswiftCore.dylib`_swift_reportToDebugger:
    0x191f2b654 <+0>: b      0x191f2b650               ; _swift_runtime_on_report
libswiftCore.dylib`_swift_shouldReportFatalErrorsToDebugger:
    0x191f2b658 <+0>: adrp   x8, 337289
    0x191f2b65c <+4>: ldrb   w0, [x8, #0xae8]
Target 0: (Runner) stopped.
Lost connection to device.
```

**Comment by mschudt** [comment]
I have encountered the same error. id in params has to be a valid uuid string, otherwise that error will be thrown.
See https://developer.apple.com/documentation/foundation/nsuuid/1411662-init

**Comment by ahsanlaeiq** [comment]
> I have encountered the same error. id in params has to be a valid uuid string, otherwise that error will be thrown. See https://developer.apple.com/documentation/foundation/nsuuid/1411662-init

Thanks. It's working now by adding  `Uuid().v4()` in id.

**Comment by bilalgodesto** [comment]
I am also getting this error. Can you please explain the changes to do. I am not familiar with IOS
