### ISSUE TITLE
Fatal error: Unexpectedly found nil while unwrapping an Optional value for iOS

### ISSUE THREAD

**Issue by vengatesan125** [hiennguyen92/flutter_callkit_incoming#137]
flutter_callkit_incoming/SwiftFlutterCallkitIncomingPlugin.swift:155: Fatal error: Unexpectedly found nil while unwrapping an Optional value
flutter_callkit_incoming/SwiftFlutterCallkitIncomingPlugin.swift:155: Fatal error: Unexpectedly found nil while unwrapping an Optional value
* thread #1, queue = 'com.apple.main-thread', stop reason = Fatal error: Unexpectedly found nil while unwrapping an Optional value
    frame #0: 0x0000000186a17ebc libswiftCore.dylib`_swift_runtime_on_report
libswiftCore.dylib`:

**Comment by hiennguyen92** [comment]
https://github.com/hiennguyen92/flutter_callkit_incoming/issues/135
