### ISSUE TITLE
IOS call failed from terminate state 

### ISSUE THREAD

**Issue by sadaqatdev** [hiennguyen92/flutter_callkit_incoming#139]
Hi, Thank you for developing this plugin.

when app in terminated state , call is accepted it will not open the app, after press on called field button app is open , I attached video below.

https://user-images.githubusercontent.com/69109162/173061216-b8c04b5c-b6d8-4cee-a81d-d40a4811282b.mov

**Comment by sadaqatdev** [comment]
IOS 15.4 , plugin version is latest , flutter 3.0

**Comment by CHOMNANP** [comment]
Hi dear, can you share the step to make the call work on IOS?
We can send push notification to IOS but we're not sure how to make the call from our server to the IOS device.

**Comment by RobotKSR** [comment]
Hello! Also in need of good documentation how to send correct VOIP notification from Node.js and receive VOIP call using this plugin.

**Comment by sadaqatdev** [comment]
Hi, Thank you for developing this plugin.

when app in terminated state , call is accepted it will not open the app, after press on called field button app is open , I attached video below.

https://user-images.githubusercontent.com/69109162/173061216-b8c04b5c-b6d8-4cee-a81d-d40a4811282b.mov

**Comment by fbcouch** [comment]
Not sure if this will help, but I stumbled across this issue while seeing similar behavior – in my case, I was trying to connect to the call both by calling `FlutterCallkitIncoming.activeCalls()` and also in response to the `CallEvent.ACTION_CALL_ACCEPT` event. In my case, just removing the  `FlutterCallkitIncoming.activeCalls()` parts fixed it – the app correctly resumes from the terminated state and joins the call.

**Comment by bihim** [comment]
Have you find any solution for this issue?

**Comment by sergioprot** [comment]
@sadaqatdev, I had the same issue, the behaviour was just like in your video. The problem was, that I was calling `FlutterCallkitIncoming.endAllCalls()` when I didn't really need to. Could it be your case too?

**Comment by HensiStackApp** [comment]
Have you find any solution for this issue?

**Comment by haninhn** [comment]
hello have you fide solution. for this ? @HensiStackApp
