### ISSUE TITLE
How to track decline button Tapp status in terminated state

### ISSUE THREAD

**Issue by suriyaKalidoss21** [hiennguyen92/flutter_callkit_incoming#143]
My app is not in the background mode it is terminated state,

When we accept the call from the notification panel, it automatically navigates to the mobile app.

My problem is how to track when user tap decline.

Please provide Code knowledge on this.

**Comment by Musfick** [comment]
There is a case which named ACTION_CALL_DECLINE
```
try {
      FlutterCallkitIncoming.onEvent.listen((event) async {
        switch (event?.name) {
          case CallEvent.ACTION_CALL_DECLINE:
            debugPrint("ACTION_CALL_DECLINE");
            break;
        }
      });
    } on Exception {}
```

When app is terminated, Initialize the callbacks before start call.

**Comment by suriyaKalidoss21** [comment]
will try and update

**Comment by vkamani23** [comment]
> There is a case which named ACTION_CALL_DECLINE
> 
> ```
> try {
>       FlutterCallkitIncoming.onEvent.listen((event) async {
>         switch (event?.name) {
>           case CallEvent.ACTION_CALL_DECLINE:
>             debugPrint("ACTION_CALL_DECLINE");
>             break;
>         }
>       });
>     } on Exception {}
> ```
> 
> When app is terminated, Initialize the callbacks before start call.

How do I initialise callbacks before start call? Any help on this would be appreciated.

**Comment by suriyaKalidoss21** [comment]
Its working for the decline.But another problem here is during the app is in background im unable to navigate to a page when Accept button tapped

**Comment by suriyaKalidoss21** [comment]
@Musfick  Any solution for this?

**Comment by suriyaKalidoss21** [comment]
@vkamani23  @Musfick   By adding this event listener I'm unable to track the accept button event when the app is foreground.

Because its overrides by the terminated code event listener

Any help on this?

**Comment by MingSern** [comment]
@Musfick Any way to listen to decline event natively? Need to execute some function when the app is in terminated state.

**Comment by Ahmed2120** [comment]
did you find any solution ? @suriyaKalidoss21
