### ISSUE TITLE
app not wake up when is on terminated or background state (iOS)

### ISSUE THREAD

**Issue by fjserrano1** [hiennguyen92/flutter_callkit_incoming#144]
Hello!

I have a problem in iOS with pushkit. All works fine when app is in foreground, but when is in background or terminated the notification is not to able to show callkit.

My AppDelegate is a copy of the example

Any ideas? 

Thank you in advance

**Comment by Musfick** [comment]
Check if push notification is working in background or terminated state.
also check this issue
https://github.com/firebase/flutterfire/issues/6290#

**Comment by abdo400** [comment]
@fjserrano1 Did you fix this?

**Comment by abdo400** [comment]
@fjserrano1  Can you please share what you did? I am also facing the same issue. Thanks!

**Comment by waqadArshad** [comment]
@fjserrano1 Can you please share what you did? I am also facing the same issue. Thanks!
