### ISSUE TITLE
Can't showCallKitIncoming on iOS

### ISSUE THREAD

**Issue by abdo400** [hiennguyen92/flutter_callkit_incoming#146]
Hi,
Whenever I try calling FlutterCallkitIncoming.showCallkitIncoming I get the following error:
```
 thread # 1, queue = 'com.apple.main-thread', stop reason = Fatal error: Unexpectedly found nil while unwrapping an Optional value
    frame #0: 0x00000001e5f26458 libswiftCore.dylib`_swift_runtime_on_report
libswiftCore.dylib`_swift_runtime_on_report:
->  0x1e5f26458 <+0>: ret
libswiftCore.dylib`_swift_reportToDebugger:
    0x1e5f2645c <+0>: b      0x1e5f26458               ; _swift_runtime_on_report
libswiftCore.dylib`_swift_shouldReportFatalErrorsToDebugger:
    0x1e5f26460 <+0>: adrp   x8, 335240
    0x1e5f26464 <+4>: ldrb   w0, [x8, #0x45c]
```

I am using version 1.0.2+1 of the package

**Comment by vedranivicatos** [comment]
Can you provide some more info, exact code which calls FlutterCallkitIncoming.showCallkitIncoming and what you pass as params?

**Comment by minhtritc97** [comment]
#135

**Comment by abdo400** [comment]
@minhtritc97 Thanks, it works like that now. But only when the app is in running in fullscreen.

**Comment by minhtritc97** [comment]
> @minhtritc97 Thanks, it works like that now. But only when the app is in running in fullscreen.

config follow document
<img width="565" alt="image" src="https://user-images.githubusercontent.com/48729090/178264324-e004d849-f27b-4e7d-bd7e-ea58b8777586.png">

 then open project with xcode-> targets runner -> signing & capabilities -> tick 
<img width="435" alt="image" src="https://user-images.githubusercontent.com/48729090/178264799-60e07b98-fb75-4b53-ad22-c155122d27c5.png">

**Comment by abdo400** [comment]
I have these + VoIP but unfortunately its not working with me

**Comment by minhtritc97** [comment]
> I have these + VoIP but unfortunately its not working with me

in background, it only work when you call showCallkitIncoming in current screen, if you push to new screen then call showCallkitIncoming, it will not work

**Comment by abdo400** [comment]
Some research led me to VoIP again. I should send a VoIP notification, however, I am not quite sure how to do that. Any idea how?

I am getting the VoIP token from the asset method "getDevicePushTokenVoIP", then sending the notification to it via Firebase messaging (which I guess is the wrong part)

**Comment by abdo400** [comment]
For VoIP setup, this is what worked for me.
https://stackoverflow.com/questions/69504770/flutter-fcm-9-on-ios-14
