### ISSUE TITLE
If Android Terminated or Killed Then "Accept" Button not launching app

### ISSUE THREAD

**Issue by hpsolver** [hiennguyen92/flutter_callkit_incoming#147]

**Comment by hpsolver** [comment]
Device Version : Android 10

**Comment by nusjose** [comment]
I faced the same issue.

**Comment by kienntkaopiz** [comment]
i have same issue. 
I added this code and it works!

<img width="694" alt="Screen Shot 2022-07-19 at 15 10 35" src="https://user-images.githubusercontent.com/58588183/179700919-08060859-5ef3-4785-bce1-a28b670df494.png">
<img width="1003" alt="Screen Shot 2022-07-19 at 15 10 14" src="https://user-images.githubusercontent.com/58588183/179700935-323a9496-ba0e-4ca0-bc3a-ba9d48de131c.png">

**Comment by hiennguyen92** [comment]
I will check and update it

**Comment by haseebullahtahir** [comment]
Hy Dear @hiennguyen92 Good afternoon. can you update package

**Comment by hiennguyen92** [comment]
please using version 1.0.2+2
