### ISSUE TITLE
Crash when use FlutterCallkitIncoming.activeCalls() on Android

### ISSUE THREAD

**Issue by duyanpham** [hiennguyen92/flutter_callkit_incoming#152]
When I use function FlutterCallkitIncoming.activeCalls() It throw an error "PlatformException(error, Unsupported value: 'Data(args={})' of type 'class com.hiennv.flutter_callkit_incoming.Data', , null)" on Android 12 and Android 10

**Comment by hiennguyen92** [comment]
please using version 1.0.2+2
