### ISSUE TITLE
Keys and IVs are used in the clear (and published)

### ISSUE THREAD

**Issue by below** [hiennguyen92/flutter_callkit_incoming#155]
https://github.com/hiennguyen92/flutter_callkit_incoming/blob/d4a994845fd50d9d573ac64d656457fe2a34926e/ios/Classes/StringUtils.swift#L13

I am uncertain what the main objective is, why encrypting the data to CXHandle is even necessary, and I would like to understand the rationale.

That said, encrypting something with a key and iv that is listed in the clear and published on a public repository seems to defeat the purpose of security. After all, any attacker can find the necessary data to decrypt the information right here.

**Comment by hiennguyen92** [comment]
Encryption is only used to make it difficult to see unnecessary information (show in Call history book - Social Profile)
if not encoded, it will show json here. here we encode it to make sure the data is not read easily. it is only used by the app when decryption is needed.(like Messenger or any social)

**Comment by below** [comment]
Who would see this information though? Is the CXHandleAPI untrustworthy?

**Comment by hiennguyen92** [comment]
this information is only used by the app, save info to call history book and get it out when needed.(similar to save info local by system app)

CXHandle it is apple's API.

<img width="433" alt="image" src="https://user-images.githubusercontent.com/3755347/186709204-9537cd4c-b3d9-49d3-85c8-045ed6b12bb7.png">

**Comment by below** [comment]
It appears you are encrypting the data when sending it to CXHandle, and decrypt it when you get it back.

What is the angle of attack you are protecting the information against?

**Comment by hiennguyen92** [comment]
like I said above, if not encrypted all that info will show up as raw(in social profile above)

**Comment by dhoepfl** [comment]
As this text is intended to be shown to the user, it should be human readable.
At the very least it should be something like "Flutter: <userid> - (<internal data>)".
