### ISSUE TITLE
App crashes on ios when showing call via fcm

### ISSUE THREAD

**Issue by abdulkash** [hiennguyen92/flutter_callkit_incoming#156]
lutter_callkit_incoming/SwiftFlutterCallkitIncomingPlugin.swift:155: Fatal error: Unexpectedly found nil while unwrapping an Optional value
2022-07-30 00:53:28.569685+0100 Runner[99582:6634921] flutter_callkit_incoming/SwiftFlutterCallkitIncomingPlugin.swift:155: Fatal error: Unexpectedly found nil while unwrapping an Optional value

**Comment by amani27** [comment]
> lutter_callkit_incoming/SwiftFlutterCallkitIncomingPlugin.swift:155: Fatal error: Unexpectedly found nil while unwrapping an Optional value 2022-07-30 00:53:28.569685+0100 Runner[99582:6634921] flutter_callkit_incoming/SwiftFlutterCallkitIncomingPlugin.swift:155: Fatal error: Unexpectedly found nil while unwrapping an Optional value

Were you trying on simulator or real device?

**Comment by abdulkash** [comment]
yeah i was trying in on a real device but it works very well when using pushkit

**Comment by amani27** [comment]
> pushkit

Did you end up using native solution? Or is it some other plugin you're talking about? @abdulkash ?

**Comment by abdulkash** [comment]
Yeah

**Comment by henriquetroiano** [comment]
You need to use VoIP push notifications.
Push notifications are not allowed to perform call actions. The system will kill your app.
When you receive a voip push, you need to imediately show the callkit. If you dont, the system will kill your app too.
This is the reason why you cant show callkit on fcm push.

**Comment by henriquetroiano** [comment]
There is 2 main types of push notifications: VoIP push and regular push. Got it ?

**Comment by henriquetroiano** [comment]
@abdulkash show me the code you are trying to show the callkit. I think that you are trying to pass objective C params on a swift code.

**Comment by beebobox** [comment]
I had the same issue, but i was using VOIP Push.
The reason that the app was crashing was that, when I sent the voip push notification from my server the id parameter was an empty string. This also caused the error: Fatal error: Unexpectedly found nil while unwrapping an Optional value.
@hiennguyen92: is it possible to validate if the id parameter is empty, instead of crashing?

**Comment by kevinZartek** [comment]
for me giving a integer value instead of uuid caused this issue

**Comment by arslankaleem7229** [comment]
Any solution for this ?

**Comment by hiennguyen92** [comment]
make sure `id` is UUID (v4)
