### ISSUE TITLE
how to dismiss when caller ended call

### ISSUE THREAD

**Issue by zaycode** [hiennguyen92/flutter_callkit_incoming#157]
how to dismiss when caller ended call before take action accepted or rejected

**Comment by hiennguyen92** [comment]
using ```await FlutterCallkitIncoming.endCall(params);```

**Comment by nikhilkWinjit** [comment]
**FlutterCallkitIncoming.endCall** requires **UUID** as parameter.
Use `await FlutterCallkitIncoming.endCall(this.uuid);`

**Comment by yoer** [comment]
when click top popup window, and callkit ui switch to full; now call FlutterCallkitIncoming.endCall(uuid) is not end!! the full window still exist after call
