### ISSUE TITLE
iOS Call Screen doesn't appear on background/terminate

### ISSUE THREAD

**Issue by NathanaelNeria** [hiennguyen92/flutter_callkit_incoming#158]
I've read the pushkit.md and followed the codes for swift, but i have some questions

1. Can the call screen be triggered on background/terminate using Apple Push Notification service certificate? i'm only getting a pop up notification
2. if no, how to trigger the call screen using VOIP certificate when receiving push notification?

i'm kinda confused on how to implement that native iOS part, please give me some guidance

**Comment by waleed-sofstica** [comment]
Yeah thats the issue I am also facing...

**Comment by pavanjaju** [comment]
+1 Any update on this?

**Comment by hiennguyen92** [comment]
you can only use VoIP service certificate

please check https://github.com/hiennguyen92/flutter_callkit_incoming/blob/master/PUSHKIT.md
and
example: https://github.com/hiennguyen92/flutter_callkit_incoming/blob/master/example/ios/Runner/AppDelegate.swift

**Comment by beebobox** [comment]
Hi
I have just upgraded to flutter 3, and also updated to 1.0.2+2.
Before this upgrade the call screen appeared in all 3 states, terminated, backgrounded and active.
Now I does only appear when the app is active.

I have an excact copy of your AppDelegateSwift, and nothing has changed other than the 2 upgrades.
Any ideas on where the issue could be?

br. Beebo.

**Comment by beebobox** [comment]
It had been a while since i uninstalled the app, and i had made several updates where i just installed on top both directly from xcode or from testflight.

I fixed the issue by uninstalling the app, and simply reinstalled it. No code change.

**Comment by pavanjaju** [comment]
What made it work for me, if creating an ad-hoc build and then trying the
prod VoIP push, instead of sandbox.

**Comment by hiennguyen92** [comment]
In some cases Apple blocks VoIP to avoid spam.(maybe you tested too much on same device) please use product certificate as an instead to sandbox

**Comment by beebobox** [comment]
Strange thing was that is was working in active mode both on sandbox and prod, so the Push got trough.. but sometimes the simplest thing does the trick :)

**Comment by kevinZartek** [comment]
I am using fcm push notifications to trigger call both in android and ios. In android it works even when the app is in background, but in ios I am getting push notification but call kit ui is not triggered. Do we need to implement push kit even if fcm package is used ? if yes, I have read pushkit.md file and i have covered steps upto generating .p12 file. After that what exactly should I do ?
