### ISSUE TITLE
The plugin `flutter_callkit_incoming` requires your app to be migrated to the Android embedding v2. Follow the steps on https://flutter.dev/go/android-project-migration and re-run this command.

### ISSUE THREAD

**Issue by sadaqatkarimi** [hiennguyen92/flutter_callkit_incoming#16]
e: /Users/everythingapple/developer/flutter/.pub-cache/git/flutter_callkit_incoming-37674da0a1c410c04df2a6fa7a64dd4a283f5a3d/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/FlutterCallkitIncomingPlugin.kt: (47, 19): Unresolved reference: MethodChannel
e: /Users/everythingapple/developer/flutter/.pub-cache/git/flutter_callkit_incoming-37674da0a1c410c04df2a6fa7a64dd4a283f5a3d/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/FlutterCallkitIncomingPlugin.kt: (50, 13): Unresolved reference: EventChannel
e: /Users/everythingapple/developer/flutter/.pub-cache/git/flutter_callkit_incoming-37674da0a1c410c04df2a6fa7a64dd4a283f5a3d/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/FlutterCallkitIncomingPlugin.kt: (54, 5): 'onMethodCall' overrides nothing
e: /Users/everythingapple/developer/flutter/.pub-cache/git/flutter_callkit_incoming-37674da0a1c410c04df2a6fa7a64dd4a283f5a3d/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/FlutterCallkitIncomingPlugin.kt: (54, 46): Unresolved reference: MethodCall
e: /Users/everythingapple/developer/flutter/.pub-cache/git/flutter_callkit_incoming-37674da0a1c410c04df2a6fa7a64dd4a283f5a3d/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/FlutterCallkitIncomingPlugin.kt: (54, 75): One type argument expected for class Result<out T>
e: /Users/everythingapple/developer/flutter/.pub-cache/git/flutter_callkit_incoming-37674da0a1c410c04df2a6fa7a64dd4a283f5a3d/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/FlutterCallkitIncomingPlugin.kt: (130, 34): Unresolved reference: EventChannel
e: /Users/everythingapple/developer/flutter/.pub-cache/git/flutter_callkit_incoming-37674da0a1c410c04df2a6fa7a64dd4a283f5a3d/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/FlutterCallkitIncomingPlugin.kt: (132, 32): Unresolved reference: EventChannel
e: /Users/everythingapple/developer/flutter/.pub-cache/git/flutter_callkit_incoming-37674da0a1c410c04df2a6fa7a64dd4a283f5a3d/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/FlutterCallkitIncomingPlugin.kt: (134, 9): 'onListen' overrides nothing

**Comment by hiennguyen92** [comment]
Hi @sadaqatkarimi 
you should upgrade your app https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects

**Comment by sadaqatkarimi** [comment]
thank you
