### ISSUE TITLE
Programically "click" accept or decline?

### ISSUE THREAD

**Issue by beebobox** [hiennguyen92/flutter_callkit_incoming#161]
Hi Hien.
First of all thank you so much for this package. It is essential for my project :)

I have a accept and decline buttons in displayed in my UI if the application is active when the call comes in, but i need an option to programmically "click" either accept or decline, so that i can close the popup box. 

Is that a possibility?

br. 
Jacob

**Comment by hiennguyen92** [comment]
i think it doesn't seem feasible with iOS.
