### ISSUE TITLE
errorr activeCalls() in android

### ISSUE THREAD

**Issue by phucdth12a** [hiennguyen92/flutter_callkit_incoming#162]
i use demo: https://github.com/hiennguyen92/flutter_callkit_incoming/blob/master/example/lib/main.dart

but after call await FlutterCallkitIncoming.showCallkitIncoming(params);
i call  await FlutterCallkitIncoming.activeCalls();

and receive error: PlatformException(error, Unsupported value: 'Data(args={})' of type 'class com.hiennv.flutter_callkit_incoming.Data', , null). 

i see code revert to base (https://github.com/hiennguyen92/flutter_callkit_incoming/pull/142) 

version: 1.0.2+1

**Comment by phucdth12a** [comment]
i change in file yaml it ok.
# flutter_callkit_incoming: ^1.0.2+1
  # flutter_callkit_incoming: any
  flutter_callkit_incoming:
    git:
      url: https://github.com/hiennguyen92/flutter_callkit_incoming.git
      ref: master

**Comment by FutureSages** [comment]
@phucdth12a It would be great if you could update the package on [pub.dev](https://pub.dev). Thank you.
