### ISSUE TITLE
java.io.FileNotFoundException: /storage/emulated/0/Android/data/com.android.thememanager/files/MIUI/.ringtone/Swan.mp3: open failed: EACCES (Permission denied)

### ISSUE THREAD

**Issue by abdulkash** [hiennguyen92/flutter_callkit_incoming#164]
W/System.err(24232): java.io.FileNotFoundException: /storage/emulated/0/Android/data/com.android.thememanager/files/MIUI/.ringtone/Swan.mp3: open failed: EACCES (Permission denied)
W/System.err(24232): 	at libcore.io.IoBridge.open(IoBridge.java:575)
W/System.err(24232): 	at java.io.FileInputStream.<init>(FileInputStream.java:160)
W/System.err(24232): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1221)
W/System.err(24232): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1199)
W/System.err(24232): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1164)
W/System.err(24232): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1084)
W/System.err(24232): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1030)

Throws this exception when recieving incoming call and deosn't play the ringtone only vibrates

**Comment by hiennguyen92** [comment]
please using version 1.0.2+2
