### ISSUE TITLE
IOS accept Call issue

### ISSUE THREAD

**Issue by sokphengcheang** [hiennguyen92/flutter_callkit_incoming#165]
Hello long time no see, I face some issues after upgrading to flutter 3 and the latest version. as below
![Screen Shot 2022-08-25 at 11 49 17 AM](https://user-images.githubusercontent.com/27798903/186577649-88c04d6a-be3e-4d6d-8517-716ceaf9a798.png)
this error was caused by calling Active call. however is there any way to retrieve data when accept ? beside activeCall

Sometimes accepting a call from the lock screen and background won't open the app for me too.

**Comment by kostricanitechnology** [comment]
Hello,

I have same issue, did you find any solution? Can you share how you had it before to update the flutter version?

**Comment by Ahmed2120** [comment]
did you find any solution
