### ISSUE TITLE
Not getting call in terminated state

### ISSUE THREAD

**Issue by malukishtiaq** [hiennguyen92/flutter_callkit_incoming#166]
Hi

I hope you are fine. I am working on video call app using agora. For iOS I am sending voip notifications to other iOS device to wake up. It works properly only when app is opened or in background. I am having problem in terminated state of app on iOS. I send voip notifications similar to iOS device but it does not wake up the device. Can anyone help?

**here is my swift code.**

Info.plist

`<key>UIBackgroundModes</key>
	<array>
		<string>fetch</string>
		<string>processing</string>
		<string>remote-notification</string>
		<string>voip</string>
	</array>`

`
 // Handle updated push credentials
    func pushRegistry(_ registry: PKPushRegistry, didUpdate credentials: PKPushCredentials, for type: PKPushType) {
        print(credentials.token)
        let deviceToken = credentials.token.map { String(format: "%02x", $0) }.joined()
        SwiftFlutterCallkitIncomingPlugin.sharedInstance?.setDevicePushTokenVoIP(deviceToken)
    }
    
    func pushRegistry(_ registry: PKPushRegistry, didInvalidatePushTokenFor type: PKPushType) {
        SwiftFlutterCallkitIncomingPlugin.sharedInstance?.setDevicePushTokenVoIP("")
    }
    
    func pushRegistry(_ registry: PKPushRegistry, didReceiveIncomingPushWith payload: PKPushPayload, for type: PKPushType, completion: @escaping () -> Void) {
        guard type == .voIP else { return }
        let id = UUID().uuidString
        let payloadDict = payload.dictionaryPayload["aps"] as! Dictionary<String, Any>
        let bodyDict = payloadDict["data"] as! Dictionary<String, String>
        let firstName = bodyDict["FirstName"] as? String ?? ""
        let lastName = bodyDict["LastName"] as? String ?? ""
        let nameCaller =  firstName + " " + lastName;
        let handle = bodyDict["handle"] as? String ?? ""
        let isVideo = true
        let image = bodyDict["CallerImage"] as? String ?? ""
        let callerImage =  image
        let channelId = bodyDict["channelId"] as? String ?? ""
        let senderMemberId = bodyDict["senderMemberId"] as? String ?? ""
        let recieverMemberId = bodyDict["recieverMemberId"] as? String ?? ""
        let routePath = bodyDict["routePath"] as? String ?? ""

        var info = [String: Any?]()
        info["id"] = id
        info["nameCaller"] = nameCaller
        info["handle"] = "any"
        info["type"] = 0
        info["extra"] = ["routePath": routePath, "platform": "ios", "recieverMemberId":recieverMemberId, "senderMemberId":senderMemberId,"channelId":channelId,"callerImage":callerImage, "isVideo":isVideo]
        SwiftFlutterCallkitIncomingPlugin.sharedInstance?.showCallkitIncoming(flutter_callkit_incoming.Data(args: info), fromPushKit: true)
    }`

**Comment by hiennguyen92** [comment]
please try with example
https://github.com/hiennguyen92/flutter_callkit_incoming/blob/master/example/ios/Runner/AppDelegate.swift
