### ISSUE TITLE
incoming call notification call and accept buttons seems to have been clipped out in android

### ISSUE THREAD

**Issue by sagnik-sanyal** [hiennguyen92/flutter_callkit_incoming#167]
on receiving a notification in android for incoming call the accept and deny buttons seems to have been clipped out and not being displayed properly. Please have a look at the attachment provided. Any current fix for that?
![0ca68bc7-9a79-4114-a194-22e82eff0e10](https://user-images.githubusercontent.com/94127463/187618949-6e89fffc-aa6e-47ee-b24c-7a43e85fc259.jpg)
Also if i change to isCustomNotification flag to false the notification accept/deny colours aren't being displayed properly
![WhatsApp Image 2022-08-31 at 12 43 50 PM](https://user-images.githubusercontent.com/94127463/187620493-82d58db3-70b9-4b51-9c18-cb5e765bd426.jpeg)

**Comment by sagnik-sanyal** [comment]
This issue is specific to Android 12

**Comment by jimykhan** [comment]
Hi dear have u achieved your goals I am trying to navigate to the video calling screen once pressed accept button but i did not have any suggestions thanks.

**Comment by sagnik-sanyal** [comment]
You can check out the example the listeners are there for that purpose only. It should listen to the changes from the starting of the app and route to specific screen accordingly

**Comment by promych** [comment]
Same.
xiaomi 12 / android 12

**Comment by idrats** [comment]
Any updates? Also have this error

**Comment by anocean2** [comment]
there is a solution in this pull request #196

**Comment by hiennguyen92** [comment]
please upadte version 1.0.3+1. props `isCustomSmallExNotification`
