### ISSUE TITLE
Android's answer or decline button in a terminated state does nothing but launch the app.

### ISSUE THREAD

**Issue by akramAssi** [hiennguyen92/flutter_callkit_incoming#169]

**Comment by maulikchak** [comment]
can u share a full file please so we can understand better

**Comment by akramAssi** [comment]
video
https://drive.google.com/file/d/1t-h4D0Rez95VnbdFwN9NP3Km6XJoG6Z_/view?usp=sharing
code
[page.txt](https://github.com/hiennguyen92/flutter_callkit_incoming/files/9586644/page.txt)

**Comment by quinvq** [comment]
Same issue (flutter 3.3)
