### ISSUE TITLE
How i remove CallKit lable from full screen call intent?

### ISSUE THREAD

**Issue by sadaqatkarimi** [hiennguyen92/flutter_callkit_incoming#17]
![WhatsApp Image 2022-01-12 at 12 46 19 PM](https://user-images.githubusercontent.com/69109162/149086534-9ddb8f42-62aa-4f0c-8045-1aa93d2ec4ad.png)

**Comment by hiennguyen92** [comment]
@sadaqatkarimi please set 
android: {
isShowLogo: false
}

**Comment by sadaqatkarimi** [comment]
thank you.
