### ISSUE TITLE
FlutterCallkitIncoming.activeCalls(): error response data

### ISSUE THREAD

**Issue by lannes** [hiennguyen92/flutter_callkit_incoming#171]
`FlutterCallkitIncoming.activeCalls()` method not return **json** readable, it's return **gson** {a: , b: , c:, d:, e: f:, ...}

**Comment by cosnomi** [comment]
This issue can be resolved by #83. In my case, adding `-keep class com.hiennv.flutter_callkit_incoming.** { *; }` in proguard-rules.pro solved the issue.
It might be helpful to have this config in README.me. (I spent hours to find this.)

**Comment by lannes** [comment]
> This issue can be resolved by #83. In my case, adding `-keep class com.hiennv.flutter_callkit_incoming.** { *; }` in proguard-rules.pro solved the issue. It might be helpful to have this config in README.me. (I spent hours to find this.)

Thank you very much, I will try it
