### ISSUE TITLE
Answer and Decline buttons Issue 

### ISSUE THREAD

**Issue by appwebprogrammer** [hiennguyen92/flutter_callkit_incoming#172]
i am using agora and i create my own screen for 2 users start the call or video call, and i use call kit for display notification,
when the app is opened and notification received no problems and when the user click on answer it navigate him to answer screen, but when the app totally closed  when the the user click on answer button its not navigate to the answer where the other user is waiting its only opens the app any solution for this please

**Comment by hiennguyen92** [comment]
please check https://github.com/hiennguyen92/flutter_callkit_incoming/blob/be650a7701fd2c6ad64996cd243bd2ed98a6f5b5/example/lib/main.dart#L101

**Comment by appwebprogrammer** [comment]
var currentCall = await getCurrentCall(); get null data i tried it before

**Comment by appwebprogrammer** [comment]
I need your help i use your plugin to view incoming calls, my problem is when the user receive background  notification when app is terminated, i can't navigate to answer screen when click answer, and if you have another way to open the answer screen give it to me
