### ISSUE TITLE
[Android] Accept button on full-screen triggers a decline event

### ISSUE THREAD

**Issue by mdusko** [hiennguyen92/flutter_callkit_incoming#175]
Hello @hiennguyen92 
Can you please check this case?
Tested on Android 10 and Android 12

Thank you.

**Comment by mdusko** [comment]
Update:
This happens if I immediately call **FlutterCallkitIncoming.endAllCalls()** method after the accepted call when the app is in the background (pressed accept button in full screen).

I checked the native code (android) and saw that is expected behavior.
![image](https://user-images.githubusercontent.com/65610208/189691671-9e0c3c48-c2ce-47b1-b99b-52a3b2aaf949.png)

So, I will close this because this is not a bug.

**Comment by wenrong443** [comment]
![image](https://user-images.githubusercontent.com/29721778/198465304-5286d553-1d26-4fe9-831a-40dca785f0a4.png)

It also have display issue on xiaomi devices
