### ISSUE TITLE
PlatformException(error, call.arguments() must not be null, , null) , after calling await FlutterCallkitIncoming.endAllCalls();

### ISSUE THREAD

**Issue by sadaqatkarimi** [hiennguyen92/flutter_callkit_incoming#18]
PlatformException(error, call.arguments() must not be null, , null) , 

after calling await FlutterCallkitIncoming.endAllCalls();

**Comment by marcoberetta96** [comment]
duplicate of https://github.com/hiennguyen92/flutter_callkit_incoming/issues/12
