### ISSUE TITLE
Incoming call notification not appear after update to Flutter 3.3 (Android)

### ISSUE THREAD

**Issue by booooohdan** [hiennguyen92/flutter_callkit_incoming#182]
I use flutter_callkit_incoming: ^1.0.2+2 only with Android at Flutter 2.10.3 and all worked fine.
After updating the project to Flutter 3.3 in debug mode:
- all work well
In release mode (after building in Codemagic CI/CD) 
- calls in background and terminated states stopped working
- calls in the foreground (when the app is open) work well. 
No errors in Sentry, push notification works well
App has "Ignore Battery Optimization" permission

**Comment by JoshanTandukar** [comment]
Channel name seems like giving this issue.

**Comment by santhoshrao519** [comment]
I'm also facing same issue, breaking my head to solve it. Anyone got it fix?

**Comment by booooohdan** [comment]
> I'm also facing same issue, breaking my head to solve it. Anyone got it fix?

Are you tried Flutter 3.3? Maybe it's working with 3.0

**Comment by idrats** [comment]
The same issue after updating to Flutter 3.3.+

**Comment by booooohdan** [comment]
@idrats @santhoshrao519 did you try with Flutter 3.0, not 3.3? Maybe the package works with 3.0?

**Comment by idrats** [comment]
@booooohdan yes, there were no problem on Flutter 3.0.5

**Comment by anocean2** [comment]
The same issue after updating to Flutter 3.3.4

**Comment by santhoshrao519** [comment]
downgraded to flutter 3.0.5, when i try with getActiveCalls()
I'm getting Unhandled Exception: PlatformException(error, Missing type parameter., , null) exception in app terminated state

**Comment by jimykhan** [comment]
Hi guys I am facing the same issue in debug it works fine but not working in the release even I try 3.0.0 3.0.5 and 3.3.4 3.3.5 same issue is not working in the release any other solution

**Comment by santhoshrao519** [comment]
@jimykhan Try

@pragma('vm:entry-point')
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  // code here
}

**Comment by neilhosey** [comment]
Is this being looked at?

**Comment by booooohdan** [comment]
> @pragma('vm:entry-point') Future _firebaseMessagingBackgroundHandler(RemoteMessage message) async { // code here }

Resolved
