### ISSUE TITLE
FlutterCallkitIncoming.onEvent.listen not working on Android when app is terminated

### ISSUE THREAD

**Issue by AAkira** [hiennguyen92/flutter_callkit_incoming#183]
`FlutterCallkitIncoming.onEvent.listen` is not working on Android when an app is terminated.

||Terminated(killed)|Background(running)|Foreground(running)|
|-|-|-|-|
|Android|x|o|o|o|
|iOS|o|o|o|

I think we need to be able to get an init event value like in Firebase messaging library.

cf. [`FirebaseMessaging.instance.getInitialMessage()`](https://github.com/firebase/flutterfire/blob/master/packages/firebase_messaging/firebase_messaging/lib/src/messaging.dart#L90-L92)

Flutter version: 3.0.5
Library version: 1.0.2+2

**Comment by ChiPhanTlm** [comment]
same here, any idea

**Comment by madhukarNumen** [comment]
Same for me. Any update on this issue?

**Comment by santhoshrao519** [comment]
same issue here, any solution?

**Comment by mortezasojodi** [comment]
use the firebase background message, this event is not fired on terminate.

  FirebaseMessaging.onBackgroundMessage(firebaseMessagingBackgroundHandler);
  Future<void> firebaseMessagingBackgroundHandler(RemoteMessage message) async {
    // AwesomeNotifications().createNotificationFromJsonData(message.data);
    await Firebase.initializeApp();
    notificationHandler(message);
  }
Future<void> notificationHandler(RemoteMessage message) async {
  if (message.data['title'] == 'Message') {
    messageHandler.showMessageNotification(message.data['body']);
  }
  if (message.data['title'] == 'Call') {
    print(message.data);
    messageHandler.showIncomingCallNotification(message.data['body']);
  }

}

**Comment by silvanfischer** [comment]
It's still not working in the current version on master. Having the app build as release type and then killed, the Android Intents (accept, decline, etc) are not passed to the event handler. The cause of this is this commit here: d6b37c61

**Comment by tunm1228** [comment]
I am having this problem too
