### ISSUE TITLE
Events are not fired when the app is closed. #187 solve the issue. Can you please release a new version with the #187 ?

### ISSUE THREAD

**Issue by henriquetroiano** [hiennguyen92/flutter_callkit_incoming#188]
Hello, @hiennguyen92 !

When the app is fully terminated, when we click on accept button, the app opens, but the event call accept is not fired.
Is this expected ?
maybe the #187 should resolve this issue! Can you please upload a new version with the getLastestEvent method?

**Comment by abdo400** [comment]
Any idea how to use this within the flutter app?

**Comment by henriquetroiano** [comment]
The #187 is not released until now, @abdo400 .
The way I did was using UserDefaults on iOS. On android the ecents are easily handled.

**Comment by abdo400** [comment]
Actually its working fine with me on iOS.
Rejecting and accepting calls when app is terminated.

But I can't detect the reject call event when app is terminated for Android so I thought I might use this to fix it.

**Comment by jimykhan** [comment]
@abdo400  did you check in release mode its okay for me in debug android and not working in release mode
@henriquetroiano can u please guide

**Comment by henriquetroiano** [comment]
Hi @jimykhan 
The callkit is not working on closed app in release mode ?

**Comment by jimykhan** [comment]
and also work from in flutter 3.0.5

**Comment by jimykhan** [comment]
in release even not working if application in background

**Comment by henriquetroiano** [comment]
@jimykhan  Are you using Android or iOS

**Comment by jimykhan** [comment]
android

**Comment by jimykhan** [comment]
@henriquetroiano Is it working for You in release?

**Comment by henriquetroiano** [comment]
Did you configured Firebase.onBackgroundMessage ?

**Comment by henriquetroiano** [comment]
> @henriquetroiano Is it working for You in release?

Yes it is

**Comment by jimykhan** [comment]
@henriquetroiano yes

**Comment by jimykhan** [comment]
what is your flutter sdk version? @henriquetroiano

**Comment by henriquetroiano** [comment]
> what is your flutter sdk version? @henriquetroiano

I'm using 3.0.5

**Comment by henriquetroiano** [comment]
@jimykhan  I'll teach you a trick

**Comment by jimykhan** [comment]
can u share ur main code?

**Comment by jimykhan** [comment]
> @jimykhan I'll teach you a trick

yes please thanks for flutter 3.0.5 also working for me only this method through error await FlutterCallkitIncoming.activeCalls()

**Comment by henriquetroiano** [comment]
> can u share ur main code?

I cannot, it's from my job. But I'll help you find the main issue:

Make an http post request to your server, from `Firebase.onBackgroundMessage`, to make sure you are receiving the push call notification, and send on it's body the message to check.

and before you show the callkit with await `await FlutterCallkitIncoming.showCallkitIncoming(params)`, you will put this code inside a Try/catch.

If any catch errors throws, you'll make a http post request to your server and send the error from `} catch (e) {` 

```
try {
    await FlutterCallkitIncoming.showCallkitIncoming(params);
} catch (e) {
    await Dio().post('/log', {'data': e});
}

```

**Comment by henriquetroiano** [comment]
This is a simple trick to find the issue in release mode

**Comment by jimykhan** [comment]
how u navigate user video calling page once user accept call ?

**Comment by jimykhan** [comment]
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage event) async {
  await Firebase.initializeApp();
  print("background message");
  if (event.notification?.title?.toLowerCase() == "offer".toLowerCase()) {
    // main();
    print(
        'Message title: ${event.notification?.title}, body: ${event.notification?.body}, data: ${event.data}');
    String currentUuid = Uuid().v4();
    // 'callingTime': DateTime.now().toString(),
    Map<String,dynamic> data = event.data;
    data["callingTime"] = DateTime.now().toString();
    showCallkitIncoming(currentUuid,data: data);
  }
}

Future<void> firebaseMessagingBackgroundHandler(RemoteMessage event) async {}

GlobalKey<NavigatorState>? applicationContext = GlobalKey();

Future<void> main() async {
  try {
    WidgetsFlutterBinding.ensureInitialized();
    await Firebase.initializeApp();
    FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);
    initFirebaseRequest();
    // SystemChrome.setEnabledSystemUIOverlays([SystemUiOverlay.top]);
    SystemChrome.setSystemUIOverlayStyle(const SystemUiOverlayStyle(
      statusBarColor: Colors.green,
      statusBarBrightness: Brightness.light,
      statusBarIconBrightness: Brightness.dark,
    ));
    runApp(ProviderScope(child: MyApp()));
  } catch (e) {
    runApp(ProviderScope(child: MyApp()));
  }
}
class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> with WidgetsBindingObserver{
  var _uuid;
  bool shouldNavigateToCallingScreen = true;
  var currentCall;
  var _currentUuid;
  @override
  void initState() {
    super.initState();
    _uuid = Uuid();
    WidgetsBinding.instance.addObserver(this);
    //Check call when open app from terminated
    //  checkAndNavigationCallingPage(fromInit: false);
  }
  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

  getCurrentCall() async {
    try{
      DateTime dateTimeNow = DateTime.now();
      var calls = await FlutterCallkitIncoming.activeCalls();
      await FlutterCallkitIncoming.endAllCalls();

      if (calls is List) {
        try{
          if (calls.isNotEmpty) {
            print('DATA: $calls');
            this._currentUuid = calls[0]['id'];
            String callingTime = calls[calls.length-1]['extra']['callingTime'];
            int diff = dateTimeNow.difference(DateTime.parse(callingTime)).inSeconds;
            if(diff>10){
              return null;
            }
            return calls[0];
          } else {
            this._currentUuid = "";
            return null;
          }
        }
        catch(ex){
          print("$ex");
          return null;
        }
      }
      else{
        return null;
      }

    }catch(ex){
      print("await FlutterCallkitIncoming.activeCalls();");
      print("$ex");
      return null;
    }
  }

  checkAndNavigationCallingPage({bool fromInit = false}) async {
    currentCall = await getCurrentCall();
    if(fromInit){
      return;
    }
    else{
      if(!shouldNavigateToCallingScreen){
        shouldNavigateToCallingScreen = true;
        return;
      }
      if (currentCall != null && shouldNavigateToCallingScreen) {
        shouldNavigateToCallingScreen = false;
        Map<String,String> validMap = Map<String,String>.from(currentCall['extra']);
        // json.decode(json.encode(currentCall['extra'])) as Map<String, String>;
        Navigator.push(applicationContext!.currentContext!, PageTransition(child: VideoCallingScreen(
          offer: validMap,
        ),type: PageTransitionType.fade));
        return;
      }
    }
  }

  @override
  Future<void> didChangeAppLifecycleState(AppLifecycleState state, ) async {
    print(state);
    if (state == AppLifecycleState.resumed) {
      //Check call when open app from background
      checkAndNavigationCallingPage();

    }
  }

  @override
  Widget build(BuildContext context) {
    homeContext = context;
    return GetMaterialApp(
      builder: BotToastInit(),
      navigatorKey: applicationContext,
      debugShowCheckedModeBanner: false,
      title: '2C Health Care',
      navigatorObservers: [BotToastNavigatorObserver()],
      theme: ThemeData(
          primaryColor: Colors.green.shade50,
          primarySwatch: Colors.green,
          appBarTheme: AppBarTheme(
              backgroundColor: Colors.green,
              systemOverlayStyle: SystemUiOverlayStyle.dark)),
      // initialRoute: '/',
      // getPages: [
      //   GetPage(name: '/', page: () => currentCall == null ? Splash() : VideoCallingScreen(fromBackGround: true,)),
      //   GetPage(name: '/calling', page: () => VideoCallingScreen()),
      // ],
      // home: const Splash(),
      // home: currentCall != null ? VideoCallingScreen() :  const Splash(),\
      home: FutureBuilder<dynamic>(
    future: getCurrentCall(),
    initialData: 'Demo Name',
    builder: (
    BuildContext context,
    AsyncSnapshot<dynamic> snapshot,

    ) {
      if(snapshot.connectionState == ConnectionState.waiting){
        return AlertLoader();
      }
      else if(snapshot.connectionState == ConnectionState.done){
        if(snapshot.hasData && snapshot.data != null){
          Map<String,String> validMap = Map<String,String>.from(snapshot.data['extra']);
          return VideoCallingScreen(fromBackGround: true,offer: validMap,);
        }
        else{
          return Splash();
        }
      }
      return Splash();
    },

    ));
  }
}


this is my logic to navigate user to calling screen its work for me in debug but in release this method through error FlutterCallkitIncoming.activeCalls();

**Comment by henriquetroiano** [comment]
@jimykhan if the app is closed, the trick is to use this package: [https://pub.dev/packages/external_app_launcher](url) and launch your own app on FlutterCallkitIncoming on call accept event.
`Please, notice that you need to configure the FlutterCallkitIncoming events before accept the call, to handle it's events, ok?`

**Comment by jimykhan** [comment]
Can u please share navigation logic? @henriquetroiano

**Comment by henriquetroiano** [comment]
@jimykhan I can't, it's not a public code. I'm using context-less navigator, Qlevar Router. Qlevar has observers and middlewares, and when I accept a call in background I save with sharedpreferences "I accept the call in background with ID X" and, when I open the app, I check on first route if I accepted some call in background and redirect to call page

**Comment by jimykhan** [comment]
@henriquetroiano why or using external_app_launcher if u are using flutter SDK 3.0.5 when click on accept button It can open application then why using external launcher

**Comment by henriquetroiano** [comment]
@jimykhan it only works on android 11 or higher. older versions needs external_app_lancher.

**Comment by jimykhan** [comment]
for me its work android version 9 and 10 also

**Comment by santhoshrao519** [comment]
getActiveCalls() throwing exception. Please let know how to solve it
