### ISSUE TITLE
Getting exception when accessing getActiveCalls when the app is in terminated State

### ISSUE THREAD

**Issue by santhoshrao519** [hiennguyen92/flutter_callkit_incoming#190]
I'm getting **Unhandled Exception: PlatformException(error, Missing type parameter., , null)** issue when getting active calls method in my project. Can any one have the solution for it. I'm urgently need of it. Please help

**Comment by santhoshrao519** [comment]
anyone please help, its an urgent fix

**Comment by santhoshrao519** [comment]
Any solution for this?

**Comment by santhoshrao519** [comment]
does any one please let know is it fixable or not? I have been waiting since a month

**Comment by hiennguyen92** [comment]
please update version 1.0.3+1
