### ISSUE TITLE
How to track decline call tap when app is in terminated state

### ISSUE THREAD

**Issue by suriyaKalidoss21** [hiennguyen92/flutter_callkit_incoming#191]
When the app is in the terminated state I want to track the call declined tap button,

For that I have added track event code in _firebaseMessagingBackgroundHandler

`Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async { 
 FlutterCallkitIncoming.onEvent.listen(((event) {
      switch (event!.name) {
        case CallEvent.ACTION_CALL_DECLINE:
          print("Declined");
          break;
      }
    }));
  }}`

By adding this line I can able to track the decline status.

But another problem with this approach is call Accept is not tracked during App background state

When in App background this _firebaseMessagingBackgroundHandler is called again and  FlutterCallkitIncoming.onEvent is overrided

because of that I'm unable to track the previously added Call Accept button.

But in app foreground, navigating to a certain page after Accept button tapped is working fine.

And also without the Calldecline event listen code in _firebaseMessagingBackgroundHandler app is working

**Comment by suriyaKalidoss21** [comment]
Where can I place the FlutterCallkitIncoming.onEvent.listen so that I can listen accept and decline on teriminated state and background state

**Comment by suriyaKalidoss21** [comment]
IM Stuck on this issue,Please help me

**Comment by henriquetroiano** [comment]
i have the solution for you:
use shared_preferences package to set "i clicked on accept".
use external_app_launcher to launch your own app, when it comes the first screen, use initstate to  navigate to the call screen, then, get the call.
use proximity_screen_lock package to handle proximity sensor. on initstate of calling page, set proximity on and let it running. on dispose method, set as inactive. on iOS the callkit does this function.

hope it helps

**Comment by jimykhan** [comment]
Hi guys. Is this package work in release mode issue for in release mode okay in debug

**Comment by 51v4** [comment]
@suriyaKalidoss21 Hi, did you find any solution for this?
