### ISSUE TITLE
Unable to add padding for calling notification

### ISSUE THREAD

**Issue by madhukarNumen** [hiennguyen92/flutter_callkit_incoming#195]
How to add padding around the notification ui? 
For some android devices (eg.: Redmi 10) padding is not there for the calling notification.  

<img width="323" alt="Screenshot 2022-10-27 at 5 36 22 PM" src="https://user-images.githubusercontent.com/103411015/198280552-0c406874-8853-4e93-ac70-ac4ab8d4b624.png">

Please look into it.

**Comment by hiennguyen92** [comment]
please update version 1.0.3+1. adding prop `isCustomSmallExNotification`

**Comment by DavidGomezOv** [comment]
@hiennguyen92 I tried with that parameter and doesn't work, it shows like this
<img width="947" alt="image" src="https://github.com/hiennguyen92/flutter_callkit_incoming/assets/79603643/8b82778b-d27b-4d3c-b087-557bb9f4b849">

What I did was create a custom notification layout with horizontal and vertical padding called "layout_custom_xiaomi_notification" with the same ids like the "layout_custom_small_notification" and the I added this validation in the "CallkitNotificationManager" right in the middle of the if and else clause that validates the Samsung manufacturer

```
else if (Build.MANUFACTURER.contains("Xiaomi",ignoreCase = true) || Build.MANUFACTURER.contains("Redmi",ignoreCase = true)) {
    notificationSmallViews = RemoteViews(context.packageName, R.layout.layout_custom_xiaomi_notification)
    initNotificationViews(notificationSmallViews!!, data)
}
```

<img width="753" alt="image" src="https://github.com/hiennguyen92/flutter_callkit_incoming/assets/79603643/85f53864-cc53-4f30-9b12-1d714348b71d">
