### ISSUE TITLE
If app is not in last opened app in iOS, notification not working in iOS

### ISSUE THREAD

**Issue by sagarstackapp** [hiennguyen92/flutter_callkit_incoming#201]
Flutter sdk - 3.0.5
firebase_messaging: 11.2.6
flutter_callkit_incoming: ^1.0.2+2

After installing when user app notification working for both terminated and background mode. 
But when app is in terminated mode and user open other app then app is not receiving any notification.

Here's the video
[https://drive.google.com/file/d/1fp2hJoCg_yjQ38yn3fkKCuSF3uThZU2h/view?usp=share_link](url)

Kindly check this issue.
Thanks in advance

**Comment by Basemshawwa** [comment]
same issue with me any soluations?
