### ISSUE TITLE
iOS 16: the app won't open (hidden) after accept call from locked screen state

### ISSUE THREAD

**Issue by un-hongly** [hiennguyen92/flutter_callkit_incoming#205]
Hi,
After upgraded to iOS 16 the app won't open if device on lock screen state. Tested and found that the app is running on background but the app's UI interface is not presented to screen.

**Comment by huongrealest** [comment]
same issue

**Comment by federico-amura-kenility** [comment]
same here

**Comment by federico-amura-kenility** [comment]
bump

**Comment by colaTW** [comment]
same here

**Comment by MrPistoul** [comment]
same

**Comment by HensiStackApp** [comment]
same issue
any update?

**Comment by Jazzykhan** [comment]
I am having the same issue. rest is working fine only issue is with the locked screen on iOS. How to solve it any leads? @hiennguyen92
