### ISSUE TITLE
App Crashes and shows unable to load CallKitLogo message for incoming call in IOS

### ISSUE THREAD

**Issue by prenCodePad** [hiennguyen92/flutter_callkit_incoming#206]
App Crashes and shows unable to load CallKitLogo message for incoming call in IOS
<img width="1063" alt="Screen Shot 2022-11-22 at 2 26 57 PM" src="https://user-images.githubusercontent.com/87073699/203270181-de1f086c-a60b-4e0d-891f-6a99749f6c61.png">

**Comment by MingSern** [comment]
@prenCodePad How did you solved this?

**Comment by prenCodePad** [comment]
Hi, I noticed that my token was not being sent properly, I fixed the token
part and it worked fine from then.

Regards,
Praveen Pilli.

**Comment by MingSern** [comment]
@prenCodePad Can you show me how you send it?

**Comment by MingSern** [comment]
@prenCodePad I see, thanks
