### ISSUE TITLE
custom ringtone not working

### ISSUE THREAD

**Issue by faisalmushtaq007** [hiennguyen92/flutter_callkit_incoming#207]
i added a custom ringtone file to raw folder in android section. 
after setting the  'ringtonePath': '/android/app/src/main/res/raw/azan.mp3', its using default phone ringtone
Can u please tell me if i am doing anything wrong

**Comment by hiennguyen92** [comment]
only using name

**Comment by eduardothiesen** [comment]
I am facing the same issue.

ringtone files set in raw folder, ringtone path set as just the name

`AndroidParams(
      isCustomNotification: false,
      isShowLogo: false,
      ringtonePath: 'ringtone_1.mp3',
      backgroundColor: ColorManager.gcfBlue.hexString,
      incomingCallNotificationChannelName: 'Incoming Call',
      missedCallNotificationChannelName: 'Missed Call',
      isShowCallID: false,
      isShowFullLockedScreen: true,
    ),`

![Screenshot 2024-08-05 at 16 31 35](https://github.com/user-attachments/assets/7a3ff448-07ef-4172-a1c9-08401b1ff77d)

Please advise

**Comment by eduardothiesen** [comment]
> I am facing the same issue.
> 
> ringtone files set in raw folder, ringtone path set as just the name
> 
> `AndroidParams( isCustomNotification: false, isShowLogo: false, ringtonePath: 'ringtone_1.mp3', backgroundColor: ColorManager.gcfBlue.hexString, incomingCallNotificationChannelName: 'Incoming Call', missedCallNotificationChannelName: 'Missed Call', isShowCallID: false, isShowFullLockedScreen: true, ),`
> 
> ![Screenshot 2024-08-05 at 16 31 35](https://private-user-images.githubusercontent.com/6534624/355219334-7a3ff448-07ef-4172-a1c9-08401b1ff77d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4ODY2ODksIm5iZiI6MTcyMjg4NjM4OSwicGF0aCI6Ii82NTM0NjI0LzM1NTIxOTMzNC03YTNmZjQ0OC0wN2VmLTQxNzItYTFjOS0wODQwMWIxZmY3N2QucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDVUMTkzMzA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjU4NzM4NjAxOTkxNTZjZDY2ZTk5MmM5YWYyZDg1ZmJkOGJhOWJlOTVmZmZjYTA3M2JlODNkNmE2NjhkMzgzYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.bzSt_mnw8_4v7lCIVeRYSViAZPaWLY4OdLORDrr3COQ)
> 
> Please advise

For anyone experiencing the same problem: the ringtonePath should be set without the extension. For example: "ringtone_1", instead of "ringtone_1.mp3"

**Comment by Steveit96** [comment]
@hiennguyen92  The custom ringtone is not working on the ipad and redmi phone as well. ( So far it's not working on this devices), Is there any way to fix it ? Thanks in advance.
