### ISSUE TITLE
incoming calls after reload phone

### ISSUE THREAD

**Issue by kingstertime** [hiennguyen92/flutter_callkit_incoming#210]
Hello! After reload phone,

`await FlutterCallkitIncoming.showCallkitIncoming(params);` not working for me (android)

Event from firebase handle, but call don't shown.

Method written above is executed and ends. 

`  FlutterCallkitIncoming.onEvent.listen((event) {
    switch (event!.name) {}}` 
don't show any case, but after 1-2 minutes a call comes.

How I can fix this? help, please! Thanks!

**Comment by kingstertime** [comment]
@hiennguyen92 can you please give me some feedback, please?

**Comment by hiennguyen92** [comment]
This may be related to push notifications.
