### ISSUE TITLE
App crashing when receving a 2nd call while app is in background/terminated [iOS]

### ISSUE THREAD

**Issue by abdo400** [hiennguyen92/flutter_callkit_incoming#211]
I am getting this crash on production, I looked it up a bit but it is saying. that I need to register the call to the system? Not sure what that means though. Any idea?

`3   PushKit                       	0x229d90744 -[PKPushRegistry _terminateAppIfThereAreUnhandledVoIPPushes] + 168 (PKPushRegistry.m:349)`

**Comment by ozayr** [comment]
Hi, Im getting the same. when app is terminated firebase notification is delivered without causing phone to ring. when clicking on notification to open app the app shows a crash.
