### ISSUE TITLE
iOS call kit automatically declined the call

### ISSUE THREAD

**Issue by firgia** [hiennguyen92/flutter_callkit_incoming#213]
I'm trying to make 4 calls in sequence

Call 1
1. Push VoIP to show incoming call
2. Show incoming call
3. Answer the call
4. End the call

Call 2
4. Push VoIP to show incoming call
5. Show incoming call
6. The app automatically declines the call

Call 3
7. Push VoIP to show incoming call
8. Show incoming call
9. Answer the call
10. End the call

Call 4
11. Push VoIP to show incoming call
12. Show incoming call
13. The app automatically declines the call

I don't know why the call kit automatically declines the incoming call when I successfully answered a call before.

**Comment by federico-amura-kenility** [comment]
something similar happens when the app is closed and I am on the lock screen.
sometimes the call is closed automatically and sometimes you can answer it without any problems.

**Comment by NaderRaida** [comment]
Same issue

**Comment by FaizanAhmad127** [comment]
any luck on this?
