### ISSUE TITLE
Incoming call screen not removing

### ISSUE THREAD

**Issue by akbarikeyur** [hiennguyen92/flutter_callkit_incoming#215]
When I get an incoming call notification, by clicking on the notification it's showing call on full screen. By clicking on the Decline button, the call ends successfully and ACTION_CALL_DECLINE is also called but the incoming call screen will hide after 10-15 seconds. Please check the video recoding for reference.

Here is my code on decline call

```
endRunningCall() async {
  dynamic lastCall = await FlutterCallkitIncoming.activeCalls();
  if(lastCall != null && (lastCall is List) && lastCall.isNotEmpty) {
    if(lastCall.last["id"] != null) {
      FlutterCallkitIncoming.endCall(lastCall.last["id"]);
    }
  }
  await FlutterCallkitIncoming.endAllCalls();
}
```

https://user-images.githubusercontent.com/9164668/210076809-7b6c8f67-ba39-42bc-b7b5-8d98e2ab3042.mov

**Comment by kevinZartek** [comment]
Same issue. Decline Call not closing the package call alert screen

**Comment by samuel2629** [comment]
Same issue

**Comment by devsadeq** [comment]
any update?

**Comment by maravilhosinga** [comment]
Any update ??

**Comment by hiennguyen92** [comment]
please using 1.0.3+3

**Comment by samuel2629** [comment]
> please using 1.0.3+3

This is the version i'm using, still same issue.

**Comment by works-tabei** [comment]
Shouldn't line 114 of CallkitIncomingActivity.kt be changed to below?
        registerReceiver(
            endedCallkitIncomingBroadcastReceiver,
                IntentFilter("${packageName}.${ACTION_ENDED_CALL_INCOMING}")
        )

*added ${packageName}

**Comment by Basemshawwa** [comment]
> please using 1.0.3+3

same error too
any soluation?

**Comment by CHA7RIK** [comment]
I also experience this issue in 1.0.3+3

**Comment by CHA7R1K** [comment]
I also experience this issue in 1.0.3+3

**Comment by Muhammad-Mohsen** [comment]
> Shouldn't line 114 of CallkitIncomingActivity.kt be changed to below? registerReceiver( endedCallkitIncomingBroadcastReceiver, IntentFilter("${packageName}.${ACTION_ENDED_CALL_INCOMING}") )
> 
> *added ${packageName}

Thanks a lot @works-tabei , I added the package locally and updated the code like you said, and it worked.

**Comment by Sang-Nguyen-Sunny** [comment]
> Shouldn't line 114 of CallkitIncomingActivity.kt be changed to below? registerReceiver( endedCallkitIncomingBroadcastReceiver, IntentFilter("${packageName}.${ACTION_ENDED_CALL_INCOMING}") )
> 
> *added ${packageName}

Thanks you, it worked.

**Comment by Sang-Nguyen-Sunny** [comment]
I have one more question, application mode is in terminal popup incoming incoming but FlutterCallkitIncoming.endCall(id) it doesn't remove that notification.

**Comment by jj22584992** [comment]
@works-tabei  thank you bro, it works!!!

**Comment by hiennguyen92** [comment]
Please update to version 2.0.0 (make sure you check the changelog, because the input structure has been changed)
