### ISSUE TITLE
App crashes when opening notification on real device with 'Settings key: <ringtone2> is not readable' error

### ISSUE THREAD

**Issue by devsadeq** [hiennguyen92/flutter_callkit_incoming#219]
### **There is an error that occurs when attempting to open a notification on a real device. The app crashes and the following error message is displayed:**

D/AndroidRuntime(32405): Shutting down VM
E/AndroidRuntime(32405): FATAL EXCEPTION: main
E/AndroidRuntime(32405): Process: com.example.etana, PID: 32405
E/AndroidRuntime(32405): java.lang.RuntimeException: Unable to start service com.hiennv.flutter_callkit_incoming.CallkitSoundPlayerService@8df4e97 with Intent { cmp=com.ogtechnology.etana/com.hiennv.flutter_callkit_incoming.CallkitSoundPlayerService (has extras) }: java.lang.SecurityException: Settings key: <ringtone2> is not readable. From S+, settings keys annotated with @hide are restricted to system_server and system apps only, unless they are annotated with @Readable.
E/AndroidRuntime(32405): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4724)
E/AndroidRuntime(32405): 	at android.app.ActivityThread.access$2000(ActivityThread.java:256)
E/AndroidRuntime(32405): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2129)
E/AndroidRuntime(32405): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(32405): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(32405): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(32405): 	at android.app.ActivityThread.main(ActivityThread.java:7870)
E/AndroidRuntime(32405): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(32405): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(32405): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
E/AndroidRuntime(32405): Caused by: java.lang.SecurityException: Settings key: <ringtone2> is not readable. From S+, settings keys annotated with @hide are restricted to system_server and system apps only, unless they are annotated with @Readable.
E/AndroidRuntime(32405): 	at android.provider.Settings$NameValueCache.getStringForUser(Settings.java:2906)
E/AndroidRuntime(32405): 	at android.provider.Settings$System.getStringForUser(Settings.java:3518)
E/AndroidRuntime(32405): 	at android.media.RingtoneManager.getActualDefaultRingtoneUriBySlot(RingtoneManager.java:815)
E/AndroidRuntime(32405): 	at android.media.RingtoneManager.getActualDefaultRingtoneUri(RingtoneManager.java:793)
E/AndroidRuntime(32405): 	at com.hiennv.flutter_callkit_incoming.CallkitSoundPlayerService.getRingtoneUri(CallkitSoundPlayerService.kt:145)
E/AndroidRuntime(32405): 	at com.hiennv.flutter_callkit_incoming.CallkitSoundPlayerService.playSound(CallkitSoundPlayerService.kt:73)
E/AndroidRuntime(32405): 	at com.hiennv.flutter_callkit_incoming.CallkitSoundPlayerService.onStartCommand(CallkitSoundPlayerService.kt:28)
E/AndroidRuntime(32405): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4706)
E/AndroidRuntime(32405): 	... 9 more
I/Process (32405): Sending signal. PID: 32405 SIG: 9
Lost connection to device.

- The issue persists even after attempting to set a custom ringtone.
- This issue does not occur on an emulator.

**Comment by hiennguyen92** [comment]
I am not able to reproduce this issue. temporarily, i try catch it(not play ringtone)
