### ISSUE TITLE
Not showing incoming call screen or notification on ios

### ISSUE THREAD

**Issue by mtmfuture** [hiennguyen92/flutter_callkit_incoming#22]
hello first i would thank you about the plugin i had test it on android and it working fine 
but when i had tried testing it on ios one i make  a call 
call start and end immediately with no notification or callscreen

**Comment by mtmfuture** [comment]
> You should test with real device. It will not work with simulator.

thank you for your replay i do really test it on a real device is there any special configuration on xcode?

**Comment by mtmfuture** [comment]
libswiftCore.dylib`_swift_runtime_on_report:
->  0x1857ced7c <+0>: ret
libswiftCore.dylib`_swift_reportToDebugger:
    0x1857ced80 <+0>: b      0x1857ced7c               ; _swift_runtime_on_report
libswiftCore.dylib`_swift_shouldReportFatalErrorsToDebugger:
    0x1857ced84 <+0>: adrp   x8, 335267
    0x1857ced88 <+4>: ldrb   w0, [x8, #0x1e4]
Target 0: (Runner) stopped.
    frame #0: 0x00000001857ced7c libswiftCore.dylib`_swift_runtime_on_report
Unable to load icon AppIcon40x40.
2
flutter_callkit_incoming/SwiftFlutterCallkitIncomingPlugin.swift:128: Fatal error: Unexpectedly found nil while unwrapping an Optional value
* thread #1, queue = 'com.apple.main-thread', stop reason = Fatal error: Unexpectedly found nil while unwrapping an Optional value

**Comment by hiennguyen92** [comment]
Hi @mtmfuture 

I just updated version 1.0.1
please update it

also i have a tutorial on setup Pushkit
https://github.com/hiennguyen92/flutter_callkit_incoming/blob/master/PUSHKIT.md

**Comment by mtmfuture** [comment]
thanks i will test it
