### ISSUE TITLE
How to Accept incoming call from a custom UI?

### ISSUE THREAD

**Issue by shkvoretz** [hiennguyen92/flutter_callkit_incoming#225]
There appears to be no functionality to programmatically accept incoming calls. 
I receive VOIP push notifications on iOS and thus the CallKit is automatically being displayed.
I got custom UI with an 'Accept Call' button and I need to be able to invoke a method to accept the call.

**Comment by InvalidReferenceException** [comment]
How to do this? It does not seem to be possible to accept or reject the call programmatically from dart. If I set call connected the call incoming UI is still shown in iOS and Android.
