### ISSUE TITLE
While Incoming call also Announce with social profile.

### ISSUE THREAD

**Issue by Androidsignal** [hiennguyen92/flutter_callkit_incoming#228]
Incoming call caller announce Call
"testravifan **N2FjZmFkOd..............**"

Its should be only "testravifan"

How To FIX it.

<img width="407" alt="Screenshot 2023-01-18 at 2 52 17 PM" src="https://user-images.githubusercontent.com/30517653/213132807-9af2c766-a366-4f9b-86c2-8043255633fa.png">
er name with social profile.

**Comment by Androidsignal** [comment]
@hiennguyen92

**Comment by hiennguyen92** [comment]
I still haven't found a solution yet****

**Comment by richard-ruah** [comment]
I'm also facing the same issue. Does anyone got a solution to it?
