### ISSUE TITLE
Android: App name is not modified on fullscreen incoming call UI

### ISSUE THREAD

**Issue by MingSern** [hiennguyen92/flutter_callkit_incoming#229]
I think the image below explains itself, I've already set the `appName` to my own app name but it still shows "Callkit", this happens only on android.

<img width="342" alt="Screenshot 2023-01-18 at 8 29 39 PM" src="https://user-images.githubusercontent.com/40648559/213172091-fb0c9206-3f26-4ac7-8c78-20a1826ba241.png">

**Comment by HiroYuan-DAICHIGP** [comment]
Same here

**Comment by hiennguyen92** [comment]
it is 'isShowLogo' which is an image (please read readme description)
