### ISSUE TITLE
Missing propguard-rule for Android -> obfuscated keys in FlutterCallkitIncoming.activeCalls()

### ISSUE THREAD

**Issue by stefanschaller** [hiennguyen92/flutter_callkit_incoming#230]
The following rule needs to be added in the `proguard-rules.pro` to avoid obfuscated keys.

Please add that to the README: 
`-keep class com.hiennv.flutter_callkit_incoming.** { *; }`

**Comment by stefanschaller** [comment]
@hiennguyen92  Are you even care about the issues?

**Comment by hiennguyen92** [comment]
Ok. I will add it to Readme. Thanks

**Comment by stefanschaller** [comment]
There are several more issues, open prs and so on. Do you need help with the contribution?

**Comment by hiennguyen92** [comment]
I added it in the README.md
