### ISSUE TITLE
I want to perform certain logic when user tap on notification when call is missed.

### ISSUE THREAD

**Issue by FaizanAhmad127** [hiennguyen92/flutter_callkit_incoming#235]
When the call is missed we can call a `FlutterCallkitIncoming.showMissCallNotification(params)` method to show a notification with a callback button, the callback button is working perfectly fine because I can detect a tap on it by using call back `Event.ACTION_CALL_CALLBACK` but I want to perform certain logic(maybe open a call history screen) when the app is open via a tap on notification not on call back action. How to do that in both foreground and background/terminated?

**Comment by hiennguyen92** [comment]
because Android doesn't manage history calls. so you have to do it in Flutter code

**Comment by vocsygautam** [comment]
hello i'm also facing this issue from ios side when call is missed by the user,
in android showing notification and call back button, but on ios not show any miss call notification.
