### ISSUE TITLE
Android : endAllCall Api is not removing the callkit when in full screen.

### ISSUE THREAD

**Issue by SagarArora312** [hiennguyen92/flutter_callkit_incoming#236]
If we call the **FlutterCallkitIncoming.endAllCalls()** when the callkit is showing in the full screen. Then just ringing stop but callkit screen is not getting off.

**Comment by avadhkatrodiya98** [comment]
Android : endAllCall Api is not removing the callkit when in full screen

**Comment by avadhkatrodiya98** [comment]
What is the solution?

**Comment by jj22584992** [comment]
Same here, wanna know the solution, Please help

**Comment by hiennguyen92** [comment]
Please update to version 2.0.0 (make sure you check the changelog, because the input structure has been changed)
