### ISSUE TITLE
Can't close screen in coming when app terminate in android.

### ISSUE THREAD

**Issue by phucdth12a** [hiennguyen92/flutter_callkit_incoming#238]
In app android, after close app and lock phone. When i receive phone, it show screen 
![image](https://user-images.githubusercontent.com/18467891/217172561-150fa673-906a-48df-a3e8-6d73c8a10d7d.png)
and when i tapped button Decline this screen can't close.

**Comment by hiennguyen92** [comment]
Please update to version 2.0.0 (make sure you check the changelog, because the input structure has been changed)
