### ISSUE TITLE
iPhone 13-14 notification not coming in kill mode release

### ISSUE THREAD

**Issue by nbpatel94** [hiennguyen92/flutter_callkit_incoming#239]
Hello, @developer 

I have used this package for incoming call notification for android and iOS as well. And get the desired output from this package that's good but i found one issue with the new launched iPhone devices (iPhone 13 & 14).

When i call and send notification to iPhone 13/14 not receiving in kill mode but if i open application after sending notification it working fine and also notification working fine. And i also want to mention that it working fine with iPhone 7, XR as i tested all my cases. and also tested your demo which is on github but it's also have same issue.

Can you please test and give me solutions for this because i already try to find solution for this but can't find it. 

I have also attached drive link of test case there you can check the issue.

[Drive link](https://drive.google.com/file/d/1eSy1RZ2odL_RINlr2eZhhhx48bPfUzfX/view?usp=share_link)

**Comment by AbdurrehmanSubhani** [comment]
Hey, which type of notification are you using to wake your app from terminated state, FCM/APNs or APNs voip?

**Comment by vithanichandresh** [comment]
Having the same error

**Comment by nbpatel94** [comment]
FCM

**Comment by AbdurrehmanSubhani** [comment]
The best and most reliable way of waking an application and displaying a call from terminated/killed state would be to use APNs VoIP notifications for IOS (this package already implements PushKit and CallKit so you would just have to setup your APNs certificates). I myself was stuck trying to wake my application using FCM notifications but it was no use. The code provided for setting up and handling VoIP notifications in the package documentation works fine

**Comment by nbpatel94** [comment]
i have use android callkit in native
