### ISSUE TITLE
Call get declined after tapping on accept on iPhone.

### ISSUE THREAD

**Issue by FaizanAhmad127** [hiennguyen92/flutter_callkit_incoming#240]
@hiennguyen92 Thanks for building this amazing plugin/package. The code is working perfectly fine on android and the app is published to Play Store and has 500+ users and no one complained. But the issue arises only on iPhones. 
Steps:
1. Send data-only notifications through FCM.
2. Show incoming call notifications using `await FlutterCallkitIncoming.showCallkitIncoming(params)`.
3. User tap on accept/tick mark in the notification.
4. Call gets declined.
5. User navigates to the chat screen instead of the call screen as the logic is made when an error happens or a video call doesn't initiate navigate to the chat screen.

The log shows that the `Event.ACTION_CALL_DECLINE` is called before `Event.ACTION_CALL_ACCEPT` which is unlike in android. 

Code:
 
`
   // remove previous calls first if any
    await FlutterCallkitIncoming.endAllCalls();

    final data = remote.data;
    String callerEmail = data['callerEmail'];
    bool isVideoCall = data['isVideoCall'] == "true" ? true : false;
    String token = data['token'];
    String chatRefPath = data['chatRefPath'];
    String channelId = data['channelId'];
    String callId = data['callId'];
    String chatId = data['chatId'];
    bool isGroup = data['isGroup'] == "true" ? true : false;
    String projectID = data['projectID'];
    String type = data['type'];
    String callRefPath = data['callRefPath'];
    final user = await contactService.getUserUsingEmail(email: callerEmail);

    final params = CallKitParams(
      id: Uuid().v4(),
      nameCaller: 'Faizan'
      appName: 'Imposio',
      avatar: 'https://abc.com',
     
      handle: 'Incoming Call',
      type: 0,
      duration: 60000, // this doesn't work either but followed the example anyway.
      textAccept: 'Accept',
      textDecline: 'Decline',
      textMissedCall: 'Missed Call',
      textCallback: 'Call Back',
      headers: <String, dynamic>{},
      android: AndroidParams(
          isCustomNotification: true,
          isShowLogo: false,
          isShowCallback: true,
          isShowMissedCallNotification: true,
          ringtonePath:'system_ringtone_default',
          backgroundColor: '#0955fa',
          actionColor: '#4CAF50',
          missedCallNotificationChannelName: 'Missed Call',
          incomingCallNotificationChannelName: 'Incoming Call'),
      ios: IOSParams(
        iconName: 'Imposio',
        //handleType: user.email,
        handleType: 'Incoming Call',
        supportsVideo: true,
        maximumCallGroups: 2,
        maximumCallsPerCallGroup: 1,
        audioSessionMode: 'default',
        audioSessionActive: true,
        audioSessionPreferredSampleRate: 44100.0,
        audioSessionPreferredIOBufferDuration: 0.005,
        supportsDTMF: true,
        supportsHolding: true,
        supportsGrouping: false,
        supportsUngrouping: false,
        ringtonePath: 'system_ringtone_default',
      ),
    );
   
      await FlutterCallkitIncoming.showCallkitIncoming(params);
`
![IMG_0950](https://user-images.githubusercontent.com/45005402/217563015-6af45904-9e7e-4b95-8e42-c1792c81be81.PNG)
![IMG_0951](https://user-images.githubusercontent.com/45005402/217563057-aa62dfcf-1632-421b-9fd7-fd78d5fd25cf.PNG)

**Comment by VijaiCPrasad** [comment]
This issue is not consistent and happens at times across multiple ios versions and library version. @FaizanAhmad127 where you able to fix it?

**Comment by patrick-billingsley** [comment]
Just ran into this issue. It is consistently happening only on iOS when the app is backgrounded for me.

**Comment by FaizanAhmad127** [comment]
No, I haven't solved it yet.

**Comment by patrick-billingsley** [comment]
I made a discovery today concerning this issue. In my particular case, the issue only happens when the app is backgrounded.

I discovered that I was receiving two calls simultaneously with the same data but different UUIDs. When I accepted, it was declining one and accepting the other which would open my app without the call I was expecting, but open the native callscreen with the other call.

I'm still sussing out what is happening in my specific case but wanted to put this here if this helps with anyone else's issues.

**Comment by Refaat2020** [comment]
@FaizanAhmad127 

could you please tell me how you could handle it on ios?

**Comment by FaizanAhmad127** [comment]
I wasn't able to solve it. Moved on to other features.

**Comment by meet-mi** [comment]
@FaizanAhmad127 @Refaat2020 @patrick-billingsley Have you found the solution for this issue?

**Comment by meet-mi** [comment]
@hiennguyen92 Please look into this issue many folks are stuck here.
