### ISSUE TITLE
calling showCallkitIncoming(Uuid().v4(), title, body); is working fine in debug mode but stops working after releasing app to playstore even thoug other notifications still come

### ISSUE THREAD

**Issue by gmarimo** [hiennguyen92/flutter_callkit_incoming#241]
I am testing my app using real Android Device with Android 1o. The issue is Flutter Callkit works fine in debug mode but stops working after uploading the app to playstore. callkit version flutter_callkit_incoming: ^1.0.3+3

**Comment by mschudt** [comment]
Try building your app without obfuscation. That solved this for me.

**Comment by gmarimo** [comment]
> Try building your app without obfuscation. That solved this for me.

I didn't pass obfuscation in build command, I just passed flutter build appbundle. I never used --obfuscate, i was going to use that later after testing. Does obfuscation passed automatically if I don't pass the flag?

**Comment by vinaykharayat** [comment]
Same issue

**Comment by vinaykharayat** [comment]
> > Try building your app without obfuscation. That solved this for me.
> 
> I didn't pass obfuscation in build command, I just passed flutter build appbundle. I never used --obfuscate, i was going to use that later after testing. Does obfuscation passed automatically if I don't pass the flag?

I think flutter automatically adds this --obfuscate during release

**Comment by vinaykharayat** [comment]
> Try building your app without obfuscation. That solved this for me.

Can you tell me how to do it? Do we need to create progaurd? any additional steps?

**Comment by vinaykharayat** [comment]
Just use 
`@pragma('vm:entry-point')`
to background entry point function.
I was using 
`FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);`

So where I defined `_firebaseMessagingBackgroundHandler`, I added `@pragma('vm:entry-point')` just above it.

**Comment by fbcouch** [comment]
@vinaykharayat is correct - see the updated flutterfire docs here: https://github.com/firebase/flutterfire/blob/master/docs/cloud-messaging/receive.md#apple-platforms-and-android

**Comment by hiennguyen92** [comment]
The following rule needs to be added in the proguard-rules.pro to avoid obfuscated keys.
  -keep class com.hiennv.flutter_callkit_incoming.** { *; }
