### ISSUE TITLE
Unable to set ringtonePath

### ISSUE THREAD

**Issue by vinaykharayat** [hiennguyen92/flutter_callkit_incoming#243]
I have a mp3 file in /android/app/src/main/res/raw/ringtone_default.mp3
```
android: const AndroidParams(
        isCustomNotification: true,
        isShowLogo: true,
        isShowCallback: false,
        isShowMissedCallNotification: false,
        ringtonePath: 'ringtone_default.mp3',
        backgroundColor: '#0955fa',
        backgroundUrl: 'https://i.pravatar.cc/500',
        actionColor: '#4CAF50'),
```
        
I tried putting 'ringtone_default.mp3' 'ringtone_default.pm3' 'android/app/src/main/res/raw/ringtone_default.mp3 in ringtonePath but it is always playing the default system ringtone, if I put 'ringtone_default' then no sound is playing.

**Comment by hiennguyen92** [comment]
please using `ringtone_default` 

please make sure phone is not in do not disturb mode. also make sure to enable play sound (some devices like Xiaomi)

**Comment by gbfarah** [comment]
We are noticing that on some different variants of phones that the above is ignored and the default ringtone as provided flutter_callkit_incoming is still playing .... Even putting the full path to the file doesnt seem to resolve.
Any ideas ?

**Comment by edwinmacalopu** [comment]
@gbfarah It didn't work for me either, I tried the .mp3 extension a lot and now just adding the name works
