### ISSUE TITLE
Stuck when decline from lockscreen in android

### ISSUE THREAD

**Issue by abhiddreambolix** [hiennguyen92/flutter_callkit_incoming#247]
Hey @hiennguyen92 ,

I am not sure why this happens in android only when the device is locked and we get call notification and if i decline it the flutter_callkit android template doesn't go away it takes around 12 to 15 seconds to go aways. 

I/Quality (32717): Skipped: false 1 cost 12.137153 refreshRate 11206292 bit true processName meet.kasper
I/Quality (32717): Skipped: false 1 cost 13.565257 refreshRate 11207098 bit true processName meet.kasper
I/Quality (32717): Skipped: false 1 cost 12.950642 refreshRate 11208111 bit true processName meet.kasper
I/Quality (32717): Skipped: false 1 cost 16.042614 refreshRate 11207728 bit true processName meet.kasper
I/Quality (32717): Skipped: false 1 cost 13.258343 refreshRate 11202388 bit true processName meet.kasper
I/Quality (32717): Skipped: false 1 cost 13.458337 refreshRate 11207369 bit true processName meet.kasper
I/Quality (32717): Skipped: false 1 cost 11.433798 refreshRate 11202302 bit true processName meet.kasper
I/Quality (32717): Skipped: false 1 cost 15.26659 refreshRate 11200786 bit true processName meet.kasper
I/Quality (32717): Skipped: false 2 cost 28.337984 refreshRate 11200152 bit true processName meet.kasper
D/VRI[MainActivity](32717): dispatchAppVisibility visible:true

This came for almost 10 seconds continuously. 

I am attaching the image for ref where i am stuck..... 
![IMG-20230217-WA0000](https://user-images.githubusercontent.com/110274237/219498963-d3ece6b0-07dc-4c0a-a71c-ce5bf2da7d84.jpg)

**Comment by hiennguyen92** [comment]
await FlutterCallkitIncoming.setCallConnected(this._currentUuid);
