### ISSUE TITLE
Call notification UI issue

### ISSUE THREAD

**Issue by Gagandeep1408** [hiennguyen92/flutter_callkit_incoming#253]
some devices have UI issue can you please fix it
![image](https://user-images.githubusercontent.com/59157362/222885721-a3be0dc4-6196-4e4b-a60b-f17ae080e665.png)

**Comment by fukemy** [comment]
this problem is not belong to library

**Comment by Gagandeep1408** [comment]
Can you please tell me if I have to restrict full screen view how I can do that?

**Comment by fukemy** [comment]
hi there. I think its belong to OS problem. because this bubble notification is system notification framework. so please check more real devices for this problem

**Comment by hiennguyen92** [comment]
Please update to version 2.0.0 (make sure you check the changelog, because the input structure has been changed)
maybe you have to use properties ```isCustomSmallExNotification``` on some devices
