### ISSUE TITLE
Incoming ringing not showing when the release apk build and tried

### ISSUE THREAD

**Issue by gig-sudesh** [hiennguyen92/flutter_callkit_incoming#257]
I tried this package and its working perfectly when I build the flutter project and tried. But just in case I tried building an apk and intalled on my phone and tried and the ringing notification didnt work as it worked on the debug mode

**Comment by fbcouch** [comment]
See https://github.com/firebase/flutterfire/blob/master/docs/cloud-messaging/receive.md#apple-platforms-and-android – after flutter 3.3.0, you need to annotate the background message handler with `@pragma('vm:entry-point')`

**Comment by sampaiopedrodev** [comment]
@fbcouch Nice, works for me

**Comment by hiennguyen92** [comment]
I have updated this in the README.md
