### ISSUE TITLE
Android - calling endAllCalls() does not finish the activity CallkitIncomingActivity

### ISSUE THREAD

**Issue by maher-mobi-dev** [hiennguyen92/flutter_callkit_incoming#258]
After investigation I found that the endAllCalls() method can't finish the CallkitIncomingActivity because the action used in clearIncomingNotification() is **getIntentEnded(context: Context) = ${context.packageName}.${ACTION_ENDED_CALL_INCOMING}**,
while the broadcast receiver **EndedCallkitIncomingBroadcastReceiver** is registered with **ACTION_ENDED_CALL_INCOMING** without the **${context.packageName}.**

CAN YOU CHECK PLEASE!

**Comment by VijaiCPrasad** [comment]
@maher-mobi-dev where you able to fix this?

**Comment by VijaiCPrasad** [comment]
This happens even when using `endCall(uuid);` method

**Comment by VijaiCPrasad** [comment]
@hiennguyen92 is there a fix for this yet?

**Comment by DavidGomezOv** [comment]
I was able to remove the popUp notification with this: 
```dart
await FlutterCallkitIncoming.endAllCalls();
Eraser.clearAllAppNotifications();
``` 
this last one is from the library Eraser: [https://pub.dev/packages/eraser](https://pub.dev/packages/eraser)

And for the fullscreen intent of the incoming call screen notification I made a fork of the repo and modify some classes to add a method for finish the activity that shows the incoming call notification.

**Comment by hiennguyen92** [comment]
await FlutterCallkitIncoming.setCallConnected(this._currentUuid);
