### ISSUE TITLE
I can`t accept call when app terminated

### ISSUE THREAD

**Issue by Mfolio** [hiennguyen92/flutter_callkit_incoming#259]
Hi. My app is working on foreground and background. When app is terminated state or not running, I see the incoming call notification but when I tap the accept button the app starts but does not go to the call screen

**Debug consule :** Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: flutter_callkit_incoming_events. Response ID: 21

Event Code :
```
    FlutterCallkitIncoming.onEvent.listen((event) async {
      switch (event!.event) {
        case Event.ACTION_CALL_INCOMING:
          print(event.body['extra']['roomID']);
          break;
        case Event.ACTION_CALL_START:

          // TODO: started an outgoing call
          // TODO: show screen calling in Flutter
          break;
        case Event.ACTION_CALL_ACCEPT:
          navigatorKey.currentState?.push(
            MaterialPageRoute(
              builder: (context) =>
                  CallPage(callID: event.body['extra']['roomID']),
            ),
          );
          break;
        case Event.ACTION_CALL_DECLINE:
          // TODO: declined an incoming call
          break;
        case Event.ACTION_CALL_ENDED:
          // TODO: ended an incoming/outgoing call
          break;
        case Event.ACTION_CALL_TIMEOUT:
          // TODO: missed an incoming call
          break;
        case Event.ACTION_CALL_CALLBACK:
          // TODO: only Android - click action `Call back` from missed call notification
          break;
        case Event.ACTION_CALL_TOGGLE_HOLD:
          // TODO: only iOS
          break;
        case Event.ACTION_CALL_TOGGLE_MUTE:
          // TODO: only iOS
          break;
        case Event.ACTION_CALL_TOGGLE_DMTF:
          // TODO: only iOS
          break;
        case Event.ACTION_CALL_TOGGLE_GROUP:
          // TODO: only iOS
          break;
        case Event.ACTION_CALL_TOGGLE_AUDIO_SESSION:
          // TODO: only iOS
          break;
        case Event.ACTION_DID_UPDATE_DEVICE_PUSH_TOKEN_VOIP:
          // TODO: Handle this case.
          break;
        case Event.ACTION_CALL_CUSTOM:
          // TODO: Handle this case.
          break;
      }
    });
```

**Comment by MingSern** [comment]
Same issue here, it only happens to Android when terminated, 

> @firgia @erolyildiz33 Try
> 
> @pragma('vm:entry-point') Future _messagingBackgroundHandler(RemoteMessage message) async { // your code here }

@booooohdan was suggesting the above solution, it seems that it doesn't work for me because I am using OneSignal, not Firebase.
Everything was working perfectly fine before, but now I'm not sure what happened and it's not working again. 

I am currently using:
```yaml
flutter: 3.7.8
flutter_callkit_incoming: ^1.0.3+3
onesignal_flutter: ^3.5.1
```
So the issue for me is that I use the `showIncomingNotification` function in native android (Kotlin) whenever a "call" notification is received as such:
```kotlin
// in my NotificationServiceExtension
val callkit = FlutterCallkitIncomingPlugin.getInstance()

callkit.showIncomingNotification(data)
```
It works when the app is in foreground/background, but when the app is terminated the call dialog is not shown. So I expected there's something to do with the `context` being null. So I "fix" it by manually creating the intent and passing the context as such:
```kotlin
// the context is from my NotificationServiceExtension
override fun remoteNotificationReceived(context: Context, notificationReceivedEvent: OSNotificationReceivedEvent) {
    ...
    val intent = CallkitIncomingBroadcastReceiver.getIntentIncoming(context, data.toBundle())

    CallkitNotificationManager(context).showIncomingNotification(data.toBundle())

    context.sendBroadcast(intent)

    notificationReceivedEvent.complete(null)
    ...
}
```
The above code will show the call dialog when the app is terminated, however when I tap on `Decline` or `Accept`, the `FlutterCallkitIncoming.onEvent.listen` is not working, it is not receiving any event.

Anyone can help? @hiennguyen92 

I can confirm this code worked previously, but I do not know what changed, Flutter's new version? Would be great to have an update about this.

**Comment by MingSern** [comment]
@Mfolio did you solved this?

**Comment by haily2706** [comment]
@MingSern @hiennguyen92  Have you solved this issue? - please help to guide me through this issue, thank you!

**Comment by mschudt** [comment]
Make sure to call FlutterCallkitIncoming.onEvent.listen(...) inside of the Firebase backgroundMessageHandler (or any other background service your app might use, I guess) in case you're not already doing this. After receiving the ACTION_CALL_ACCEPT event you'll also have to make sure that your app is loaded and already ready for navigation in the same way as when a user clicks on a regular push notification. You could use a Completer in a widget below MaterialApp or try Future.delayed but you have to somehow ensure that your app is built yet.

**Comment by ahmedradwan18** [comment]
Have you solved this issue?

**Comment by Mfolio** [comment]
> Have you solved this issue?

Yes, I solved it. First, tap the accept button of the terminated app. After opening the app, I check the active calls and if there is an active call, I decode it to json and go to the call screen

**Comment by haily2706** [comment]
@Mfolio

Can you show the code here for us to refer @Mfolio? I am stuck with it for a few weeks :-(. thank you for your help

**Comment by ahmedradwan18** [comment]
thanks for your reply, when I tap accept and then check active calls it tells me that no active calls.

**Comment by Mfolio** [comment]
> > > Have you solved this issue?
> > 
> > 
> > Yes, I solved it. First, tap the accept button of the terminated app. After opening the app, I check the active calls and if there is an active call, I decode it to json and go to the call screen
> 
> @Mfolio thanks for sharing, my issue is activeCalls() always return the last call info, How do you define that opening the app is from calling accept?

**Comment by Mfolio** [comment]
> > > Have you solved this issue?
> > 
> > 
> > Yes, I solved it. First, tap the accept button of the terminated app. After opening the app, I check the active calls and if there is an active call, I decode it to json and go to the call screen
> 
> @Mfolio thanks for sharing, my issue is activeCalls() always return the last call info, How do you define that opening the app is from calling accept?

Just endActiveCalls every hangup

**Comment by jj22584992** [comment]
> > > > Have you solved this issue?
> > > 
> > > 
> > > Yes, I solved it. First, tap the accept button of the terminated app. After opening the app, I check the active calls and if there is an active call, I decode it to json and go to the call screen
> > 
> > 
> > @Mfolio thanks for sharing, my issue is activeCalls() always return the last call info, How do you define that opening the app is from calling accept?
> 
> Just endActiveCalls every hangup

Thanks you reply so fast.
Do you mean using endCall(String uuid) this function?, even though I still get last callInfo on Android...

**Comment by Mfolio** [comment]
> > > > > Have you solved this issue?
> > > > 
> > > > 
> > > > Yes, I solved it. First, tap the accept button of the terminated app. After opening the app, I check the active calls and if there is an active call, I decode it to json and go to the call screen
> > > 
> > > 
> > > @Mfolio thanks for sharing, my issue is activeCalls() always return the last call info, How do you define that opening the app is from calling accept?
> > 
> > 
> > Just endActiveCalls every hangup
> 
> Thanks you reply so fast. Do you mean using endCall(String uuid) this function?, even though I still get last callInfo on Android...

Thanks. Just   await FlutterCallkitIncoming.endAllCalls();

**Comment by Mfolio** [comment]
> > > > > Have you solved this issue?
> > > > 
> > > > 
> > > > Yes, I solved it. First, tap the accept button of the terminated app. After opening the app, I check the active calls and if there is an active call, I decode it to json and go to the call screen
> > > 
> > > 
> > > @Mfolio thanks for sharing, my issue is activeCalls() always return the last call info, How do you define that opening the app is from calling accept?
> > 
> > 
> > Just endActiveCalls every hangup
> 
> Thanks you reply so fast. Do you mean using endCall(String uuid) this function?, even though I still get last callInfo on Android...

Thanks. Just   await FlutterCallkitIncoming.endAllCalls();

**Comment by haily2706** [comment]
It works for me @Mfolio. thank you so much. 

I still receive the duplication call on the Android, when I pick up the call in the first 1-2 seconds

**Comment by jj22584992** [comment]
@Mfolio  thanks you, it works by using endAllCalls()
otherwise, would you success decline call when app terminated?
I try many times it never trigger ''post request'' to server that make caller know this call it's done.

**Comment by ankit-deligence3112** [comment]
i am not able listen action in terminated state ,when i click on accept or decline not perform action that i have written in listener ,
please help me out where i am wrong , here is my code 


Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  debugPrint("Handling a background message: ${message.messageId}");

  if (message.data['type'] == 'Call') {
    channelId = message.data['channel_id'];
    NotificationData.showCallkitIncoming(message.data['channel_id'],
        message.data['senderName'], message.data['senderPicture']);
  }
}

String? channelId;

class Tabbar extends StatefulWidget {
  final bool? isPaymentSuccess;
  final String? plan;
  const Tabbar(this.plan, this.isPaymentSuccess, {super.key});
  @override
  TabbarState createState() => TabbarState();
}

//_
class TabbarState extends State<Tabbar> {
  CollectionReference callRef = FirebaseFirestore.instance.collection("calls");
  List<UserModel> users = [];
  int swipedcount = 0;
  // late final Uuid _uuid;
  String? currentUuid;
  String textEvents = "";

  bool isPuchased = false;
  @override
  void initState() {
    super.initState();

// when any background message recieve

    initFirebase();
    listenerEvent(onEvent);

    // NotificationData.getCurrentUser();

    // when user tap on msg fron terminated state
    // FirebaseMessaging.instance.getInitialMessage().then((message) async {
    //   debugPrint("RemoteMessage  ${message?.data}");
    //   if (message != null) {
    //     if (message.data['type'] == 'Call') {
    //       var currentCall = await getCurrentCall();
    //       if (currentCall != null) {}
    //     }
    //   } else {}
    // });

    // Check call when open app from terminated

    if (widget.isPaymentSuccess != null && widget.isPaymentSuccess!) {
      WidgetsBinding.instance.addPostFrameCallback((_) async {
        await Alert(
          context: context,
          type: AlertType.success,
          title: "Confirmation".tr().toString(),
          desc: "You have successfully subscribed to our"
              .tr(args: ['${widget.plan}']).toString(),
          buttons: [
            DialogButton(
              onPressed: () => Navigator.pop(context),
              width: 120,
              child: Text(
                "Ok".tr().toString(),
                style: const TextStyle(color: Colors.white, fontSize: 20),
              ),
            )
          ],
        ).show();
      });
    }
  }

  getCurrentCall() async {
    //check current call from pushkit if possible
    var calls = await FlutterCallkitIncoming.activeCalls();
    if (calls is List) {
      if (calls.isNotEmpty) {
        debugPrint('DATA: $calls');
        currentUuid = calls[0]['id'];
        return calls[0];
      } else {
        currentUuid = "";
        return null;
      }
    }
  }

  Future<void> listenerEvent(Function? callback) async {
    try {
      FlutterCallkitIncoming.onEvent.listen((event) async {
        if (kDebugMode) {
          print('HOME: $event');
        }
        switch (event!.event) {
          case Event.actionCallIncoming:
            break;
          case Event.actionCallStart:
            break;
          case Event.actionCallAccept:
            debugPrint("callinfo from navigation $channelId");
            await callRef.doc(event.body['id']).update({'response': "Pickup"});
            await FlutterRingtonePlayer.stop();
            checkAndNavigationCallingPage(event.body['id']);
            break;
          case Event.actionCallDecline:
            await FlutterCallkitIncoming.endAllCalls();
            await callRef.doc(event.body['id']).update({'response': 'Decline'});

            debugPrint(
                'decilne incoming dart------------------------------------');

            break;
          case Event.actionCallEnded:
            await callRef
                .doc(event.body['id'])
                .update({'response': 'Not-answer'});
            await FlutterCallkitIncoming.endAllCalls();
            break;
          case Event.actionCallTimeout:
            await FlutterCallkitIncoming.endAllCalls();
            await callRef
                .doc(event.body['id'])
                .update({'response': 'Not-answer'});

            debugPrint(
                'decilne incoming dart------------------------------------');
            break;
          case Event.actionCallCallback:
            break;
          case Event.actionCallToggleHold:
            break;
          case Event.actionCallToggleMute:
            break;
          case Event.actionCallToggleDmtf:
            break;
          case Event.actionCallToggleGroup:
            break;
          case Event.actionCallToggleAudioSession:
            break;
          case Event.actionDidUpdateDevicePushTokenVoip:
            break;
          case Event.actionCallCustom:
            break;
        }
        if (callback != null) {
          callback(event.toString());
        }
      });
    } on Exception {
      rethrow;
    }
  }

  checkAndNavigationCallingPage(String channelId) async {
    var currentCall = await getCurrentCall();
    if (currentCall != null) {
      // ignore: use_build_context_synchronously
      Navigator.push(
          context,
          MaterialPageRoute(
              builder: (context) => CallPage(
                    callType: "Audiocall",
                    channelName: channelId,
                    role: ClientRoleType.clientRoleBroadcaster,
                  )));
    }
  }

  initFirebase() async {
    await Firebase.initializeApp();

    FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);
    FirebaseMessaging.onMessage.listen((RemoteMessage message) async {
      debugPrint(
          'Message title: ${message.notification?.title}, body: ${message.notification?.body}, data: ${message.data}');

      NotificationData.showCallkitIncoming(message.data['channel_id'],
          message.data['senderName'], message.data['senderPicture']);
    });
    FirebaseMessaging.instance.getToken().then((token) {
      debugPrint('Device Token FCM: $token');
    });
  }

  // Future<void> didChangeAppLifecycleState(AppLifecycleState state) async {
  //   debugPrint(state.toString());
  //   if (state == AppLifecycleState.resumed) {
  //     //Check call when open app from background
  //     checkAndNavigationCallingPage(channelId!);
  //   }
  // }

  onEvent(event) {
    if (!mounted) return;
    setState(() {
      textEvents += "${event.toString()}\n";
    });
  }

**Comment by anusha-chromosis** [comment]
> > Have you solved this issue?
> 
> Yes, I solved it. First, tap the accept button of the terminated app. After opening the app, I check the active calls and if there is an active call, I decode it to json and go to the call screen

Yes Thank you, this worked for me.I have another issue, on decline of call when app is in terminated state how can we update that call is rejected to the server by hitting an api?
