### ISSUE TITLE
iOS: Every outgoing call become Canceled Call.

### ISSUE THREAD

**Issue by ryojiro** [hiennguyen92/flutter_callkit_incoming#265]
This code is called when outgoing call for CallKit.

https://github.com/hiennguyen92/flutter_callkit_incoming/blob/988e33ceabeb4179982329de0314e53883847b88/ios/Classes/SwiftFlutterCallkitIncomingPlugin.swift#L367-L381

Especially, these lines are called on outgoing call when a callee answered.

https://github.com/hiennguyen92/flutter_callkit_incoming/blob/988e33ceabeb4179982329de0314e53883847b88/ios/Classes/SwiftFlutterCallkitIncomingPlugin.swift#L374-L376

However, I think this API is wrong by Apple Documentation. https://developer.apple.com/documentation/callkit/cxprovider/1930695-reportoutgoingcall

This part fixes at https://github.com/hiennguyen92/flutter_callkit_incoming/pull/264

Also, this method `hasConnected` should be called when callee answered.

https://github.com/hiennguyen92/flutter_callkit_incoming/blob/988e33ceabeb4179982329de0314e53883847b88/ios/Classes/Call.swift#L66-L73

However this method is never called in this time. I tried to fix this part but I don't have enough knowledge for Swift so I couldn't.

**Comment by hiennguyen92** [comment]
Please update to version 2.0.0 (make sure you check the changelog, because the input structure has been changed)
```await FlutterCallkitIncoming.setCallConnected(this._currentUuid);```

**Comment by ryojiro** [comment]
Thank you so much !!
