### ISSUE TITLE
how to remove popup notification call while in terminal

### ISSUE THREAD

**Issue by Sang-Nguyen-Sunny** [hiennguyen92/flutter_callkit_incoming#268]
When I use await FlutterCallkitIncoming.endCall(id)
CallkitIncomingActivity call mode inside app can remove call in activity.
CallkitNotificationManager call mode in the background terminal, the call notification cannot remove.
Hope you can help.

**Comment by meet-mi** [comment]
'await FlutterCallkitIncoming.endCall(id)' method removes the top pop-up, but if we have opened the call screen by tapping on the pop-up, then it is not removing that screen on the 'endcall' method.

Update here if you find something.

**Comment by DavidGomezOv** [comment]
I was able to remove the popUp notification with this: 
```dart
await FlutterCallkitIncoming.endAllCalls();
Eraser.clearAllAppNotifications();
``` 
this last one is from the library Eraser: [https://pub.dev/packages/eraser](https://pub.dev/packages/eraser)
Unfortunately, for now, there is no way to remove the screen of incoming call.

**Comment by hiennguyen92** [comment]
Please update to version 2.0.0 (make sure you check the changelog, because the input structure has been changed)
