### ISSUE TITLE
FlutterCallkitIncoming.endCall is not use when callkit window is full window

### ISSUE THREAD

**Issue by yoer** [hiennguyen92/flutter_callkit_incoming#272]
when click top popup window, and callkit ui switch to full; now call FlutterCallkitIncoming.endCall(uuid) is not end!! the full window still exist after call

**Comment by hiennguyen92** [comment]
Please update to version 2.0.0 (make sure you check the changelog, because the input structure has been changed)

**Comment by yoer** [comment]
Thanks a lot
