### ISSUE TITLE
android call in screen always show 'Callkit' on the top

### ISSUE THREAD

**Issue by golden886** [hiennguyen92/flutter_callkit_incoming#274]
<img width="443" alt="截圖 2023-04-16 下午10 09 28" src="https://user-images.githubusercontent.com/130913943/232318897-817535c4-c0ef-457d-972c-628c07c47164.png">
how to change 'Callkit' string? is this appName ?
i have tried change appName, but still show 'Callkit',
many Thanks!

**Comment by hiennguyen92** [comment]
it is logo, please using prop isShowLogo

**Comment by golden886** [comment]
Thanks for answer!
'isShowLogo' is a CallKitParams ?

**Comment by golden886** [comment]
many many Thanks!!
It is OK! now!
