### ISSUE TITLE
Can't dismiss incoming call UI when caller canceled?

### ISSUE THREAD

**Issue by doanbh** [hiennguyen92/flutter_callkit_incoming#277]
I can't dismiss incoming call UI when Caller canceled.
I use `await FlutterCallkitIncoming.endAllCalls();` but it  doesn't turn off.

**Comment by DavidGomezOv** [comment]
I was able to remove the popUp notification with this: 
```dart
await FlutterCallkitIncoming.endAllCalls();
Eraser.clearAllAppNotifications();
``` 
this last one is from the library Eraser: [https://pub.dev/packages/eraser](https://pub.dev/packages/eraser)
Unfortunately, for now, there is no way to remove the screen of incoming call.

**Comment by hiennguyen92** [comment]
Please update to version 2.0.0 (make sure you check the changelog, because the input structure has been changed)
