### ISSUE TITLE
Voip on iOS

### ISSUE THREAD

**Issue by zionnite** [hiennguyen92/flutter_callkit_incoming#28]
Hello sir, thank you for this package, as a matter of fact, am actually enjoying it

am making use of Socket.io, Nodejs, and Agora.io

I have to question, which are:

1) but sir, I tested the package in my application, am loving it in Android, but it's not working on the ios Simulator, do I need a physical ios Simulator to test it?

2) on the issue of using VoIP on flutter, am really really lost, 
though you drop this [https://medium.com/mindful-engineering/voice-over-internet-protocol-voip-801ee15c3722](url) but am still very confusing on how to proceed

3) I Notice also that on my physical android device, the package did not bring the app from background to foreground

4) How do I remove the callback from the missed call notification, I would love to customize the interface to my taste?

@hiennguyen92, am really grateful for your swift reply and the desire to make this package one of the best

**Comment by zionnite** [comment]
![Screenshot_20220131-004721](https://user-images.githubusercontent.com/10984801/151723032-5cb678ae-6902-4a5d-8b19-df6ff8b7ec88.jpg)


I got this the button are offset from the screen, please how do I correct that

**Comment by hiennguyen92** [comment]
@zionnite 
1. Please using real device for IOS
2. 3. 4. I will check it

**Comment by zionnite** [comment]
Hello Sir, on my question 3 I asked,

 I was wrong, I did not implement the package accurately after checking the documentation and use_guide at pub.dev I was able to make it work properly.


Please ignore the question number 3. It's working fine!!!

**Comment by zionnite** [comment]
Sir, please I really need help on how to use VoIP with iOS along this package.

**Comment by zionnite** [comment]
In addition to my question sir,

5) How do I access parameters values in the  `extra{ 'userId':'ox127'}`

Tried `event!.body` but am getting error

**Comment by zionnite** [comment]
> In addition to my question sir,
> 
> 5. How do I access parameters values in the  `extra{ 'userId':'ox127'}`
> 
> Tried `event!.body` but am getting an error

I was able to resolve it by the following code

 ```
print(event!.body['extra']['userId']);
        print(event.body['extra']['to_user']);
        print(event.body['extra']['from_user']);
```
