### ISSUE TITLE
Permission issue for iOS

### ISSUE THREAD

**Issue by kostricanitechnology** [hiennguyen92/flutter_callkit_incoming#280]
I have this issue when I try to publish to apple store.

Missing Info.plist value. The Info.plist key 'BGTaskSchedulerPermittedIdentifiers' must contain a list of identifiers used to submit and handle tasks when 'UIBackgroundModes' has a value of 'processing'. For more information, refer to the Information Property List Key Reference at https://developer.apple.com/library/ios/documentation/General/Reference/InfoPlistKeyReference/Introduction/Introduction.html. (ID: e2994093-43da-4cc6-94c2-69882d7a29bd)

This is what I have on info.plist

<key>UIBackgroundModes</key>
		<array>
  		<string>processing</string>
  		<string>remote-notification</string>
  		<string>voip</string>
		</array>

**Comment by hiennguyen92** [comment]
Normally if you don't code with native code, you just need to add 
```remote-notification```
```voip```

Without ```progressing```

**Comment by kostricanitechnology** [comment]
I have tried without it but the call screen is not showing like Android

**Comment by PrinceGoyal** [comment]
Even my IOS is not showing calling notification when app is in background.

**Comment by Ahmed2120** [comment]
@PrinceGoyal 
i have the same issue as it not showing calling notification when app is in background.
how you solve it ?

**Comment by kostricanitechnology** [comment]
Hello,

i haven’t resolved and have abandoned this package because they don’t have a support and have a lot of issues.
