### ISSUE TITLE
Your project requires a newer version of the Kotlin Gradle plugin.        

### ISSUE THREAD

**Issue by yoer** [hiennguyen92/flutter_callkit_incoming#288]
e: /Users/yoer/.pub-cache/hosted/pub.dev/flutter_callkit_incoming-2.0.0/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/widgets/RippleRelativeLayout.kt: (129, 27): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
The class is loaded from /Users/yoer/workspace/gradle_user_home/caches/transforms-3/f9bd3816add3c36f02c5ab14e144e020/transformed/jetified-kotlin-stdlib-1.8.10.jar!/kotlin/Unit.class
e: /Users/yoer/.pub-cache/hosted/pub.dev/flutter_callkit_incoming-2.0.0/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/widgets/RippleRelativeLayout.kt: (130, 13): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
The class is loaded from /Users/yoer/workspace/gradle_user_home/caches/transforms-3/f9bd3816add3c36f02c5ab14e144e020/transformed/jetified-kotlin-stdlib-1.8.10.jar!/kotlin/Unit.class
e: /Users/yoer/.pub-cache/hosted/pub.dev/flutter_callkit_incoming-2.0.0/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/widgets/RippleRelativeLayout.kt: (136, 27): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
The class is loaded from /Users/yoer/workspace/gradle_user_home/caches/transforms-3/f9bd3816add3c36f02c5ab14e144e020/transformed/jetified-kotlin-stdlib-1.8.10.jar!/kotlin/Unit.class
e: /Users/yoer/.pub-cache/hosted/pub.dev/flutter_callkit_incoming-2.0.0/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/widgets/RippleRelativeLayout.kt: (137, 13): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
The class is loaded from /Users/yoer/workspace/gradle_user_home/caches/transforms-3/f9bd3816add3c36f02c5ab14e144e020/transformed/jetified-kotlin-stdlib-1.8.10.jar!/kotlin/Unit.class

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_callkit_incoming:compileDebugKotlin'.
> Compilation error. See log for more details

**Comment by yoer** [comment]
when I upgrade to version 2.0.0, the project fails to compile and prompts to upgrade to the latest Gradle. 
Is it possible that flutter_callkit_incoming is using syntax or features that are only supported in the latest Gradle version?

**Comment by hiennguyen92** [comment]
you can try add in android/build.gradle

buildscript {
    ext.kotlin_version = '1.8.0'
...
}

change version to 1.8.0

**Comment by yoer** [comment]
after change version to 1.8.0

`
Launching lib/main.dart on HMA L29 in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* Where:
Script '/Users/yoer/workspace/sources/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 950

* What went wrong:
A problem occurred evaluating root project 'android'.
> A problem occurred configuring project ':app'.
   > Could not create task ':app:copyFlutterAssetsDebug'.
      > Could not create task ':app:mergeDebugAssets'.
         > Cannot use @TaskAction annotation on method IncrementalTask.taskAction$gradle() because interface org.gradle.api.tasks.incremental.IncrementalTaskInputs is not a valid parameter to an action method.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 58s
Exception: Gradle task assembleDebug failed with exit code 1
`

**Comment by hiennguyen92** [comment]
I think you need to upgrade Gradle version

android/build.gradle
`classpath 'com.android.tools.build:gradle:7.1.2'`

android/gradle/wrapper/gradle-wrapper.properties
`distributionUrl=https\://services.gradle.org/distributions/gradle-7.4-bin.zip`

**Comment by yoer** [comment]
``` termial
A problem occurred configuring project ':sqflite'.
> Could not resolve all files for configuration ':sqflite:classpath'.
   > Could not resolve com.android.tools.build:gradle:7.4.2.
     Required by:
         project :sqflite
      > No matching variant of com.android.tools.build:gradle:7.4.2 was found. The consumer was configured to find a runtime of a library compatible with Java 8, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.gradle.plugin.api-version' with value '7.4' but:
          - Variant 'apiElements' capability com.android.tools.build:gradle:7.4.2 declares a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares an API of a component compatible with Java 11 and the consumer needed a runtime of a component compatible with Java 8
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '7.4')
          - Variant 'javadocElements' capability com.android.tools.build:gradle:7.4.2 declares a runtime of a component, and its dependencies declared externally:
              - Incompatible because this component declares documentation and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java version (required compatibility with Java 8)
                  - Doesn't say anything about its elements (required them packaged as a jar)
                  - Doesn't say anything about org.gradle.plugin.api-version (required '7.4')
          - Variant 'runtimeElements' capability com.android.tools.build:gradle:7.4.2 declares a runtime of a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component compatible with Java 11 and the consumer needed a component compatible with Java 8
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '7.4')
          - Variant 'sourcesElements' capability com.android.tools.build:gradle:7.4.2 declares a runtime of a component, and its dependencies declared externally:
              - Incompatible because this component declares documentation and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java version (required compatibility with Java 8)
                  - Doesn't say anything about its elements (required them packaged as a jar)
                  - Doesn't say anything about org.gradle.plugin.api-version (required '7.4')
> Failed to notify project evaluation listener.
   > Could not get unknown property 'android' for project ':sqflite' of type org.gradle.api.Project.
   > Could not get unknown property 'android' for project ':sqflite' of type org.gradle.api.Project.
```

**Comment by yoer** [comment]
``` terminal
[✓] Flutter (Channel stable, 3.7.12, on macOS 12.2.1 21D62 darwin-arm64 (Rosetta), locale zh-Hans-CN)
    • Flutter version 3.7.12 on channel stable at /Users/yoer/workspace/sources/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (6 weeks ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/yoer/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • ANDROID_HOME = /Users/yoer/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0
```

**Comment by yoer** [comment]
This problem has been blocking my project for a while. 
Can you please tell me the specific reasons that caused it? 
It occurs when upgrading to version 2.0. 
Additionally, my project does not use sqlite.

**Comment by hiennguyen92** [comment]
you can set Android Studio build with java8. Setting>Build Tool>Gradle> set java8 instead of 11

**Comment by yoer** [comment]
sloved, 

project/android/gradle/wrapper/gradle-wrapper.properties:
``` terminal
distributionUrl=https\://services.gradle.org/distributions/gradle-7.5-all.zip
```

project/android/build.gradle:
``` gradle
buildscript {
    // kotlin version should be 1.8.0
    ext.kotlin_version = '1.8.0'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"

        // support notification
        classpath 'com.google.gms:google-services:4.3.10'
    }
}
```
