### ISSUE TITLE
on android 12 error occur 

### ISSUE THREAD

**Issue by sadaqatdev** [hiennguyen92/flutter_callkit_incoming#29]
Thank you for your great work.

PlatformException (PlatformException(error, com.wealways.alwayschat: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles., , null))

**Comment by sadaqatkarimi** [comment]
static Future showCallkitIncoming(dynamic params) async {
    await _channel.invokeMethod("showCallkitIncoming", params);
  }.  error occur while call this method

**Comment by sadaqatkarimi** [comment]
this error cannot resolve in latest version of app

**Comment by hiennguyen92** [comment]
Hi @sadaqatdev 

I just deployed version 1.0.1
please update it
