### ISSUE TITLE
Q: How do you configure the VOIP.pem to the app (on Xcode)

### ISSUE THREAD

**Issue by lironzemingo** [hiennguyen92/flutter_callkit_incoming#293]
I want to configure the VoIP push, so I can get call on iOS when the app is terminated. followed this example here:  
https://github.com/hiennguyen92/flutter_callkit_incoming/blob/master/example/ios/Runner/AppDelegate.swift

but I don't understand what I'm supposed to do with the VOIP.pem certificate that I have.
thank you

**Comment by hiennguyen92** [comment]
Please check step by step here 
https://github.com/hiennguyen92/flutter_callkit_incoming/blob/master/PUSHKIT.md

The .pem file is used to send voIP from your server to your device (it will be used in the backend)
