### ISSUE TITLE
The button cannot be pressed depending on the screen size.【Android】

### ISSUE THREAD

**Issue by Takatoshi-ish** [hiennguyen92/flutter_callkit_incoming#294]
I cannot press the answer button on the Android incoming call screen depending on the screen size.
I would like to modify the screen so that the button can be pressed even on a landscape screen.
Is it possible to improve it?

Reference image.
![callkit_terminal](https://github.com/hiennguyen92/flutter_callkit_incoming/assets/51984676/17a57934-d4e8-415a-8cde-1eb285c88ddd)

**Comment by hiennguyen92** [comment]
Currently only support portrait. I will support landscape in the next version

**Comment by Takatoshi-ish** [comment]
@hiennguyen92 
When will the next version be released?

**Comment by hiennguyen92** [comment]
@Takatoshi-ish I have a question.
how can you switch the screen to landscape? I already set it to hard it's portrait already.

**Comment by hiennguyen92** [comment]
you can try with version 2.0.0+1, thanks
