### ISSUE TITLE
Call Rejection Event from terminated State

### ISSUE THREAD

**Issue by TouseefAQ** [hiennguyen92/flutter_callkit_incoming#30]
Is there is any event that can be fire when user rejects the call from terminated state?

**Comment by hiennguyen92** [comment]
Hi @TouseefAQ 

I just updated version 1.0.1
please update it

also i have a tutorial on setup Pushkit
https://github.com/hiennguyen92/flutter_callkit_incoming/blob/master/PUSHKIT.md

**Comment by TouseefAQ** [comment]
Thanks
