### ISSUE TITLE
Can you add a variable like EXTRA_CALLKIT_IS_SHOW_LOGO to control caller ID hide or show?

### ISSUE THREAD

**Issue by yoer** [hiennguyen92/flutter_callkit_incoming#303]
I need to hide the caller ID on the incoming call view. 

Can you add a variable like EXTRA_CALLKIT_IS_SHOW_LOGO to control it?

**Comment by hiennguyen92** [comment]
it looks like it is `isShowLogo` inside Android.

**Comment by hiennguyen92** [comment]
Sorry it was delayed, it was updated in [2.0.1+2](https://pub.dev/packages/flutter_callkit_incoming/versions/2.0.1+2)

**Comment by hiennguyen92** [comment]
@yoer Please update to the latest version. Some users are using the 'flutter_callkit_incoming_yoer' package, and I cannot check the issues if they create them under 'flutter_callkit_incoming'.

**Comment by yoer** [comment]
ok

**Comment by yoer** [comment]
But why would someone reference this project? It's a temp project for private bug fix 😓

**Comment by hiennguyen92** [comment]
I'm not sure about that. you can find it here: https://github.com/hiennguyen92/flutter_callkit_incoming/issues?q=flutter_callkit_incoming_yoer
maybe they have prebuilt
https://pub.dev/packages/zego_uikit_prebuilt_call.

If you are a ZEGO developer, please update as soon as possible to make the library as stable as possible.
