### ISSUE TITLE
Android is Working but iOS i'm getting this error

### ISSUE THREAD

**Issue by maravilhosinga** [hiennguyen92/flutter_callkit_incoming#309]
* thread #1, queue = 'com.apple.main-thread', stop reason = Fatal error: Unexpectedly found nil while unwrapping an Optional value
    frame #0: 0x00000001bfbcca3c libswiftCore.dylib`_swift_runtime_on_report

**Comment by hiennguyen92** [comment]
please make sure id always is UUID format.

**Comment by maravilhosinga** [comment]
Using UUID format as mentioned by @hiennguyen92  is working.
