### ISSUE TITLE
Error in IOS 13 pro mini 

### ISSUE THREAD

**Issue by sadaqatdev** [hiennguyen92/flutter_callkit_incoming#31]
after picking call from app terminated state , Call Failed Screen display from callKit ios , if we click on callback button of callKit ios then app is open,  in other words app is not open when we accept call in app terminated state, 

Thank you for your great work.

**Comment by hiennguyen92** [comment]
Hi @sadaqatdev 

I just updated version 1.0.1
please update it

also i have a tutorial on setup Pushkit
https://github.com/hiennguyen92/flutter_callkit_incoming/blob/master/PUSHKIT.md

**Comment by sadaqatdev** [comment]
ok, thank you

**Comment by brijeshbodariya** [comment]
@sadaqatdev 
did you fix this?

**Comment by haninhn** [comment]
did you find a solution @sadaqatdev
