### ISSUE TITLE
Android shown duplicate app when accept call from lock screen.

### ISSUE THREAD

**Issue by posawatji** [hiennguyen92/flutter_callkit_incoming#313]
version: flutter_callkit_incoming: 2.0.0+1
please help @hiennguyen92 

I'm not found this case when I use this package.
https://github.com/doneservices/flutter_callkeep

![2566-06-21 18 00 27](https://github.com/hiennguyen92/flutter_callkit_incoming/assets/39872173/26789a9d-67c4-4777-86a6-de3f4e028a76)

![2566-06-21 18 00 30](https://github.com/hiennguyen92/flutter_callkit_incoming/assets/39872173/20a79d0c-9c9c-4e7f-a871-7c9263644867)

**Comment by DaveBubenik** [comment]
I was able to correct this by changing the android launchMode in my application to:
`android:launchMode="singleTask"`

I noticed callkeep sets that mode in it's plugin, maybe callkit_incoming needs to do the same?

**Comment by huantd0111** [comment]
> I was able to correct this by changing the android launchMode in my application to: `android:launchMode="singleTask"`
> 
> I noticed callkeep sets that mode in it's plugin, maybe callkit_incoming needs to do the same?

Thank you. This works fine in my case.

**Comment by posawatji** [comment]
> I was able to correct this by changing the android launchMode in my application to: `android:launchMode="singleTask"`
> 
> I noticed callkeep sets that mode in it's plugin, maybe callkit_incoming needs to do the same?

it's work, Thanks you🤩.
