### ISSUE TITLE
iOS app crashes on receiving a VoIP push

### ISSUE THREAD

**Issue by PrathameshTM** [hiennguyen92/flutter_callkit_incoming#315]
I am trying to get things working with iOS. I am not using FCM at all. Your example uses FCM so I have done the implementation based on my understanding. Help me verify the same as well.
1. Made changes to the AppDelegate.swift file as mentioned. Simple copy paste of code.
2. Added the capabilities: Background modes (VoIP, Background fetch, Remote notifications, Background processing) & Push notifications.
3. Imported flutter_callkit_incoming and implemented the following in my code. Just the below two things:
```
    FlutterCallkitIncoming.getDevicePushTokenVoIP().then(
      (voipToken) {
        debugPrint('VoIP token: $voipToken');
        if (voipToken != null || voipToken != '') {
          registerToken(voipToken);
        }
      },
    );

    FlutterCallkitIncoming.onEvent.listen(
      (event) {
        debugPrint('FlutterCallkitIncoming.onEvent: $event');
      },
      cancelOnError: false,
      onDone: () {
        debugPrint('FlutterCallkitIncoming.onEvent: done');
      },
      onError: (e) {
        debugPrint('FlutterCallkitIncoming.onEvent:error ${e.toString()}');
      },
    );
```

Coming to the server side, I have a setup to trigger notificaitons to APNs servers.
When I trigger a VoIP notification to the VoIP token from my server, it is a success:
```
{
  "sent": [
    {
      "device": "648a4b4d9511055a8c7b2605ead4aa71a9bcd5b07511220e4a869d4bf87c9ac6"
    }
  ],
  "failed": []
}
```

However, when it arrives at the device end, I see the following error with a crash.
The `didReceiveIncomingPushWith` is present in AppDelegate.swift file.
```
didReceiveIncomingPushWith
[connection] nw_read_request_report [C6] Receive failed with error "Software caused connection abort"
[connection] nw_read_request_report [C10] Receive failed with error "Software caused connection abort"
[connection] nw_read_request_report [C4] Receive failed with error "Software caused connection abort"
[connection] nw_read_request_report [C8] Receive failed with error "Software caused connection abort"
Unable to load icon CallKitLogo.
warning: flutter_callkit_incoming was compiled with optimization - stepping may behave oddly; variables may not be available.
* thread #1, queue = 'com.apple.main-thread', stop reason = Swift runtime failure: Unexpectedly found nil while unwrapping an Optional value
    frame #1: 0x000000010472cbc8 flutter_callkit_incoming`SwiftFlutterCallkitIncomingPlugin.showCallkitIncoming(data=0x000000028292d3b0, fromPushKit=<unavailable>, self=0x0000000283539860) at SwiftFlutterCallkitIncomingPlugin.swift:215:62 [opt]
   212          let uuid = UUID(uuidString: data.uuid)
   213          
   214          configurAudioSession()
-> 215          self.sharedProvider?.reportNewIncomingCall(with: uuid!, update: callUpdate) { error in
                                                                     ^
   216              if(error == nil) {
   217                  self.configurAudioSession()
   218                  let call = Call(uuid: uuid!, data: data)
Target 0: (Runner) stopped.
```

**Comment by hiennguyen92** [comment]
please make sure the id you pass in the input is uuid format xxxx-xxxx.... not string or int.

**Comment by PrathameshTM** [comment]
Which field of the push notification payload is passed in as uuid?

**Comment by hiennguyen92** [comment]
That depends on your logic. 
just make sure the id here is uuid format xxxx-xxxx.... 
https://github.com/hiennguyen92/flutter_callkit_incoming/blob/16986c293eb56b937c8452bc49dcf93fc8e1aa40/example/ios/Runner/AppDelegate.swift#L70

You can set the hardcode here or pass it to the notification payload.

**Comment by PrathameshTM** [comment]
I was actually going to paste the same thing. Thanks. I will try this out.

**Comment by PrathameshTM** [comment]
Actually you have added this line and it is using UUID() package.

```
let data = flutter_callkit_incoming.Data(id: UUID().uuidString, nameCaller: nameCaller, handle: handle, type: isVideo ? 1 : 0)
```

I didn't change this. It should always be a valid UUID right?

**Comment by PrathameshTM** [comment]
My bad. Wait I got it.

**Comment by PrathameshTM** [comment]
Thanks. I changed the id to a valid UUID and things are working.

**Comment by diasmalibekov** [comment]
> Thanks. I changed the id to a valid UUID and things are working.



> Thanks. I changed the id to a valid UUID and things are working.

what was the problem could you tell me please?
