### ISSUE TITLE
iOS: How to deal with call ended from caller's end

### ISSUE THREAD

**Issue by PrathameshTM** [hiennguyen92/flutter_callkit_incoming#316]
So, I send a VoIP push when a call is made that is straight-forward.
When a call is cancelled again from the caller's end, I again send a silent VoIP push notification.
I want to dismiss the callkit screen and handle the call cancelled event in my app.

So, in the AppDelegate.swift file, do we have something like:
`SwiftFlutterCallkitIncomingPlugin.sharedInstance?.showCallkitMissed(data, fromPushKit: true)`

**Comment by PrathameshTM** [comment]
So basically
A calls B
B sees CallKit screen
A cancels call
The CallKit screen on B's end should stop ringing and get dismissed.

**Comment by PrathameshTM** [comment]
Should I write custom logic where I conditionally call:
THIS
`SwiftFlutterCallkitIncomingPlugin.sharedInstance?.showCallkitMissed(data, fromPushKit: true)`
OR
`SwiftFlutterCallkitIncomingPlugin.sharedInstance?.endCall(data, fromPushKit: true)`

based on my payload?

**Comment by nepali-programmer** [comment]
Have you found any solution? I am also working on similar issue. I want to stop ringing and get dismissed in foreground, background and terminated state.

**Comment by PrathameshTM** [comment]
@nepali-programmer I verified this and `SwiftFlutterCallkitIncomingPlugin.sharedInstance?.endCall(data)` is something that works. The id has to be the same.
