### ISSUE TITLE
How to display active call screen?

### ISSUE THREAD

**Issue by vvitto** [hiennguyen92/flutter_callkit_incoming#317]
Could you provide me some instructions about how to display active call screen after accepting incoming call? Currently I'm listening for `actionCallAccept` event and invoke `FlutterCallkitIncoming.setCallConnected(event.body['id']);` but I'm wondering how to show active call screen like this:
![image](https://github.com/hiennguyen92/flutter_callkit_incoming/assets/26697512/83402f2d-0363-4159-919a-0c38c3e237ad)

I'm testing it in android emulator and after `setCallConnected` nothing happens and incoming call notification just disappears.

**Comment by hiennguyen92** [comment]
the library will not have this screen. you need to develop this screen in Flutter (it is the calling page screen in Example)

**Comment by vvitto** [comment]
@hiennguyen92 clear, thanks
