### ISSUE TITLE
Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent

### ISSUE THREAD

**Issue by TouseefAQ** [hiennguyen92/flutter_callkit_incoming#32]
When running on Android 12
`E/flutter ( 7301): Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles., , null)
E/flutter ( 7301): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
E/flutter ( 7301): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
E/flutter ( 7301): <asynchronous suspension>
E/flutter ( 7301): #2      FlutterCallkitIncoming.showCallkitIncoming (package:flutter_callkit_incoming/flutter_callkit_incoming.dart:39:5)
E/flutter ( 7301): <asynchronous suspension>
E/flutter ( 7301): #3      FirebaseMessagingService.notificationOnMessageHandler.<anonymous closure> (package:vinciio/core/services/firebase_messaging_service/firebase_messaging_service.dart:113:7)
E/flutter ( 7301): <asynchronous suspension>`

**Comment by hiennguyen92** [comment]
Hi @TouseefAQ 

I just deployed version 1.0.1.
please update it

**Comment by TouseefAQ** [comment]
Resolved , Thank you very much. I really appreciate.
