### ISSUE TITLE
Cannot pass duration in iOS call Data

### ISSUE THREAD

**Issue by PrathameshTM** [hiennguyen92/flutter_callkit_incoming#321]
The following works:
`let data = flutter_callkit_incoming.Data(id: "488501f2-45f1-4b20-8aa3-4f2313405622", nameCaller: nameCaller, handle: handle, type: 0)`

But if I do this, I get an error:
`let data = flutter_callkit_incoming.Data(id: "488501f2-45f1-4b20-8aa3-4f2313405622", nameCaller: nameCaller, handle: handle, type: 0, duration: 45000)`

Error:
```
Could not build the precompiled application for the device.
Swift Compiler Error (Xcode): Extra argument 'duration' in call
/Users/prathameshtm/Development/dart/flutter-pn-sample-v3/ios/Runner/AppDelegate.swift:92:180
```

Is it not possible to change the duration in AppDeletegate.swift file? Is there some other way to do it?

**Comment by hiennguyen92** [comment]
please check this Example:
https://github.com/hiennguyen92/flutter_callkit_incoming/blob/16986c293eb56b937c8452bc49dcf93fc8e1aa40/example/ios/Runner/AppDelegate.swift#L40

it will be:
`data. duration = 45000`

**Comment by PrathameshTM** [comment]
I am getting this error if I do `data.duration = 45000`

```
Could not build the precompiled application for the device.
Swift Compiler Error (Xcode): Cannot find 'duration' in scope
/Users/prathameshtm/Development/dart/flutter-pn-sample-v3/ios/Runner/AppDelegate.swift:88:88
```

**Comment by PrathameshTM** [comment]
Sorry, my bad.
data.duration = 45000 works for me.

Thank you.
