### ISSUE TITLE
[iOS] Call not working after first time in iOS. Caller name is gibberish.

### ISSUE THREAD

**Issue by joshisijan** [hiennguyen92/flutter_callkit_incoming#323]
[IOS] I receive call on first time and every thing is functional. After first time every time you get this screen.

here is my code:

```
import PushKit
import UIKit
import Flutter
import flutter_local_notifications
import flutter_callkit_incoming


@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate, PKPushRegistryDelegate {  
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {

    GeneratedPluginRegistrant.register(with: self)

    // Flutter local notification
    FlutterLocalNotificationsPlugin.setPluginRegistrantCallback { (registry) in
        GeneratedPluginRegistrant.register(with: registry)
    }
    // Show foreground notification
    if #available(iOS 10.0, *) {
      UNUserNotificationCenter.current().delegate = self as UNUserNotificationCenterDelegate
    }     

    // Setup VOIP
    let mainQueue = DispatchQueue.main
    let voipRegistry: PKPushRegistry = PKPushRegistry(queue: mainQueue)
    voipRegistry.delegate = self
    voipRegistry.desiredPushTypes = [PKPushType.voIP]    
        
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)    
  }

  // Call back from Recent history
    override func application(_ application: UIApplication,
                              continue userActivity: NSUserActivity,
                              restorationHandler: @escaping ([UIUserActivityRestoring]?) -> Void) -> Bool {
        
        guard let handleObj = userActivity.handle else {
            return false
        }
        
        guard let isVideo = userActivity.isVideo else {
            return false
        }
        let objData = handleObj.getDecryptHandle()
        let nameCaller = objData["nameCaller"] as? String ?? ""
        let handle = objData["handle"] as? String ?? ""
        let data = flutter_callkit_incoming.Data(id: UUID().uuidString, nameCaller: nameCaller, handle: handle, type: isVideo ? 1 : 0)
        data.extra = ["platform": "ios", "duration": 60000]

        return super.application(application, continue: userActivity, restorationHandler: restorationHandler)
    }
    
    // Handle updated push credentials
    func pushRegistry(_ registry: PKPushRegistry, didUpdate credentials: PKPushCredentials, for type: PKPushType) {
        print(credentials.token)
        let deviceToken = credentials.token.map { String(format: "%02x", $0) }.joined()
        print(deviceToken)
        //Save deviceToken to your server
        SwiftFlutterCallkitIncomingPlugin.sharedInstance?.setDevicePushTokenVoIP(deviceToken)
    }
    
    func pushRegistry(_ registry: PKPushRegistry, didInvalidatePushTokenFor type: PKPushType) {
        print("didInvalidatePushTokenFor")
        SwiftFlutterCallkitIncomingPlugin.sharedInstance?.setDevicePushTokenVoIP("")
    }
    
    // Handle incoming pushes
    func pushRegistry(_ registry: PKPushRegistry, didReceiveIncomingPushWith payload: PKPushPayload, for type: PKPushType, completion: @escaping () -> Void) {
        print("didReceiveIncomingPushWith")
        guard type == .voIP else { return }

        // guard let apsPayload = payload.dictionaryPayload["aps"] as? [String: Any] else { return }
        
        // let id = payload.dictionaryPayload["id"] as? String ?? ""
        let nameCaller = payload.dictionaryPayload["nameCaller"] as? String ?? ""
        let handle = payload.dictionaryPayload["handle"] as? String ?? ""
        let isVideo = payload.dictionaryPayload["isVideo"] as? Bool ?? false
        
        let data = flutter_callkit_incoming.Data(id: UUID().uuidString, nameCaller: nameCaller, handle: handle, type: isVideo ? 1 : 0)
        data.extra = ["platform": "ios", "duration": 60000]                

        SwiftFlutterCallkitIncomingPlugin.sharedInstance?.showCallkitIncoming(data, fromPushKit: true)
        
        // //Make sure call completion()
        DispatchQueue.main.asyncAfter(deadline: .now() + 1.5) {
           completion()
        }
    }
}
```

**Comment by RochakShrestha19** [comment]
I've been also facing the same issue. My AppDelegate.swift is also the same. Please help me @hiennguyen92

**Comment by hiennguyen92** [comment]
can you give me video record screen of the whole process?

**Comment by joshisijan** [comment]
https://github.com/hiennguyen92/flutter_callkit_incoming/assets/33340684/03f81113-bb81-42e2-846c-bb3030258bfa

Watch whole video.
- When first call is received you can respond to it. It is a valid call. [Accept & Decline]
- From second call you get gibberish value for caller name and you can not respond to call.

My AppDelegate.swift is given above.

@hiennguyen92 @RochakShrestha19

**Comment by hiennguyen92** [comment]
maybe you use the same uuid for the calls. you can change them for each call and let me know the result. thank

**Comment by joshisijan** [comment]
Doesn't UUID().uuidString gives unique UUID every time it is called for every incoming push received? @hiennguyen92 
<img width="760" alt="Screenshot 2023-06-28 at 11 10 18 AM" src="https://github.com/hiennguyen92/flutter_callkit_incoming/assets/33340684/999f4f9e-55b8-453c-9b1e-ec796dc1e5bf">

**Comment by hiennguyen92** [comment]
seems strange. It is show the encryption handle

**Comment by joshisijan** [comment]
When I put ```GeneratedPluginRegistrant.register(with: self)``` in front of VOIP setup in AppDelegate.swift like in upper code this issue occurs. But if I place ```GeneratedPluginRegistrant.register(with: self)``` after VOIP setup like 
```
   // Setup VOIP
    let mainQueue = DispatchQueue.main
    let voipRegistry: PKPushRegistry = PKPushRegistry(queue: mainQueue)
    voipRegistry.delegate = self
    voipRegistry.desiredPushTypes = [PKPushType.voIP] 

   GeneratedPluginRegistrant.register(with: self)
```

then every thing work without any issue for Foreground and Background state. But for terminated State i have following result:
 - for first call Same gibberish is shown
 - but after first call from second call everything works

If you find any solution it would be great.

**Comment by RochakShrestha19** [comment]
> When I put `GeneratedPluginRegistrant.register(with: self)` in front of VOIP setup in AppDelegate.swift like in upper code this issue occurs. But if I place `GeneratedPluginRegistrant.register(with: self)` after VOIP setup like
> 
> ```
>    // Setup VOIP
>     let mainQueue = DispatchQueue.main
>     let voipRegistry: PKPushRegistry = PKPushRegistry(queue: mainQueue)
>     voipRegistry.delegate = self
>     voipRegistry.desiredPushTypes = [PKPushType.voIP] 
> 
>    GeneratedPluginRegistrant.register(with: self)
> ```
> 
> then every thing work without any issue for Foreground and Background state. But for terminated State i have following result:
> 
> * for first call Same gibberish is shown
> * but after first call from second call everything works
> 
> If you find any solution it would be great.
> 
> @hiennguyen92

It has also been the exact same case for me. Did you find the solution @joshisijan?
@hiennguyen92, a solution would be appreciated.

**Comment by nepali-programmer** [comment]
I have not found any solution @RochakShrestha19.

wbu? @hiennguyen92

**Comment by joshisijan** [comment]
I haven't found any solution @RochakShrestha19.

wbu @hiennguyen92 ?

**Comment by joshisijan** [comment]
Issue is solved. There was two package both using CallKit. Removed PushKit implementation from one of the package to solve the problem.

**Comment by jerrypaulsam** [comment]
I have the same issue and I am not using any other packages. Does anyone got a solution other than the one mentioned above?

Thanks
