### ISSUE TITLE
[iOS] accept audio call does not open the app

### ISSUE THREAD

**Issue by tungs0ul** [hiennguyen92/flutter_callkit_incoming#324]
when I accept the video call, it will open my app and redirect to the page I want. If the call is audio call, it does not open the app and stay on the audio call panel without any connection

**Comment by hiennguyen92** [comment]
ios does not allow calling audio to open the app directly. you have to use callkit UI.

**Comment by zionnite** [comment]
please, can you provide sample code to use callKit Ui to open your app?
