### ISSUE TITLE
Handlers not working when app is terminated or killed

### ISSUE THREAD

**Issue by Usama9999** [hiennguyen92/flutter_callkit_incoming#33]
Hi, I am adding a video call feature to my app.
I am using firebase handlers to show incoming call notifications. But I can't handle background acceptance and rejection when the app is terminated or killed. Is there any way to do it?

**Comment by hiennguyen92** [comment]
https://github.com/hiennguyen92/flutter_callkit_incoming/blob/master/PUSHKIT.md

Please using Pushkit/VoIP for IOS

For android, please using background firebase receive for show incomming ui

**Comment by Usama9999** [comment]
> https://github.com/hiennguyen92/flutter_callkit_incoming/blob/master/PUSHKIT.md
> 
> Please using Pushkit/VoIP for IOS
> 
> For android, please using background firebase receive for show incoming UI

yeah its showing. But what abound the events. I mean if my app is closed and received a incoming call notification and I accept it. The app get open but on accept I can navigate to a new screen

**Comment by hiennguyen92** [comment]
Hi @Usama9999 

you can temporarily use 
```
await FlutterCallkitIncoming.activeCalls()
```

**Comment by sunilsinghchaudhary00** [comment]
> > Hi @Usama9999
> > you can temporarily use
> > ```
> > await FlutterCallkitIncoming.activeCalls()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It will return the last call that you accepted.
> 
> How do i know if a call is accepted when the app opens on ios, below is the response from await FlutterCallkitIncoming.activeCalls()
> 
> ```
> {
>   "extra": {
>     "platform": "ios",
>     "user": "abc@123"
>   },
>   "avatar": "",
>   "uuid": "eeb6cbed-cb07-4602-90f4-19f02cac1147",
>   "id": "eeb6cbed-cb07-4602-90f4-19f02cac1147",
>   "nameCaller": "Hien Nguyenh",
>   "type": 1,
>   "duration": 30000,
>   "appName": "Callkit",
>   "handle": "0123456789",
>   "normalHandle": 0,
>   "ios": {
>     "maximumCallGroups": 2,
>     "supportsUngrouping": true,
>     "maximumCallsPerCallGroup": 1,
>     "supportsGrouping": true,
>     "handleType": "",
>     "audioSessionActive": true,
>     "supportsHolding": true,
>     "audioSessionPreferredIOBufferDuration": 0.005,
>     "supportsDTMF": true,
>     "audioSessionPreferredSampleRate": 44100.0,
>     "supportsVideo": true,
>     "ringtonePath": "",
>     "configureAudioSession": true,
>     "iconName": "CallKitLogo",
>     "audioSessionMode": "",
>     "includesCallsInRecents": true
>   }
> }
> ```

did find the solution bro
