### ISSUE TITLE
Remove Callkit title in incoming call

### ISSUE THREAD

**Issue by Borlay** [hiennguyen92/flutter_callkit_incoming#331]
It seems i can't remove Callkit title in incoming call. Tried all propirties like appName, handle, nameCaller, nothing works.

here is image:
![image](https://github.com/hiennguyen92/flutter_callkit_incoming/assets/6999100/9182c0ec-149c-4c63-80af-d6e7adacc299)

**Comment by Borlay** [comment]
Android by the way, package version: 2.0.0

**Comment by jerrypaulsam** [comment]
I think you have `isShowLogo: true` . change it to false

**Comment by Borlay** [comment]
> I think you have `isShowLogo: true` . change it to false

Thanks, that helped

**Comment by sunil-singh-chaudhary** [comment]
hi thats working but can i replace callkit with my own title can you help pls instead of callkit i want like appname but it didnt work either callkit or nothing showing i have added  appName: 'my appname', but not showing

**Comment by anusha-chromosis** [comment]
> hi thats working but can i replace callkit with my own title can you help pls instead of callkit i want like appname but it didnt work either callkit or nothing showing i have added appName: 'my appname', but not showing

did you get the solution?

**Comment by sunil-singh-chaudhary** [comment]
> > hi thats working but can i replace callkit with my own title can you help pls instead of callkit i want like appname but it didnt work either callkit or nothing showing i have added appName: 'my appname', but not showing
> 
> did you get the solution?

hi pls check my below utils 

`// ignore_for_file: file_names

import 'dart:developer';

import 'package:pranaamExperts/utils/config.dart';
import 'package:flutter_callkit_incoming/entities/android_params.dart';
import 'package:flutter_callkit_incoming/entities/call_kit_params.dart';
import 'package:flutter_callkit_incoming/entities/notification_params.dart';
import 'package:flutter_callkit_incoming/flutter_callkit_incoming.dart';
import 'package:uuid/uuid.dart';

class CallUtils {
  static Future<void> showIncomingCall(var body) async {
    log('started showing incoming call');
    Uuid uuid = const Uuid();
    String currentUuid = uuid.v4();
    String defaultImage = 'https://i.pravatar.cc/500';
    String? profilePic = body['profile'];
    String imageUrl;
    if (profilePic != null) {
      imageUrl = imgBaseurl + profilePic;
    } else {
      imageUrl = defaultImage;
    }
    bool calltype = body['call_type'] == 10; //video call or audio call
    log('calltype is  $calltype');
    log('imageUrl is  $imageUrl');
    log('imageUrl is  ${body['name']}');
    CallKitParams callKitParams = CallKitParams(
      id: currentUuid,
      nameCaller: body['name'],
      appName: 'Pranaam',
      handle: 'Pranaam Partner',
      // avatar: imageUrl,
      type: calltype ? 0 : 1, // 0 for audio call, 1 for video call
      textAccept: 'Accept',
      textDecline: 'Decline',
      duration: 30000,
      missedCallNotification: const NotificationParams(
        showNotification: true,
        isShowCallback: false,
        subtitle: 'Missed call',
        callbackText: 'Call back',
      ),
      extra: <String, dynamic>{
        'call_type': body['call_type'],
        'notificationType': body['notificationType'],
        'callId': body['callId'],
        'profile': body['profile'],
        'name': body['name'],
        'id': body['id'],
        'fcmToken': body['fcmToken'],
        'call_duration': body['call_duration'].toString(),
        'call_method': body['call_method'].toString()
      },

      headers: <String, dynamic>{'apiKey': 'sunil@123!', 'platform': 'flutter'},
      android: const AndroidParams(
        isCustomNotification: true,
        isShowLogo: true,
        ringtonePath: 'system_ringtone_default',
        backgroundColor: '#0955fa',
        // backgroundUrl: defaultImage,
        actionColor: '#4CAF50',
        textColor: '#ffffff',
        incomingCallNotificationChannelName: "Incoming Call 1",
        isShowCallID: true, //for showing handle in incoming call notification
      ),
    );

    await FlutterCallkitIncoming.showCallkitIncoming(callKitParams);
  }
}
`
