### ISSUE TITLE
Call screen not opening when starting a call

### ISSUE THREAD

**Issue by icodelifee** [hiennguyen92/flutter_callkit_incoming#333]
After the call gets started though .startCall(params), the callkit pages does not show up. You have to open recent apps to go to the call screen

**Comment by hiennguyen92** [comment]
when startCall you have to implement the calling screen yourself with flutter.

**Comment by icodelifee** [comment]
> when startCall you have to implement the calling screen yourself with flutter.

On iOS?, cant CallKit already do that?

**Comment by hiennguyen92** [comment]
To synchronize between both iOS and Android, the calling screen must always be implemented with flutter (except in the case of iOS startCall from history phone book)

**Comment by icodelifee** [comment]
> To synchronize between both iOS and Android, the calling screen must always be implemented with flutter (except in the case of iOS startCall from history phone book)

I do  have a calling screen but specifically for ios since CallKit is available why not use that instead of custom calling screen

**Comment by icodelifee** [comment]
Im not able to launch callkit from the notification bar, after the call starts
