### ISSUE TITLE
Ringtone is still ringing while phone is on silent or vibration

### ISSUE THREAD

**Issue by Usama9999** [hiennguyen92/flutter_callkit_incoming#34]

**Comment by rachelgomez161999** [comment]
The “Find my phone” feature bypasses the ringtone. This is the same for your alarm app or any other anti-theft application installed.

But how do I silence it, anyway?

Go to your phone’s Accessibility settings, go to Hearing (or Sound/Audio. Depending on your phone.) and enable “Mute all sounds.” This should block out all sounds, including the Find My Phone ringer. This will also block out all media, ringtone or notification sounds, so use it wisely.

**_This may help you,
Rachel Gomez_**

**Comment by hiennguyen92** [comment]
Hi @Usama9999 Can you tell me which version you are using?

What operating system are you using?
Do you have any video screenshots? It will help me a lot.

**Comment by Usama9999** [comment]
> Hi @Usama9999 Can you tell me which version you are using?
> 
> What operating system are you using(Android/IOS)? Do you have any video screenshots? It will help me a lot.

I am using android

**Comment by hiennguyen92** [comment]
Yes. I got it. I will check and fix it

**Comment by hiennguyen92** [comment]
Hi @Usama9999 

I just deployed version 1.0.1+2
please check it
