### ISSUE TITLE
How to set incoming call to fullscreen?

### ISSUE THREAD

**Issue by stryder123451** [hiennguyen92/flutter_callkit_incoming#343]
@hiennguyen92  are there any methods to force incoming call to full screen?

**Comment by hiennguyen92** [comment]
there will be no way to just show full screen. because it will affect the user experience when using other apps.

**Comment by stryder123451** [comment]
Hm , i need this to trigger  didChangeAppLifecycleState , because if call show druing open app and user accepts call , nothing happens, but if user tap on call notification and make it fullscreen , didChangeAppLifecycleState works fine

**Comment by stryder123451** [comment]
@hiennguyen92  or any methods to trigger didChangeAppLifecycleState when app is resumed?
