### ISSUE TITLE
it's not working in ios state when reciveing a notification to show call kit

### ISSUE THREAD

**Issue by eng-sayed** [hiennguyen92/flutter_callkit_incoming#347]
## alwayn in ios state show this error

![Screenshot 2023-08-07 at 3 49 20 PM](https://github.com/hiennguyen92/flutter_callkit_incoming/assets/56679747/7d01016c-94b3-4d96-bd8c-15cef954f01e)

**Comment by siko1699** [comment]
thanks its work

**Comment by eng-sayed** [comment]
thanks its work
