### ISSUE TITLE
need help in backend for ios terminated and background callkit.

### ISSUE THREAD

**Issue by 7ANV1R** [hiennguyen92/flutter_callkit_incoming#349]
``**// What I'm trying to achieve:** 

In my Flutter app, when I receive an FCM notification and that notification’s data contains a specific key, I will show flutter_callkit_incoming 2.0.0+1’s callkit. That’s it.

**// What’s working and what’s not working**
It’s working perfectly on Android (foreground, background, and terminated state). It’s also working only foreground on ios devices. But not working on background or terminated state on ios.

**// How I tried to implement**
in main.dart (some @pragma('vm:entry-point') is unnecessary maybe)
```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await SharedPrefServices.init();

  /// [initialize firebase]
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  FirebaseMessaging.onBackgroundMessage(_firebaseMsgBackground);
  runApp(const ProviderScope(child: MyApp()));
}

@pragma('vm:entry-point')
Future<void> _firebaseMsgBackground(RemoteMessage message) async {
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  listenTerminatedCallEvent();
  if (isVideoCall(message)) {
    _firebaseCallBackground(message);
  } else if (isTextMessage(message)) {
    _firebaseTextBackground(message);
  }
}

@pragma('vm:entry-point')
Future<void> _firebaseTextBackground(RemoteMessage remoteMessage) async {
  print("[in _firebaseTextBackground ]");
}

@pragma('vm:entry-point')
Future<void> _firebaseCallBackground(RemoteMessage remoteMessage) async {
  print("[in _firebaseCallBackground]");
  final firebaseNotificationServices = FirebaseNotificationServices();
  firebaseNotificationServices.showIncomingCall(remoteMessage);
}
```
 firebaseNotificationServices.showIncomingCall(remoteMessage) looks like this

```
void showIncomingCall(RemoteMessage remoteMessage) async {
    const uuid = Uuid();
    final callKitNotificationId = uuid.v4();
    print(
        '[call received received on showIncomingCall] id: $callKitNotificationId Title: ${remoteMessage.notification?.title}, Body: ${remoteMessage.notification?.body}, Extra data: ${remoteMessage.data}');
    // listenTerminatedCallEvent();
    CallKitParams callKitParams = CallKitParams(
      id: callKitNotificationId,
      nameCaller: remoteMessage.data["requestFromName"],
      appName: 'Rebusel',
      avatar: imageUrlWithBaseUrl(remoteMessage.data["requestImage"]) ??
          'https://staging.rebusel.com/logo/icon.png',
      handle: remoteMessage.data["body"],
      type: 1,
      textAccept: 'Accept',
      textDecline: 'Decline',
      duration: 30000,
      missedCallNotification: const NotificationParams(
        showNotification: false,
        isShowCallback: false,
        subtitle: 'Missed call',
        callbackText: 'Call back',
      ),
      extra: remoteMessage.data,
      // headers: <String, dynamic>{'apiKey': 'Abc@123!', 'platform': 'flutter'},
      android: const AndroidParams(
        isCustomNotification: true,
        isShowLogo: false,
        ringtonePath: 'system_ringtone_default',
        backgroundColor: '#0955fa',
        backgroundUrl: PictureConstants.callBg,
        actionColor: '#4CAF50',
        incomingCallNotificationChannelName: "High Importance Channel",
        missedCallNotificationChannelName: "Missed Call",
      ),

      ios: const IOSParams(
        iconName: 'ic_launcher',
        handleType: 'generic',
        supportsVideo: true,
        maximumCallGroups: 2,
        maximumCallsPerCallGroup: 1,
        audioSessionMode: 'default',
        audioSessionActive: true,
        audioSessionPreferredSampleRate: 44100.0,
        audioSessionPreferredIOBufferDuration: 0.005,
        supportsDTMF: true,
        supportsHolding: false,
        supportsGrouping: false,
        supportsUngrouping: false,
        ringtonePath: 'system_ringtone_default',
      ),
    );

    await FlutterCallkitIncoming.showCallkitIncoming(callKitParams);
  }
```
I've set up AppDelegate.swift file as your PUSHKIT.md file said. I think AppDelegates were set perfectly that's why the foreground call is showing. if you want I can share AppDelegate.swift file later.

**MID Discussion question:** Do I have to define showCallkitIncoming() as a top-level function like your example project? and what should I do with this token FlutterCallkitIncoming.getDevicePushTokenVoIP(); do I have to put somewhere that VoIP push token?

_____

**// what my backend do**
I've talked to my backend developer. he said for FCM he just needed the server key. that's the only thing I provided previously. 
and I saw his code once he is sending data like this way
this is demo code, of course he is sending many necessary field like sound, and
```
 "apns": {
       "headers": {
         "apns-priority": "5",
       },
     },
```
```
<?php

namespace App\Http\Controllers;

use App\Models\User;
use App\Services\FCMService;
use App\Http\Controllers\Controller;

class UserController extends Controller 
{
    public function sendNotificationrToUser($id)
    {
       // get a user to get the fcm_token that already sent.               from mobile apps 
       $user = User::findOrFail($id);

      FCMService::send(
          $user->fcm_token,
          [
              'title' => 'your title',
              'body' => 'your body',
          ]
      );

    }
}
```

**This way basic notification works perfectly even in ios terminated state showing notifications.**

then I showed the last part of PUSHKIT.md file to my backend developer and he got confused by that
```
curl -v \
-d '{"aps":{"alert":"Hien Nguyen Call"},"id":"44d915e1-5ff4-4bed-bf13-c423048ec97a","nameCaller":"Hien Nguyen","handle":"0123456789","isVideo":true}' \
-H "apns-topic: com.hiennv.testing.voip" \
-H "apns-push-type: voip" \
--http2 \
--cert VOIP.pem:'<passphrase>' \
https://api.development.push.apple.com/3/device/<device token>
```

**Qu: should he implement this code in the existing Laravel FCM project or should he create a separate project for only ios notification cause this code contains https://api.development.push.apple.com/ URL?**
I mean how did he implement this part on the backend side? can you give some guidance?
and Do I need this id from the backend with UUID v4 format? cause I'm handling id from my flutter code later.

**Conclusion:  your guidance will help me a lot. hope you've read and understand the full issue. I know this might not be your expertise side but I'm sure you have the experience to work with this.**

**Comment by Taati89** [comment]
I'm sorry, is it possible for you to explain the solution you applied to me?

**Comment by iamriajul** [comment]
@7ANV1R You might want to use https://github.com/edamov/pushok package, or https://github.com/appleboy/gorush
I've used gorush.
And another tip, If get stuck at converting .p12 certificate .pem certificate, you can fix this certificate conversion issue by using openssl@1.1 (brew install openssl@1.1) and then run command like this: `/usr/local/Cellar/openssl@1.1/1.1.1v/bin/openssl ...`

**Comment by niteshneupane** [comment]
hey @7ANV1R  will you please explain the solution?

**Comment by 7ANV1R** [comment]
> hey @7ANV1R will you please explain the solution?

this is actual solution. this works magically. 
```
curl -v \
-d '{"aps":{"alert":"Hien Nguyen Call"},"id":"44d915e1-5ff4-4bed-bf13-c423048ec97a","nameCaller":"Hien Nguyen","handle":"0123456789","isVideo":true}' \
-H "apns-topic: com.hiennv.testing.voip" \
-H "apns-push-type: voip" \
--http2 \
--cert VOIP.pem:'<passphrase>' \
https://api.development.push.apple.com/3/device/<device token>
```
This is like an API call with voip.pem certificate.
read carefully PUSHKIT.md[https://github.com/hiennguyen92/flutter_callkit_incoming/blob/master/PUSHKIT.md] file
search more about apple VOIP.

**Comment by niteshneupane** [comment]
> > hey @7ANV1R will you please explain the solution?
> 
> this is actual solution. this works magically. type this command in terminal with your .pem file that will send a call magically.
> 
> ```
> curl -v \
> -d '{"aps":{"alert":"Hien Nguyen Call"},"id":"44d915e1-5ff4-4bed-bf13-c423048ec97a","nameCaller":"Hien Nguyen","handle":"0123456789","isVideo":true}' \
> -H "apns-topic: com.hiennv.testing.voip" \
> -H "apns-push-type: voip" \
> --http2 \
> --cert VOIP.pem:'<passphrase>' \
> https://api.development.push.apple.com/3/device/<device token>
> ```
> 
> This is like an API call with voip.pem certificate. read carefully PUSHKIT.md[https://github.com/hiennguyen92/flutter_callkit_incoming/blob/master/PUSHKIT.md] file search more about apple VOIP.

I did this . And it works for IPAD. But in Iphone I am getting just an icon as shown in figure. No Idea whats wrong I check the configurations and setup multiple times.
![WhatsApp Image 2023-11-03 at 3 48 06 PM](https://github.com/hiennguyen92/flutter_callkit_incoming/assets/107905954/d8f44029-f60a-4897-a33e-7061f829437b)

**Comment by Jazzykhan** [comment]
I am having same issue and can not solve it for 3 months now :(  
On iOS the onBackgroundMessage function from Fcm does't trigger at all. The notification arrive on time but the function doesn't trigger to start the incoming call screen :(
Somebody please share the solution.
thanks


what will be the device token it will be the same fcm token?

**Comment by iamriajul** [comment]
@Jazzykhan FCM doesn't work for Background Incoming Call, you need to use APNs.

**Comment by Jazzykhan** [comment]
@iamriajul i don't understand what is Apns i need to connect it with fcm? or using apns is something different?

**Comment by iamriajul** [comment]
@Jazzykhan You need to use APNs (Apple Plush Notification service) directly and configure PushKit (check PUSHKIT.readme). This is a little bit complicated, you need to read Apple documentation to understand it fully. Thanks.
