### ISSUE TITLE
App crash on android 10 both in background and foreground 

### ISSUE THREAD

**Issue by sadaqatdev** [hiennguyen92/flutter_callkit_incoming#35]
FATAL EXCEPTION: main
E/AndroidRuntime(11106): Process: com.wealways.alwayschat, PID: 11106
E/AndroidRuntime(11106): java.lang.RuntimeException: Unable to start service com.hiennv.flutter_callkit_incoming.CallkitSoundPlayerService@7f4fa37 with Intent { cmp=com.wealways.alwayschat/com.hiennv.flutter_callkit_incoming.CallkitSoundPlayerService (has extras) }: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.media.MediaPlayer.setLooping(boolean)' on a null object reference
E/AndroidRuntime(11106):        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4433)
E/AndroidRuntime(11106):        at android.app.ActivityThread.access$1800(ActivityThread.java:270)
E/AndroidRuntime(11106):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2083)
E/AndroidRuntime(11106):        at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(11106):        at android.os.Looper.loop(Looper.java:237)
E/AndroidRuntime(11106):        at android.app.ActivityThread.main(ActivityThread.java:7948)
E/AndroidRuntime(11106):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(11106):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(11106):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
E/AndroidRuntime(11106): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.media.MediaPlayer.setLooping(boolean)' on a null object reference
E/AndroidRuntime(11106):        at com.hiennv.flutter_callkit_incoming.CallkitSoundPlayerService.c(Unknown Source:53)
E/AndroidRuntime(11106):        at com.hiennv.flutter_callkit_incoming.CallkitSoundPlayerService.onStartCommand(Unknown Source:0)
E/AndroidRuntime(11106):        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4415)
E/AndroidRuntime(11106):        ... 8 more
E/AndroidRuntime(11702): FATAL EXCEPTION: main
E/AndroidRuntime(11702): Process: com.wealways.alwayschat, PID: 11702
E/AndroidRuntime(11702): java.lang.RuntimeException: Unable to start service com.hiennv.flutter_callkit_incoming.CallkitSoundPlayerService@418f35e with Intent { cmp=com.wealways.alwayschat/com.hiennv.flutter_callkit_incoming.CallkitSoundPlayerService (has extras) }: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.media.MediaPlayer.setLooping(boolean)' on a null object reference
E/AndroidRuntime(11702):        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4433)
E/AndroidRuntime(11702):        at android.app.ActivityThread.access$1800(ActivityThread.java:270)
E/AndroidRuntime(11702):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2083)
E/AndroidRuntime(11702):        at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(11702):        at android.os.Looper.loop(Looper.java:237)
E/AndroidRuntime(11702):        at android.app.ActivityThread.main(ActivityThread.java:7948)
E/AndroidRuntime(11702):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(11702):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(11702):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
E/AndroidRuntime(11702): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.media.MediaPlayer.setLooping(boolean)' on a null object reference
E/AndroidRuntime(11702):        at com.hiennv.flutter_callkit_incoming.CallkitSoundPlayerService.c(Unknown Source:53)
E/AndroidRuntime(11702):        at com.hiennv.flutter_callkit_incoming.CallkitSoundPlayerService.onStartCommand(Unknown Source:0)
E/AndroidRuntime(11702):        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4415)

**Comment by hiennguyen92** [comment]
@sadaqatdev please make sure you set 

`ringtonePath: 'system_ringtone_default'`

**Comment by sadaqatdev** [comment]
yes i set it as , 'ringtonePath': 'ringtone_default', which define in plugin doc

**Comment by sadaqatdev** [comment]
working thanks
