### ISSUE TITLE
Duplicate notification while receiving the call

### ISSUE THREAD

**Issue by sagarstackapp** [hiennguyen92/flutter_callkit_incoming#351]
I have used [flutter_callkit_incoming](https://pub.dev/packages/flutter_callkit_incoming) for the call notification on the flutter side. It works perfectly on every device. But in some cases, it sends multiple notifications for the same call. And it happens eventually. Don't know the exact test case in which the repeated notification showing.

TestCase: Once I make a call to another user (receiver) is getting multiple notifications for the same call.

Thank you in advance

**Comment by niteshneupane** [comment]
I am also facing this issue @hiennguyen92 Sir.

**Comment by Mahfa** [comment]
i have the same issue

**Comment by msalmancode** [comment]
Also facing the issue even in latest plugin

**Comment by hiennguyen92** [comment]
I think this issue may come from FCM (I checked their log). to ensure the notification is only shown once. I think you should check before calling showcallkit.something similar to:  
onBackground(message){
if(message.messageId){
//show here
}
}
Same with onMessage
