### ISSUE TITLE
Multiple Call Notifications showing

### ISSUE THREAD

**Issue by niteshneupane** [hiennguyen92/flutter_callkit_incoming#354]
Test Case 
* open app send notification
* receive call and end call after talking
* again send another notification without closing app
* Now two notification pop up
* Like wise notification number continues to increase the number of times call is accepted.

See this in attached video

https://github.com/hiennguyen92/flutter_callkit_incoming/assets/107905954/8ab8c5cd-5242-4763-9367-8f73b663f492

**Comment by poudyalanil** [comment]
I am facing same  issue on one of my projects.

**Comment by burzza** [comment]
Serious issue

**Comment by niteshneupane** [comment]
solved

**Comment by 7ANV1R** [comment]
> solved

how did you solve this? @niteshneupane

**Comment by niteshneupane** [comment]
> 

In BasePage initState method I have used 
`FirebaseMessaging.onMessage.listen((RemoteMessage message) async {}`
This Function So on Navigating to base from other pages This function reinitiates creating multiple instances thus two or more notification comes..

So now i fixed by using this above runApp()
