### ISSUE TITLE
Not working in Release mode but working in Debug Mode

### ISSUE THREAD

**Issue by hrishikeshpujari1902** [hiennguyen92/flutter_callkit_incoming#356]
When I run in the android emulator in debug mode it works completely fine. As I run or build with release mode it just pops as a notification and no incoming call UI is seen.

**Comment by hiennguyen92** [comment]
incomming call only shows when on lock screen or off screen (android)

**Comment by hrishikeshpujari1902** [comment]
> incomming call only shows when on lock screen or off screen (android)

Hey Thanks for the Package and reply but the issue is solved using @pragma('vm:entry-point') on BackgroundMessageHandler function.
