### ISSUE TITLE
[ios] how to Deactivate callkit for China using NSLocal 

### ISSUE THREAD

**Issue by 7ANV1R** [hiennguyen92/flutter_callkit_incoming#359]
I've implemented callkit by this package instructions.  now i'm trying to upload my app in app store.
in app store review said like this

> Guideline 5.0 - Legal
> 
> Recently, the Chinese Ministry of Industry and Information Technology (MIIT) requested that CallKit functionality be deactivated in all apps available on the China App Store.
> 
> During our review, we found that your app currently includes CallKit functionality and has China listed as an available territory in App Store Connect.
> 
> Next Steps
> 
> This app cannot be approved with CallKit functionality active in China. Please make the appropriate changes and resubmit this app for review.
> 
> If you have already ensured that CallKit functionality is not active in China, you may reply to this message in App Store Connect to confirm.
> 
> Voice over Internet Protocol (VoIP) call functionality continues to be allowed but can no longer take advantage of CallKit’s intuitive look and feel. CallKit can continue to be used in apps outside of China.

I've zero knowledge about swift that's why i'm asking help. this could be helpful for many people like me.

**Comment by hiennguyen92** [comment]
Callkit is not supported in China.
https://stackoverflow.com/questions/51016603/disabling-callkit-from-china-store-best-approach
