### ISSUE TITLE
[Bug]: getAcceptPendingIntent is not working when app is in foreground.

### ISSUE THREAD

**Issue by iamriajul** [hiennguyen92/flutter_callkit_incoming#362]
getAcceptPendingIntent is not working when the app is in the foreground the app's foreground status was triggered by the package.

### Steps to reproduce

1. Start the app fresh
2. Now press the back button (swipe back) to put the app in the background. (Where the Dart VM is no more alive).
3. Call the app, which shows incoming call notification (ofcourse with Decline and Accept button).
4. Click Accept, which opens your app and shows video call screen.
5. End the Video Call but don't close the app. (I call `FlutterCallkitIncoming.endAllCalls();` after webrtc disconnected).
6. Now call the app, which shows incoming notification while your app is visible behind notification.
7. Now try to click the Accept button in the Notification (bug, it doesn't work) but clicking the Decline button does work properly.

Note: At step 7, as per my debugging I've found when clicking the `Accept` button the `TransparentActivity` doesn't call onCreate, I suspect that somehow the system restricting the `TransparentActivity` from being created again, might be because it was created before when we Accepted call at step 4.

Thanks.

**Comment by iamriajul** [comment]
By adding these flags to the TransparentActivity Intent I was able to fix the problem occurred at step 7:
- FLAG_ACTIVITY_REORDER_TO_FRONT
- FLAG_ACTIVITY_CLEAR_TOP
- FLAG_ACTIVITY_SINGLE_TOP
- FLAG_ACTIVITY_BROUGHT_TO_FRONT

I've modified TransparentActivity.kt like this:

```kt
class TransparentActivity : Activity() {

    companion object {
        fun getIntent(context: Context, action: String, data: Bundle?): Intent {
            val intent = Intent(context, TransparentActivity::class.java)
            intent.action = action
            intent.putExtra("data", data)
            intent.addFlags(Intent.FLAG_ACTIVITY_NO_ANIMATION)
            intent.addFlags(Intent.FLAG_ACTIVITY_NO_HISTORY)
            intent.addFlags(Intent.FLAG_ACTIVITY_REORDER_TO_FRONT)
            intent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP)
            intent.addFlags(Intent.FLAG_ACTIVITY_SINGLE_TOP)
            intent.addFlags(Intent.FLAG_ACTIVITY_BROUGHT_TO_FRONT)
            return intent
        }
    }
    //....
```

@hiennguyen92 What are your thoughts on these changes?

Thanks.

**Comment by hiennguyen92** [comment]
Thank @iamriajul I will check and merge it.
