### ISSUE TITLE
ios real device show this error Fatal error: Unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by kapilsharma-gts** [hiennguyen92/flutter_callkit_incoming#366]
flutter_incoming_call/SwiftFlutterIncomingCallPlugin.swift:117: Fatal error: Unexpectedly found nil while unwrapping an Optional value

thread https://github.com/Alezhka/flutter_incoming_call/issues/1, queue = 'com.apple.main-thread', stop reason = Fatal error: Unexpectedly found nil while unwrapping an Optional value
frame #0: 0x000000018851532c libswiftCore.dylib`_swift_runtime_on_report

**Comment by hiennguyen92** [comment]
Please make sure the id is UUID format.
