### ISSUE TITLE
[Android] Can receive call without opening lock screen Android

### ISSUE THREAD

**Issue by thaidmfinnick** [hiennguyen92/flutter_callkit_incoming#369]
Hi @hiennguyen92,

If screen is on, I can receive call and open my app without any problem. But I want to receive call without opening lock screen like Zalo audio call, can `flutter_callkit_incoming` do this for Android?

Thank you and hope get your feedback soon!

**Comment by datpt11** [comment]
same issue :v

**Comment by berger89** [comment]
@hiennguyen92 
do you have any idea how to turn off the PIN code entry when a call is answered?

**Comment by delwar36** [comment]
Do this in your app splash page or home page. It also works for accepting calls from a terminated state.

```
Future<dynamic> getCurrentCall() async {
    //check current call from pushkit if possible
    var calls = await FlutterCallkitIncoming.activeCalls();
    if (calls is List) {
     // print('DATA: ${calls.length}');
      if (calls.isNotEmpty) {
        // _currentUuid = calls[0]['id'];
        return calls[0];
      } else {
        // _currentUuid = "";
        return null;
      }
    }
  }

var currentCall = await getCurrentCall();
    if (currentCall != null &&
        (currentCall['accepted'] || currentCall['accepted'] == 'true')) {
       //Navigate to your call screen.
    }
```

**Comment by thaidmfinnick** [comment]
@delwar36 thanks for your response! The first function `getCurrentCall` I have already used for accepting call from terminated. But I want to accept call and join the call without opening lock screen.
In your code, you still need to navigate to call screen.

**Comment by hiennguyen92** [comment]
@thaidmfinnick If you want to make a call without opening lock screen, you need to do it in Android's navite code, I think it's outside this package.

**Comment by thaidmfinnick** [comment]
thanks for your response! I will closed as resolved.

**Comment by berger89** [comment]
@thaidmfinnick do you have a sample code how to implement it in the android native code?

**Comment by thaidmfinnick** [comment]
Many thanks @berger89 for finding solution, I will test and response soonn

**Comment by krunaladit** [comment]
android:showWhenLocked="true"
if you are using in flutter then above flag make your full app accessible without opening lock screen in call case.
