### ISSUE TITLE
important

### ISSUE THREAD

**Issue by baron7272** [hiennguyen92/flutter_callkit_incoming#37]
If the app is killed, the incoming call notification does not start. please check

**Comment by hiennguyen92** [comment]
@baron7272 Can you explain more?

For IOS, you need to setup Pushkit and VoIP,
For Android, Just call it when receiving push notification from background

**Comment by dhpl** [comment]
hi @hiennguyen92. If the app is in background, when a call incoming. How to get the data? Thanks

**Comment by hiennguyen92** [comment]
@dhpl you should combine 
`CallEvent.ACTION_CALL_INCOMING` và `activeCalls`
