### ISSUE TITLE
[iOS Release] Doesn't show incoming call in iOS release mode but works in debug mode. 

### ISSUE THREAD

**Issue by delwar36** [hiennguyen92/flutter_callkit_incoming#374]
I am using FCM form sending signals. Everything works fine in Android  (debug and release) and iOS debug mode. But not getting call in background and terminated state in release mode. I am getting notification but showCallkitIncoming not showing any call.  
And also getting call in foreground as expected
@hiennguyen92 please have a look on this issue

```
/// For fcm background message handler.
@pragma('vm:entry-point')
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  await notificationService.setupFlutterNotifications();

  if (message.data['id'] == "calling") {
    await notificationService.registerToCallkitEvent();
    notificationService.showCallkitIncoming(
      message.data['callId'] ?? message.messageId!,
      message.data['userName'],
      message.data['userPhoto'],
      message.data['groupName'],
      message.data['channelName'],
      message.data['userId'],
      type: message.data['video'],
      callerDevicetoken: message.data['callerDevicetoken'],
      // callToken: message.data['callToken'],
    );
  } else if (message.data['id'] == "call_declined") {
    log("Caller Declined the call");
    final callId = message.data['callId'];

    await FlutterCallkitIncoming.endCall(callId);
  } else if (message.data['id'] == "messaging" &&
      message.notification == null) {
    notificationService.showFlutterNotification(message);
  }
}

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // Set the background messaging handler early on, as a named top-level function
  FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);
  if (!kIsWeb) {
    await notificationService.requestNotificationPerission();
    notificationService.setupFlutterNotifications();
  }
  runApp(const MyApp());
}
```

**Comment by delwar36** [comment]
Closing the issue as after more investigation we found that the problem is nit on `flutter_callkit_incoming`. It’s because of `firebase_messaging` not working properly on iOS [#9381](https://github.com/firebase/flutterfire/issues/9381#issuecomment-1227415893).
We shifted to flutter [Push](https://pub.dev/packages/push) which is better performing.

**Comment by Jazzykhan** [comment]
How push helped can you share any code or help?

I am having same issue and can not solve it for 3 months now :(  
On iOS the onBackgroundMessage function from Fcm does't trigger at all. The notification arrive on time but the function doesn't trigger to start the incoming call screen :(
Somebody please share the solution.
thanks

**Comment by Technozer** [comment]
hyy @Jazzykhan how to solved this issue.

**Comment by Jazzykhan** [comment]
@Technozer  hi i solved by using there example code and reading everything carefully. I think the issue was in the swift file.
