### ISSUE TITLE
Problem with callkit opening a new empty instance of the app

### ISSUE THREAD

**Issue by viniciusoliverrs** [hiennguyen92/flutter_callkit_incoming#377]
I'm having a problem with callkit opening a new empty instance of the app. Even though the application is in the foreground, when the callkit window arrives, I click and Callkit opens in full screen, as soon as callkit closes, I open a new instance of the app as if it were the first time I opened the 
![55689419-bce4-4fd0-abd3-5c5930c7528b](https://github.com/hiennguyen92/flutter_callkit_incoming/assets/30914699/0cb013c3-7136-4440-983e-4f11b9f97f0f)

**Comment by PrinceGoyal** [comment]
set android:launchMode="singleInstance" for mainActivity inside manifest file.

**Comment by viniciusoliverrs** [comment]
Thanks
