### ISSUE TITLE
Android background notification "Accept" button

### ISSUE THREAD

**Issue by marcoberetta96** [hiennguyen92/flutter_callkit_incoming#38]
On Android, when receiving a call while in background, if I tab on the accept button, the notification disappears and nothing else happens.

<img width="279" alt="image" src="https://user-images.githubusercontent.com/11749393/155419674-aa6848d7-5509-45c6-a988-337fe77b35da.png">

Instead, if I click on the notification the following screen opens.

<img width="292" alt="image" src="https://user-images.githubusercontent.com/11749393/155419871-231b2230-e579-412f-a366-10da8463847e.png">

Then, if I click on the accept button, the app correctly opens.

This happens only when the notification is shown while the app is closed.
If the app is in foreground, everything works fine.

Thanks!

**Comment by hiennguyen92** [comment]
i will check it. thank

**Comment by hiennguyen92** [comment]
Please check with version 1.0.1+3.

**Comment by marcoberetta96** [comment]
@hiennguyen92 with the last version you basically reverted this commit https://github.com/hiennguyen92/flutter_callkit_incoming/commit/b6c2c68345e25d9a9f8471dcd6fb871f30724092
I think you did not intended to do that... can you please confirm?

**Comment by hiennguyen92** [comment]
Hi @marcoberetta96 
sorry for reverting your commit. but I think if we do that, we won't be able to set other props.
 You can set other props this way(it will be more convenient and can set more props if needed)
 https://github.com/hiennguyen92/flutter_callkit_incoming/blob/222a550cc558f908a5a28f55b783f092d4cc8ce3/example/ios/Runner/AppDelegate.m#L31

**Comment by marcoberetta96** [comment]
@hiennguyen92 thanks, I will try that.

Anyway, I regret to tell this issue is not solved.

When accepting a call from the full screen interface everything works great.

When accepting the call from here nothing still happens.

<img width="279" alt="image" src="https://user-images.githubusercontent.com/11749393/155419674-aa6848d7-5509-45c6-a988-337fe77b35da.png">

**Comment by hiennguyen92** [comment]
can you tell me the android version you are using? Can you help me record screen of the whole process?

**Comment by marcoberetta96** [comment]
Sure!

Pixel 3a • android-arm64  • Android 12 (API 31)

Here the recording https://www.dropbox.com/s/84xaietkc9m4ily/screen-20220312-133111~2.mp4?dl=0

**Comment by hiennguyen92** [comment]
Thank you

**Comment by hiennguyen92** [comment]
maybe it's bug with android v12, i will check and fix it

**Comment by hiennguyen92** [comment]
@marcoberetta96 please help me check with version 1.0.1+4

**Comment by marcoberetta96** [comment]
@hiennguyen92 the good news is that now the accept button is working when receiving a call while in background!

There is an odd thing (regression?) with version 1.0.1+4.
When the app is open, if I click on the Accept button, the whole flutter app is restarted and then the call starts.
![](https://user-images.githubusercontent.com/11749393/155419674-aa6848d7-5509-45c6-a988-337fe77b35da.png)
I do not understand why the app restarts... This is a new behaviour of the latest version. Do you have any idea?

Thanks!

**Comment by hiennguyen92** [comment]
I'm not sure what happened. however, you can remove the old version and reinstall the apk. If the error still occurs, please record screen for me. thank

**Comment by marcoberetta96** [comment]
Unfortunately the problem still occurs.

Here a record screen: https://www.dropbox.com/s/w9fbd4542lhj39c/callkit.mp4?dl=0

Thank you!

**Comment by hiennguyen92** [comment]
I just updated v 1.0.1+5, hope it's working welll. 
I have double checked it on android < 12 and android >= 12

**Comment by marcoberetta96** [comment]
It's working great!
Thank you!!
