### ISSUE TITLE
iOS native events handler

### ISSUE THREAD

**Issue by Arley011** [hiennguyen92/flutter_callkit_incoming#382]
Is there a way to listen to events in native Swift code? 
I would like to send an API to notify that the call was declined, but I'm not using flutter background push handlers to show a call and listen for events (like in example with firebase handler). Is there a way to listen for the events stream in Swift code? Or maybe to catch events by [overriding some methods](https://developer.apple.com/forums/thread/702334) (won't it broke the package's logic though?)?

By the way, thanks a lot for this package.

**Comment by hiennguyen92** [comment]
please using verion 2.0.1+2 (please example)
