### ISSUE TITLE
Allow to set more parameters from Objective C

### ISSUE THREAD

**Issue by marcoberetta96** [hiennguyen92/flutter_callkit_incoming#39]
Currently from Objective C it's possible to set only `id`, `nameCaller`, `handle` and `type`.

`    @objc public init(id: String, nameCaller: String, handle: String, type: Int) {`

Could you please expose some more parameters?
For example `appName`, `avatar`, `duration` and `extra`.
Thanks!

If it's fine for you, I could make a PR.

**Comment by hiennguyen92** [comment]
@marcoberetta96 
you can use the same as Swift

```
 //Swift
  var info = [String: Any?]()
  info["id"] = "44d915e1-5ff4-4bed-bf13-c423048ec97a"
  info["nameCaller"] = "Hien Nguyen"
  info["handle"] = "0123456789"
  info["type"] = 1
  SwiftFlutterCallkitIncomingPlugin.sharedInstance?.showCallkitIncoming(flutter_callkit_incoming.Data(args: info), fromPushKit: true)
```

**Comment by hiennguyen92** [comment]
@marcoberetta96 
I don't have much experience with objective-c. so i think you can set value to prop of instance

example: obj.name = @"dfdfdf"

**Comment by hiennguyen92** [comment]
@marcoberetta96  please help me make PR. thank you.

**Comment by marcoberetta96** [comment]
@hiennguyen92  just added https://github.com/hiennguyen92/flutter_callkit_incoming/pull/41

**Comment by hiennguyen92** [comment]
Thank you
