### ISSUE TITLE
[Question][iOS] Callback from call history

### ISSUE THREAD

**Issue by berger89** [hiennguyen92/flutter_callkit_incoming#392]
When I click on one of the entries in the iOS call histories, my app opens. How do I get the data (e.g. the number) of the entry?

<img src="https://github.com/hiennguyen92/flutter_callkit_incoming/assets/17617106/15b12c55-bad2-4098-90d5-723d3141c41d" width="200">

**Comment by hiennguyen92** [comment]
You can check it here: https://github.com/hiennguyen92/flutter_callkit_incoming/blob/deac4f0d38b6edd59157753425933dd4558dd0a7/example/ios/Runner/AppDelegate.swift#L24
