### ISSUE TITLE
 Run on emulatior with error: App requires Multidex support

### ISSUE THREAD

**Issue by vangtry** [hiennguyen92/flutter_callkit_incoming#394]
i update to   flutter_callkit_incoming: ^2.0.0+2 i now i get this error 

[!] App requires Multidex support
    Multidex support is required for your android app to build since the number of methods has exceeded 64k. See https://docs.flutter.dev/deployment/android#enabling-multidex-support for more information. You may pass the --no-multidex flag to skip Flutter's multidex support to use a manual solution.

my build.gradle file

    defaultConfig {
       ...
        multiDexEnabled true
    }

when disabled this plugin my applicoation works fine but when installed it again then happen this issue

**Comment by hiennguyen92** [comment]
When adding multiple libs android app, you will get multiDexEnabled error. You should enable it according to the instructions.
