### ISSUE TITLE
Call popup not appearing in iOS

### ISSUE THREAD

**Issue by niteshneupane** [hiennguyen92/flutter_callkit_incoming#397]
We are using flutter_callkit_incoming for our call processing but after implementation of APN for call notification calls seems to be coming in foreground but shows a small icon on top left  and users can't interact with the call. 

![image](https://github.com/hiennguyen92/flutter_callkit_incoming/assets/107905954/d7726ef5-e70f-4a43-9ac3-77546521f89a)

**Comment by esraaalaain** [comment]
this happened because the uuid is not unique

**Comment by Tim-byte-afk** [comment]
> это произошло потому, что uuid не уникален

Hello, please tell me is it not unique in relation to what? if the call is 1 at the current moment. I encountered the same problem after updating iOS to version 17

**Comment by esraaalaain** [comment]
I face the Same Issue after updating my iPhone to 17. 
I found that after resetting my phone just the first call showed after that none.
because we didn't clear the call (uuid) after the answer or after the reject,
I have sent the UUId from the backend and it works perfectly now
