### ISSUE TITLE
How to execute something after rejecting incoming call ?

### ISSUE THREAD

**Issue by SayedShalan** [hiennguyen92/flutter_callkit_incoming#40]

**Comment by hiennguyen92** [comment]
@SayedShalan 

please using event `CallEvent.ACTION_CALL_DECLINE` 

also make sure `FlutterCallkitIncoming.onEvent.listen` on app widget

**Comment by SayedShalan** [comment]
@hiennguyen92 Yes, but it isn't called if app is terminated

**Comment by hiennguyen92** [comment]
@SayedShalan Once you receive the pushkit/VoIP the app will automatically be reactivated.

**Comment by hiennguyen92** [comment]
It's imperative for IOS that you incorporate pushkit.

**Comment by SayedShalan** [comment]
@hiennguyen92 Thank you for your response, I mean I have incoming call from fcm, I need when I Reject the incoming call then the callback will work. It is called if app is on foreground or terminated but not work if app terminated, Just it cancel the call.

**Comment by hiennguyen92** [comment]
When you receive VoIP, the app will automatically activate from terminated state. So, `FlutterCallkitIncoming.onEvent.listen` will working.

**Comment by MingSern** [comment]
@SayedShalan How did you solve this?
