### ISSUE TITLE
Unable to load icon CallKitLogo.

### ISSUE THREAD

**Issue by kapilsharma-gts** [hiennguyen92/flutter_callkit_incoming#404]
i am facing this issue in. iPhone can you please. check. and. help me out - and if any thing needed please comment

Unable to load icon CallKitLogo.

**Comment by Tim-byte-afk** [comment]
> Я столкнулся с этой проблемой. iPhone, пожалуйста. проверять. и. помогите мне - и если что-то нужно, пожалуйста, прокомментируйте
> 
> Невозможно загрузить значок CallKitLogo.

hi, didn't find a solution?

**Comment by iambhabha** [comment]
I have discovered that voip is not set in the ios info.list file.

![image](https://github.com/hiennguyen92/flutter_callkit_incoming/assets/97278053/c43dc643-f7ab-48fe-9b57-4ae336714836)
