### ISSUE TITLE
ending calls always fires decline event 

### ISSUE THREAD

**Issue by ribalassaf** [hiennguyen92/flutter_callkit_incoming#407]
Hello, I'm facing a case where I need to dissmiss the call notification from the flutter_callkit_incoming package when I open the app.
but I don't want to fire any events.
is this possible in anyway?

**Comment by deven98** [comment]
+1 to this issue.

We would love to have a silent way to end calls and not trigger any CallKit events (maybe a simple `silent` flag on the method?)

@hiennguyen92 happy to launch a PR exploring this if needed.

**Comment by hiennguyen92** [comment]
Yes. Please

**Comment by deven98** [comment]
Perfect, we'll launch a PR to achieve this in a bit.

**Comment by Brazol** [comment]
https://github.com/hiennguyen92/flutter_callkit_incoming/pull/408
please let me know if this looks good @hiennguyen92

**Comment by hiennguyen92** [comment]
@Brazol please using 2.0.1 and check changelog
