### ISSUE TITLE
How can I handle handle call is accepted or not in IOS?

### ISSUE THREAD

**Issue by Khizar-crewLogix** [hiennguyen92/flutter_callkit_incoming#413]
I need to handle either call is accepted or not . In Android it has the accepted param which shows it is accepted or not but in IOS there is no param like that and i am unable to handle that if anyone help me it will be good for me.

**Comment by hiennguyen92** [comment]
please using 2.0.1 and check example https://github.com/hiennguyen92/flutter_callkit_incoming/blob/master/example/ios/Runner/AppDelegate.swift

**Comment by Khizar-crewLogix** [comment]
@hiennguyen92 i think this code will be used if i am using pushkit service But i am working with FCM
