### ISSUE TITLE
(2.0.1) Android build failed

### ISSUE THREAD

**Issue by stMerlHin** [hiennguyen92/flutter_callkit_incoming#420]
# `flutter doctor`
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.5, on Kali GNU/Linux Rolling 6.5.0-kali3-amd64, locale fr_FR.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK  version 34.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2022.3)
[✓] IntelliJ IDEA Community Edition (version 2023.2)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!

# Output
e: file:///home/st/.pub-cache/hosted/pub.dev/flutter_callkit_incoming-2.0.1/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/CallkitIncomingActivity.kt:23:52 Unresolved reference: RippleRelativeLayout
e: file:///home/st/.pub-cache/hosted/pub.dev/flutter_callkit_incoming-2.0.1/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/CallkitIncomingActivity.kt:71:49 Unresolved reference: RippleRelativeLayout
e: file:///home/st/.pub-cache/hosted/pub.dev/flutter_callkit_incoming-2.0.1/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/CallkitIncomingActivity.kt:88:37 Unresolved reference: Utils
e: file:///home/st/.pub-cache/hosted/pub.dev/flutter_callkit_incoming-2.0.1/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/CallkitIncomingActivity.kt:235:31 Unresolved reference: CallkitNotificationManager
e: file:///home/st/.pub-cache/hosted/pub.dev/flutter_callkit_incoming-2.0.1/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/CallkitIncomingActivity.kt:248:33 Not enough information to infer type variable T
e: file:///home/st/.pub-cache/hosted/pub.dev/flutter_callkit_incoming-2.0.1/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/CallkitIncomingActivity.kt:249:44 Variable expected
e: file:///home/st/.pub-cache/hosted/pub.dev/flutter_callkit_incoming-2.0.1/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/CallkitIncomingActivity.kt:250:17 Unresolved reference: Utils
e: file:///home/st/.pub-cache/hosted/pub.dev/flutter_callkit_incoming-2.0.1/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/CallkitIncomingActivity.kt:250:42 Unresolved reference: Utils
e: file:///home/st/.pub-cache/hosted/pub.dev/flutter_callkit_incoming-2.0.1/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/CallkitIncomingActivity.kt:261:36 Unresolved reference: Utils
e: file:///home/st/.pub-cache/hosted/pub.dev/flutter_callkit_incoming-2.0.1/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/CallkitIncomingActivity.kt:287:28 Unresolved reference: TransparentActivity
e: file:///home/st/.pub-cache/hosted/pub.dev/flutter_callkit_incoming-2.0.1/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/CallkitIncomingBroadcastReceiver.kt:81:42 Unresolved reference: CallkitNotificationManager
e: file:///home/st/.pub-cache/hosted/pub.dev/flutter_callkit_incoming-2.0.1/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/CallkitIncomingBroadcastReceiver.kt:89:21 Unresolved reference: addCall
e: file:///home/st/.pub-cache/hosted/pub.dev/flutter_callkit_incoming-2.0.1/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/CallkitIncomingBroadcastReceiver.kt:104:21 Unresolved reference: addCall
e: file:///home/st/.pub-cache/hosted/pub.dev/flutter_callkit_incoming-2.0.1/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/CallkitIncomingBroadcastReceiver.kt:115:21 Unresolved reference: addCall
e: file:///home/st/.pub-cache/hosted/pub.dev/flutter_callkit_incoming-2.0.1/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/CallkitIncomingBroadcastReceiver.kt:126:21 Unresolved reference: removeCall
e: file:///home/st/.pub-cache/hosted/pub.dev/flutter_callkit_incoming-2.0.1/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/CallkitIncomingBroadcastReceiver.kt:137:21 Unresolved reference: removeCall
e: file:///home/st/.pub-cache/hosted/pub.dev/flutter_callkit_incoming-2.0.1/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/CallkitIncomingBroadcastReceiver.kt:150:21 Unresolved reference: removeCall
e: file:///home/st/.pub-cache/hosted/pub.dev/flutter_callkit_incoming-2.0.1/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/FlutterCallkitIncomingPlugin.kt:12:44 Unresolved reference: Utils
e: file:///home/st/.pub-cache/hosted/pub.dev/flutter_callkit_incoming-2.0.1/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/FlutterCallkitIncomingPlugin.kt:48:27 Unresolved reference: reapCollection
e: file:///home/st/.pub-cache/hosted/pub.dev/flutter_callkit_incoming-2.0.1/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/FlutterCallkitIncomingPlugin.kt:48:44 Overload resolution ambiguity: 
public inline fun <T> Iterable<TypeVariable(T)>.forEach(action: (TypeVariable(T)) -> Unit): Unit defined in kotlin.collections
public inline fun <K, V> Map<out TypeVariable(K), TypeVariable(V)>.forEach(action: (Map.Entry<TypeVariable(K), TypeVariable(V)>) -> Unit): Unit defined in kotlin.collections
e: file:///home/st/.pub-cache/hosted/pub.dev/flutter_callkit_incoming-2.0.1/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/FlutterCallkitIncomingPlugin.kt:49:17 Unresolved reference: it
e: file:///home/st/.pub-cache/hosted/pub.dev/flutter_callkit_incoming-2.0.1/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/FlutterCallkitIncomingPlugin.kt:54:27 Unresolved reference: reapCollection
e: file:///home/st/.pub-cache/hosted/pub.dev/flutter_callkit_incoming-2.0.1/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/FlutterCallkitIncomingPlugin.kt:54:44 Overload resolution ambiguity: 
public inline fun <T> Iterable<TypeVariable(T)>.forEach(action: (TypeVariable(T)) -> Unit): Unit defined in kotlin.collections
public inline fun <K, V> Map<out TypeVariable(K), TypeVariable(V)>.forEach(action: (Map.Entry<TypeVariable(K), TypeVariable(V)>) -> Unit): Unit defined in kotlin.collections
e: file:///home/st/.pub-cache/hosted/pub.dev/flutter_callkit_incoming-2.0.1/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/FlutterCallkitIncomingPlugin.kt:55:17 Unresolved reference: it
e: file:///home/st/.pub-cache/hosted/pub.dev/flutter_callkit_incoming-2.0.1/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/FlutterCallkitIncomingPlugin.kt:67:55 Unresolved reference: CallkitNotificationManager
e: file:///home/st/.pub-cache/hosted/pub.dev/flutter_callkit_incoming-2.0.1/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/FlutterCallkitIncomingPlugin.kt:93:45 Unresolved reference: CallkitNotificationManager
e: file:///home/st/.pub-cache/hosted/pub.dev/flutter_callkit_incoming-2.0.1/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/FlutterCallkitIncomingPlugin.kt:134:21 Unresolved reference: getDataActiveCalls
e: file:///home/st/.pub-cache/hosted/pub.dev/flutter_callkit_incoming-2.0.1/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/FlutterCallkitIncomingPlugin.kt:135:15 Overload resolution ambiguity: 
public inline fun <T> Iterable<TypeVariable(T)>.forEach(action: (TypeVariable(T)) -> Unit): Unit defined in kotlin.collections
public inline fun <K, V> Map<out TypeVariable(K), TypeVariable(V)>.forEach(action: (Map.Entry<TypeVariable(K), TypeVariable(V)>) -> Unit): Unit defined in kotlin.collections
e: file:///home/st/.pub-cache/hosted/pub.dev/flutter_callkit_incoming-2.0.1/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/FlutterCallkitIncomingPlugin.kt:139:29 Unresolved reference: it
e: file:///home/st/.pub-cache/hosted/pub.dev/flutter_callkit_incoming-2.0.1/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/FlutterCallkitIncomingPlugin.kt:143:9 Unresolved reference: removeAllCalls
e: file:///home/st/.pub-cache/hosted/pub.dev/flutter_callkit_incoming-2.0.1/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/FlutterCallkitIncomingPlugin.kt:147:23 Unresolved reference: reapCollection
e: file:///home/st/.pub-cache/hosted/pub.dev/flutter_callkit_incoming-2.0.1/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/FlutterCallkitIncomingPlugin.kt:147:40 Overload resolution ambiguity: 
public inline fun <T> Iterable<TypeVariable(T)>.forEach(action: (TypeVariable(T)) -> Unit): Unit defined in kotlin.collections
public inline fun <K, V> Map<out TypeVariable(K), TypeVariable(V)>.forEach(action: (Map.Entry<TypeVariable(K), TypeVariable(V)>) -> Unit): Unit defined in kotlin.collections
e: file:///home/st/.pub-cache/hosted/pub.dev/flutter_callkit_incoming-2.0.1/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/FlutterCallkitIncomingPlugin.kt:148:13 Unresolved reference: it
e: file:///home/st/.pub-cache/hosted/pub.dev/flutter_callkit_incoming-2.0.1/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/FlutterCallkitIncomingPlugin.kt:276:33 Unresolved reference: getDataActiveCalls
e: file:///home/st/.pub-cache/hosted/pub.dev/flutter_callkit_incoming-2.0.1/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/FlutterCallkitIncomingPlugin.kt:277:27 Overload resolution ambiguity: 
public inline fun <T> Iterable<TypeVariable(T)>.forEach(action: (TypeVariable(T)) -> Unit): Unit defined in kotlin.collections
public inline fun <K, V> Map<out TypeVariable(K), TypeVariable(V)>.forEach(action: (Map.Entry<TypeVariable(K), TypeVariable(V)>) -> Unit): Unit defined in kotlin.collections
e: file:///home/st/.pub-cache/hosted/pub.dev/flutter_callkit_incoming-2.0.1/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/FlutterCallkitIncomingPlugin.kt:278:29 Unresolved reference: it
e: file:///home/st/.pub-cache/hosted/pub.dev/flutter_callkit_incoming-2.0.1/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/FlutterCallkitIncomingPlugin.kt:282:45 Unresolved reference: it
e: file:///home/st/.pub-cache/hosted/pub.dev/flutter_callkit_incoming-2.0.1/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/FlutterCallkitIncomingPlugin.kt:289:45 Unresolved reference: it
e: file:///home/st/.pub-cache/hosted/pub.dev/flutter_callkit_incoming-2.0.1/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/FlutterCallkitIncomingPlugin.kt:294:21 Unresolved reference: removeAllCalls
e: file:///home/st/.pub-cache/hosted/pub.dev/flutter_callkit_incoming-2.0.1/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/FlutterCallkitIncomingPlugin.kt:305:36 Unresolved reference: getDataActiveCallsForFlutter

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_callkit_incoming:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

**Comment by sipalto** [comment]
Did you manage to fix it @stMerlHin ?

**Comment by sipalto** [comment]
Cheers @stMerlHin I have already fixed. If someone is also facing same issue just run:
`flutter clean`
