### ISSUE TITLE
When Accept call from lockscreen im stuck here.

### ISSUE THREAD

**Issue by sokpheng** [hiennguyen92/flutter_callkit_incoming#43]
What is the right way to accept call on lock screen ?
in the screenshot it look perfectly what I need. However it not open my app to connect the call, instead it just show timer and call screen like below. And my other device is waiting for accept.

also this screen not go away after my called finished. Is there a way to force close it?

![2022-02-28 14 32 17](https://user-images.githubusercontent.com/27798903/155942269-6ee0316d-b160-4960-aa78-14493a79cea0.jpg)

**Comment by hiennguyen92** [comment]
For iOS, Callkit will display for audio, redirect to app for video(iOS >=14)
however, the app will still automatically activate with pushkit and still receive onEven.listen

**Comment by sokpheng** [comment]
How I can talk through the lockscreen call with webrtc?

**Comment by hiennguyen92** [comment]
use onEven.listen to get listenner and connect webrtc

**Comment by sokpheng** [comment]
so it will allow app to talk through after peerConnected ?

**Comment by hiennguyen92** [comment]
the application will work in background via pushkit. so background tasks are still active (when receiving VoIP pushkit, the application will automatically start and work in the background)

**Comment by sokpheng** [comment]
Is there a way to enable video directly when accept call ?

**Comment by hiennguyen92** [comment]
Using type:1 for video call (After accepting, it will automatically navigate to app for iOS >=14)

**Comment by dhpl** [comment]
hi anh @hiennguyen92 , anh cho em hỏi trên ios khi mình accept cuộc gọi ờ màn hình lockscreen thì có cách pushNamed tới màn hình call của mình ko anh (Em đang setup webrtc ờ màn hình call)

**Comment by hiennguyen92** [comment]
@dhpl nếu là Android thì còn được. Chứ iOS phải là type: 1 video call mới được.

**Comment by dhpl** [comment]
> @dhpl nếu là Android thì còn được. Chứ iOS phải là type: 1 video call mới được.
em thấy zalo họ hiện được màn hình call. ko biết họ làm như thế nào

**Comment by hiennguyen92** [comment]
Zalo hiện màn hình call đi thôi. Chứ nhận incoming audio thì nó vẫn ở màn hình callkit mà

**Comment by dhpl** [comment]
Khi accept ờ màn hình lockscreen, là app zalo họ đẩy qua màn hình call luôn anh

**Comment by hiennguyen92** [comment]
Thì a nói rồi đó, e call với type có video call thì nó mở app. Còn chỉ audio không thì nó chỉ mở callkit thôi

**Comment by hiennguyen92** [comment]
Còn nếu call audio không thì nó cũng chỉ mở callkit rồi đếm giây thôi

**Comment by dhpl** [comment]
![IMG_7013](https://user-images.githubusercontent.com/22500109/156723538-c23aaac5-d47d-4632-8e1f-977dfd88f7fe.PNG)
khi bấm accept ờ lockscreen rồi mờ app zalo lên là họ đã đẩy qua màn hình call lúc nào rồi anh. Em đang stuck chổ đó, tất cả connect của e nằm ở màn hình MyCall phải đẩy qua đó mới connect được

**Comment by hiennguyen92** [comment]
Khi e nhận pushkit mà e show lên cái incoming này là app nó tự active lại rồi.
https://github.com/hiennguyen92/flutter_callkit_incoming/blob/c29e3d86b17d09121d1af324f553ecfdd49c9b5a/example/ios/Runner/AppDelegate.swift#L68

E chỉ cần lắng nghe listener trên App widget là đc sử dụng .onEvent.....

**Comment by dhpl** [comment]
Đúng rồi anh. Em đang bắt sự kiện này CallEvent.ACTION_CALL_ACCEPT để push qua màn hình MyCall. Mà lúc accept nó ko pushNamed qua màn hình đó được anh. Khi mở app nó mới pushNamed qua màn hình MyCall

**Comment by hiennguyen92** [comment]
@dhpl e sử dụng một số giải pháp ở đây thử
https://stackoverflow.com/questions/60589234/how-to-navigate-when-click-background-notification-on-flutter

**Comment by dhpl** [comment]
> https://stackoverflow.com/questions/60589234/how-to-navigate-when-click-background-notification-on-flutter
Thanks anh, em làm được. Chạy release mode là tự nhiên nó được =))
