### ISSUE TITLE
No Notification for new call in sample project

### ISSUE THREAD

**Issue by mateenamin** [hiennguyen92/flutter_callkit_incoming#432]
here is my code git link: https://github.com/mateenamin/testingViewProPublicCode

Flutter version  3.16.8 vs Dart version 3.2.5
flutter_callkit_incoming: ^2.0.1+1
My Flutter App is Run Project But not call incoming is ruining 

Launching lib\main.dart on SM A325F in debug mode...
Running Gradle task 'assembleDebug'...
√  Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app-debug.apk...
Debug service listening on ws://127.0.0.1:60585/OiTC23Xfwp0=/ws
Syncing files to device SM A325F...
I/DecorView(27192): notifyKeepScreenOnChanged: keepScreenOn=false
I/ViewRootImpl@36582cc[MainActivity](27192): performTraversals params={(0,0)(fillxfill) sim={adjust=resize forwardNavigation} ty=BASE_APPLICATION fmt=TRANSLUCENT wanim=0x1030001
I/ViewRootImpl@36582cc[MainActivity](27192):   fl=81810100
I/ViewRootImpl@36582cc[MainActivity](27192):   pfl=16020040
I/ViewRootImpl@36582cc[MainActivity](27192):   vsysui=2500
I/ViewRootImpl@36582cc[MainActivity](27192):   apr=LIGHT_STATUS_BARS
I/ViewRootImpl@36582cc[MainActivity](27192):   bhv=DEFAULT
I/ViewRootImpl@36582cc[MainActivity](27192):   fitSides= naviIconColor=0}
I/ViewRootImpl@36582cc[MainActivity](27192): performTraversals mFirst=false windowShouldResize=false viewVisibilityChanged=false mForceNextWindowRelayout=false params={(0,0)(fillxfill) sim={adjust=resize forwardNavigation} ty=BASE_APPLICATION fmt=TRANSLUCENT wanim=0x1030001
I/ViewRootImpl@36582cc[MainActivity](27192):   fl=81810100
I/ViewRootImpl@36582cc[MainActivity](27192):   pfl=16020040
I/ViewRootImpl@36582cc[MainActivity](27192):   vsysui=2500
I/ViewRootImpl@36582cc[MainActivity](27192):   apr=LIGHT_STATUS_BARS
I/ViewRootImpl@36582cc[MainActivity](27192):   bhv=DEFAULT
I/ViewRootImpl@36582cc[MainActivity](27192):   fitSides= naviIconColor=0}
I/ViewRootImpl@36582cc[MainActivity](27192): updateBlastSurfaceIfNeeded mBlastBufferQueue=0xb4000079eea52b00 isSameSurfaceControl=true
I/BLASTBufferQueue(27192): update, w= 1080 h= 2400 mName = ViewRootImpl@36582cc[MainActivity] mNativeObject= 0xb4000079eea52b00 sc.mNativeObject= 0xb4000079cad23680 format= -3 caller= android.view.ViewRootImpl.updateBlastSurfaceIfNeeded:2898 android.view.ViewRootImpl.relayoutWindow:9847 android.view.ViewRootImpl.performTraversals:3884 android.view.ViewRootImpl.doTraversal:3116 android.view.ViewRootImpl$TraversalRunnable.run:10885 android.view.Choreographer$CallbackRecord.run:1301 
I/ViewRootImpl@36582cc[MainActivity](27192): Relayout returned: old=(0,0,1080,2400) new=(0,0,1080,2400) req=(1080,2400)0 dur=16 res=0x1 s={true 0xb4000079d0900000} ch=false seqId=0
I/ViewRootImpl@36582cc[MainActivity](27192): updateBoundsLayer: t = android.view.SurfaceControl$Transaction@20dcd73 sc = Surface(name=Bounds for - com.example.testing/com.example.testing.MainActivity@0)/@0xe6bb430 frame = 1
I/ViewRootImpl@36582cc[MainActivity](27192): mWNT: t=0xb4000079d07f8d00 mBlastBufferQueue=0xb4000079eea52b00 fn= 1 caller= android.view.ViewRootImpl.prepareSurfaces:2985 android.view.ViewRootImpl.performTraversals:4233 android.view.ViewRootImpl.doTraversal:3116 
I/ViewRootImpl@36582cc[MainActivity](27192): reportNextDraw android.view.ViewRootImpl.performTraversals:4438 android.view.ViewRootImpl.doTraversal:3116 android.view.ViewRootImpl$TraversalRunnable.run:10885 android.view.Choreographer$CallbackRecord.run:1301 android.view.Choreographer$CallbackRecord.run:1309 
E/ion     (27192): ioctl c0044901 failed with code -1: Invalid argument
D/hw-ProcessState(27192): Binder ioctl to enable oneway spam detection failed: Invalid argument
I/BLASTBufferQueue(27192): [SurfaceView[com.example.testing/com.example.testing.MainActivity]@0#1](f:0,a:0) onFrameAvailable the first frame is available
I/BLASTBufferQueue(27192): [SurfaceView[com.example.testing/com.example.testing.MainActivity]@0#1](f:0,a:1) acquireNextBufferLocked size=1080x2361 mFrameNumber=1 applyTransaction=true mTimestamp=32708969112179(auto) mPendingTransactions.size=0 graphicBufferId=116788750712832 transform=0
D/SurfaceView@c3df87a(27192):  setAlpha: mUseAlpha = false alpha=1.0
D/SurfaceView@c3df87a(27192):  updateSurfaceAlpha: setUseAlpha() is not called, ignored.
I/ViewRootImpl@36582cc[MainActivity](27192): Setup new sync id=0
I/ViewRootImpl@36582cc[MainActivity](27192): Setting syncFrameCallback
I/ViewRootImpl@36582cc[MainActivity](27192): registerCallbacksForSync syncBuffer=false
I/ViewRootImpl@36582cc[MainActivity](27192): mWNT: t=0xb4000079cadf2c00 mBlastBufferQueue=0xb4000079eea52b00 fn= 1 caller= android.view.ViewRootImpl.lambda$applyTransactionOnDraw$11$android-view-ViewRootImpl:12865 android.view.ViewRootImpl$$ExternalSyntheticLambda1.onFrameDraw:4 android.graphics.HardwareRenderer$FrameDrawingCallback.onFrameDraw:924 
I/ViewRootImpl@36582cc[MainActivity](27192): Received frameDrawingCallback syncResult=0 frameNum=1.
I/ViewRootImpl@36582cc[MainActivity](27192): Setting up sync and frameCommitCallback
D/SurfaceView@c3df87a(27192): updateSurfacePosition RenderWorker, frameNr = 1, position = [0, 0, 1080, 2361] surfaceSize = 1080x2361
I/SurfaceView@c3df87a(27192): uSP: rtp = Rect(0, 0 - 1080, 2361) rtsw = 1080 rtsh = 2361
I/SurfaceView@c3df87a(27192): onSSPAndSRT: pl = 0 pt = 0 sx = 1.0 sy = 1.0
I/SurfaceView@c3df87a(27192): aOrMT: ViewRootImpl@36582cc[MainActivity] t = android.view.SurfaceControl$Transaction@cedcdcf fN = 1 android.view.SurfaceView.-$$Nest$mapplyOrMergeTransaction:0 android.view.SurfaceView$SurfaceViewPositionUpdateListener.positionChanged:1537 android.graphics.RenderNode$CompositePositionUpdateListener.positionChanged:373 
I/ViewRootImpl@36582cc[MainActivity](27192): mWNT: t=0xb4000079cadf2b00 mBlastBufferQueue=0xb4000079eea52b00 fn= 1 caller= android.view.SurfaceView.applyOrMergeTransaction:1455 android.view.SurfaceView.-$$Nest$mapplyOrMergeTransaction:0 android.view.SurfaceView$SurfaceViewPositionUpdateListener.positionChanged:1537 
I/BLASTBufferQueue(27192): [ViewRootImpl@36582cc[MainActivity]#0](f:0,a:0) onFrameAvailable the first frame is available
I/BLASTBufferQueue(27192): [ViewRootImpl@36582cc[MainActivity]#0](f:0,a:1) acquireNextBufferLocked size=1080x2400 mFrameNumber=1 applyTransaction=true mTimestamp=32709035516102(auto) mPendingTransactions.size=0 graphicBufferId=116788750712834 transform=0
I/ViewRootImpl@36582cc[MainActivity](27192): Received frameCommittedCallback lastAttemptedDrawFrameNum=1 didProduceBuffer=true
D/OpenGLRenderer(27192): CFMS:: SetUp Pid : 27192    Tid : 27240
W/Parcel  (27192): Expecting binder but got null!
I/ViewRootImpl@36582cc[MainActivity](27192): onSyncComplete
I/ViewRootImpl@36582cc[MainActivity](27192): setupSync seqId=0 mSyncId=0 fn=1 caller=android.view.ViewRootImpl$$ExternalSyntheticLambda11.accept:6 android.window.SurfaceSyncer.lambda$setupSync$1$android-window-SurfaceSyncer:128 android.window.SurfaceSyncer$$ExternalSyntheticLambda1.accept:8 android.window.SurfaceSyncer$SyncSet.checkIfSyncIsComplete:382 android.window.SurfaceSyncer$SyncSet.markSyncReady:359 android.window.SurfaceSyncer.markSyncReady:151 android.view.ViewRootImpl.performTraversals:4503 
I/ViewRootImpl@36582cc[MainActivity](27192): reportDrawFinished seqId=0 mSyncId=-1 fn=1 mSurfaceChangedTransaction=0xb4000079d07f8c00
I/ViewRootImpl@36582cc[MainActivity](27192): MSG_WINDOW_FOCUS_CHANGED 1 0
I/ViewRootImpl@36582cc[MainActivity](27192): mThreadedRenderer.initializeIfNeeded()#2 mSurface={isValid=true 0xb4000079d0900000}
D/InputMethodManager(27192): startInputInner - Id : 0
I/InputMethodManager(27192): startInputInner - mService.startInputOrWindowGainedFocus
D/InputMethodManager(27192): startInputInner - Id : 0
D/InsetsController(27192): onStateChanged: InsetsState: {mDisplayFrame=Rect(0, 0 - 1080, 2400), mDisplayCutout=DisplayCutout{insets=Rect(0, 80 - 0, 0) waterfall=Insets{left=0, top=0, right=0, bottom=0} boundingRect={Bounds=[Rect(0, 0 - 0, 0), Rect(468, 0 - 612, 80), Rect(0, 0 - 0, 0), Rect(0, 0 - 0, 0)]} cutoutPathParserInfo={CutoutPathParserInfo{displayWidth=1080 displayHeight=2400 physicalDisplayWidth=1080 physicalDisplayHeight=2400 density={2.625} cutoutSpec={M 0,0 H -27.42857142857143 V 30.47619047619048 H 27.42857142857143 V 0 H 0 Z @dp} rotation={0} scale={1.0} physicalPixelDisplaySizeRatio={1.0}}}}, mRoundedCorners=RoundedCorners{[RoundedCorner{position=TopLeft, radius=84, center=Point(84, 84)}, RoundedCorner{position=TopRight, radius=84, center=Point(996, 84)}, RoundedCorner{position=BottomRight, radius=84, center=Point(996, 2316)}, RoundedCorner{position=BottomLeft, radius=84, center=Point(84, 2316)}]}  mRoundedCornerFrame=Rect(0, 0 - 1080, 2400), mPrivacyIndicatorBounds=PrivacyIndicatorBounds {static bounds=Rect(964, 0 - 1080, 80) rotation=0}, mSources= { InsetsSource: {mType=ITYPE_STATUS_BAR, mFrame=[0,0][1080,80], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_NAVIGATION_BAR, mFrame=[0,2361][1080,2400], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_LEFT_GESTURES, mFrame=[0,0][78,2400], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_RIGHT_GESTURES, mFrame=[1002,0][1080,2400], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_TOP_MANDATORY_GESTURES, mFrame=[0,0][1080,112], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_BOTTOM_MANDATORY_GESTURES, mFrame=[0,2316][1080,2400], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_LEFT_DISPLAY_CUTOUT, mFrame=[0,0][-100000,2400], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_TOP_DISPLAY_CUTOUT, mFrame=[0,0][1080,80], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_RIGHT_DISPLAY_CUTOUT, mFrame=[100000,0][1080,2400], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_BOTTOM_DISPLAY_CUTOUT, mFrame=[0,100000][1080,2400], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_TOP_TAPPABLE_ELEMENT, mFrame=[0,0][1080,80], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_BOTTOM_TAPPABLE_ELEMENT, mFrame=[0,0][0,0], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_IME, mFrame=[0,0][0,0], mVisibleFrame=[0,1409][1080,2400], mVisible=false, mInsetsRoundedCornerFrame=false} } host=com.example.testing/com.example.testing.MainActivity from=android.view.ViewRootImpl$ViewRootHandler.handleMessageImpl:6740
I/ViewRootImpl(27192): updatePointerIcon pointerType = 1000, calling pid = 27192
D/InputManager(27192): setPointerIconType iconId = 1000, callingPid = 27192
I/ViewRootImpl@36582cc[MainActivity](27192): ViewPostIme pointer 0
I/ViewRootImpl@36582cc[MainActivity](27192): ViewPostIme pointer 1
D/CallkitTelecom(27192): [TelecomUtilities] reportIncomingCall number: Hien Nguyen, uuid: 1234
D/CompatibilityChangeReporter(27192): Compat change id reported: 160794467; UID 10354; state: ENABLED
W/example.testing(27192): Accessing hidden method Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard; (unsupported,core-platform-api, reflection, allowed)
W/example.testing(27192): Accessing hidden method Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V (unsupported,core-platform-api, reflection, allowed)
W/example.testing(27192): Accessing hidden method Ldalvik/system/CloseGuard;->warnIfOpen()V (unsupported,core-platform-api, reflection, allowed)
D/TrafficStats(27192): tagSocket(161) with statsTag=0xffffffff, statsUid=-1
D/TrafficStats(27192): tagSocket(162) with statsTag=0xffffffff, statsUid=-1
W/example.testing(27192): Accessing hidden method Lcom/android/org/conscrypt/ConscryptEngineSocket;->setUseSessionTickets(Z)V (max-target-q,core-platform-api, reflection, denied)
W/example.testing(27192): Accessing hidden method Lcom/android/org/conscrypt/OpenSSLSocketImpl;->setUseSessionTickets(Z)V (max-target-q,core-platform-api, reflection, denied)
W/example.testing(27192): Accessing hidden method Lcom/android/org/conscrypt/ConscryptEngineSocket;->setUseSessionTickets(Z)V (max-target-q,core-platform-api, reflection, denied)
W/example.testing(27192): Accessing hidden method Lcom/android/org/conscrypt/AbstractConscryptSocket;->setUseSessionTickets(Z)V (max-target-q, reflection, denied)
W/example.testing(27192): Accessing hidden method Lcom/android/org/conscrypt/OpenSSLSocketImpl;->setUseSessionTickets(Z)V (max-target-q,core-platform-api, reflection, denied)
W/example.testing(27192): Accessing hidden method Lcom/android/org/conscrypt/AbstractConscryptSocket;->setUseSessionTickets(Z)V (max-target-q, reflection, denied)
W/example.testing(27192): Accessing hidden method Lcom/android/org/conscrypt/ConscryptEngineSocket;->setHostname(Ljava/lang/String;)V (max-target-q,core-platform-api, reflection, denied)
W/example.testing(27192): Accessing hidden method Lcom/android/org/conscrypt/OpenSSLSocketImpl;->setHostname(Ljava/lang/String;)V (max-target-q,core-platform-api, reflection, denied)
W/example.testing(27192): Accessing hidden method Lcom/android/org/conscrypt/AbstractConscryptSocket;->setHostname(Ljava/lang/String;)V (max-target-q, reflection, denied)
W/example.testing(27192): Accessing hidden method Lcom/android/org/conscrypt/ConscryptEngineSocket;->setHostname(Ljava/lang/String;)V (max-target-q,core-platform-api, reflection, denied)
W/example.testing(27192): Accessing hidden method Lcom/android/org/conscrypt/OpenSSLSocketImpl;->setHostname(Ljava/lang/String;)V (max-target-q,core-platform-api, reflection, denied)
W/example.testing(27192): Accessing hidden method Lcom/android/org/conscrypt/AbstractConscryptSocket;->setHostname(Ljava/lang/String;)V (max-target-q, reflection, denied)
W/example.testing(27192): Accessing hidden method Lcom/android/org/conscrypt/OpenSSLSocketImpl;->setAlpnProtocols([B)V (max-target-q,core-platform-api, reflection, denied)
W/example.testing(27192): Accessing hidden method Lcom/android/org/conscrypt/AbstractConscryptSocket;->setAlpnProtocols([B)V (max-target-q, reflection, denied)
W/example.testing(27192): Accessing hidden method Lcom/android/org/conscrypt/OpenSSLSocketImpl;->setAlpnProtocols([B)V (max-target-q,core-platform-api, reflection, denied)
W/example.testing(27192): Accessing hidden method Lcom/android/org/conscrypt/AbstractConscryptSocket;->setAlpnProtocols([B)V (max-target-q, reflection, denied)
I/TelecomFramework(27192): TelecomConnectionService: createConnection, callManagerAccount: ComponentInfo{com.example.testing/com.hiennv.flutter_callkit_incoming.telecom.TelecomConnectionService}, ***, UserHandle{0}, callId: TC@59_1, request: ConnectionRequest xxxxxxxxxxxxxxxxx <MASKED> isAdhocConf: N, isIncoming: true, isUnknown: false, isLegacyHandover: false, isHandover: false,  addSelfManaged: true: (SBC.oSC)->CS.crCo->H.CS.crCo->H.CS.crCo.pICR(cet/cast)@E-JzE
D/CallkitTelecom(27192): [TelecomConnectionService] OnCreateIncomingConnection -- UUID:  number:1234
D/CallkitTelecom(27192): [TelecomConnectionService] createConnection -- UUID: 1234
D/CallkitTelecom(27192): [TelecomConnection] ON STATE CHANGED: 0
D/CallkitTelecom(27192): [TelecomConnection] ON STATE CHANGED: 2
D/CallkitTelecom(27192): [TelecomConnection] ON STATE CHANGED: 1
I/TelecomFramework(27192): TelecomConnectionService: notifyCreateConnectionComplete TC@59_1: (...->CSW.hCCC)->CS.crCoC->H.CS.crCoC(cet/cast)@E-E-E-JzE
I/TelecomFramework(27192): TelecomConnectionService: onAudioStateChanged TC@59_1 [AudioState isMuted: false, route: EARPIECE, supportedRouteMask: EARPIECE, SPEAKER, activeBluetoothDevice: [null], supportedBluetoothDevices: []]: (...->CSW.hCCC->CARSM.pM_UPDATE_SYSTEM_AUDIO_ROUTE)->CS.cASC->H.CS.cASC(cet/cast/cast)@E-E-E-JzE
D/CallkitTelecom(27192): [TelecomConnection] On Call Audio State Changed -- route: 1 -- is muted: false
I/TelecomFramework(27192): TelecomConnectionService: onAudioStateChanged TC@59_1 [AudioState isMuted: false, route: EARPIECE, supportedRouteMask: EARPIECE, SPEAKER, activeBluetoothDevice: [null], supportedBluetoothDevices: []]: (...->CSW.hCCC->CAMSM.pM_2002->CARSM.pM_SWITCH_FOCUS)->CS.cASC->H.CS.cASC(cet/cast/cast)@E-E-E-JzE
D/CallkitTelecom(27192): [TelecomConnection] On Call Audio State Changed -- route: 1 -- is muted: false
W/example.testing(27192): Accessing hidden method Lcom/android/org/conscrypt/OpenSSLSocketImpl;->getAlpnSelectedProtocol()[B (max-target-q,core-platform-api, reflection, denied)
W/example.testing(27192): Accessing hidden method Lcom/android/org/conscrypt/AbstractConscryptSocket;->getAlpnSelectedProtocol()[B (max-target-q, reflection, denied)
W/example.testing(27192): Accessing hidden method Lcom/android/org/conscrypt/OpenSSLSocketImpl;->getAlpnSelectedProtocol()[B (max-target-q,core-platform-api, reflection, denied)
W/example.testing(27192): Accessing hidden method Lcom/android/org/conscrypt/AbstractConscryptSocket;->getAlpnSelectedProtocol()[B (max-target-q, reflection, denied)

**Comment by hiennguyen92** [comment]
For Android 13+, please `requestNotificationPermission` or requestPermission of firebase_messaging before `showCallkitIncoming`
