### ISSUE TITLE
I have two questions for IOS only.

### ISSUE THREAD

**Issue by sokphengcheang** [hiennguyen92/flutter_callkit_incoming#439]
I have been using Flutter_callKit_incoming for almost 2years Thanks.  
However I have 2 problems.

1. I have 2 phones caller and receiver. 
I terminated the app and lock the phone on receiver side and then I start call from caller side and receiver did receive incoming call and show on lock screen, after on the caller side I press hangup and normally on receiver side if the phone unlock and incoming call as floating notification, and Yes it does dismissed the notification, but when screen is locked it won't dismissed until timeout.

2. Is there a way to let caller side know that the receiver side received incoming call when app in terminated state, When App on foreground I used socket to notifier the caller and change the Call status text from "Calling..." to "Ringing...", but when app terminated I have no idea how Receiver can notify to the caller side. is there a way to make it work?

**Comment by Jazzykhan** [comment]
I am having same issue and can not solve it for 3 months now :(  
On iOS the onBackgroundMessage function from Fcm does't trigger at all. The notification arrive on time but the function doesn't trigger to start the incoming call screen :(
Somebody please share the solution.

how did you manage to make it work on the ios?

For the hangup i used a stream builder from firebase to know on the caller (sender) side if the call is ended.
thanks

**Comment by zionnite** [comment]
have you been able to resolve it or still need help?

**Comment by sokphengcheang** [comment]
I still unable to solve it.
