### ISSUE TITLE
Android system cannot accept the call in full screen notification

### ISSUE THREAD

**Issue by hankwu0315** [hiennguyen92/flutter_callkit_incoming#444]
Steps:

1. Receive the call while in foreground
2. Turn notifications to full screen
3. Press accept the call
4. Delayed for a few seconds(stuck on full screen notification)
5. Then the app restarts

android: 12
flutter_callkit_incoming: v2.0.1+2

**Comment by veriak** [comment]
Hi!

I have the same problem!

**Comment by hungthinhitj** [comment]
i fix this by changing android:launchMode to singleTask, hope this help you guys

![image](https://github.com/hiennguyen92/flutter_callkit_incoming/assets/62649468/9d546b37-fa2c-4c57-a362-84de76920fb7)

**Comment by veriak** [comment]
Thanks hungthinhitj!

works for me.

**Comment by hankwu0315** [comment]
> i fixed this by changing android:launchMode to singleTask, hope this help you guys
> 
> ![image](https://private-user-images.githubusercontent.com/62649468/302194074-9d546b37-fa2c-4c57-a362-84de76920fb7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMDA2NzksIm5iZiI6MTcwNzIwMDM3OSwicGF0aCI6Ii82MjY0OTQ2OC8zMDIxOTQwNzQtOWQ1NDZiMzctZmEyYy00YzU3LWEzNjItODRkZTc2OTIwZmI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA2VDA2MTkzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiZjI1ZWYxNDlmMjg0OWMyNjE5OTg1ZTQ0YjIzYmNlY2E3MzU3OWVkZmFjYjFlZmI1NjNhOTZiNDA3ZjBlMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a82ntMVVZDa5SQWNBZM3d-cmECy-WM6JaooYoEpuDO4)

Thank you [hungthinhitj](https://github.com/hungthinhitj)!
It works for me.
