### ISSUE TITLE
Native IOS Incoming call changing title "Video..."

### ISSUE THREAD

**Issue by AimanKyo97** [hiennguyen92/flutter_callkit_incoming#445]
I changed type from 0 to 1, Is there ways to change Native ios incoming call screen title which word "Video..." to something else or disable it?

Please help, thank you.

@efraespada @AAkira @hiennguyen92 @Brazol @PaulBout1

**Comment by hiennguyen92** [comment]
cannot change it. iOS can only display Audio/Video
