### ISSUE TITLE
[HIGHT ALERT] Instance of the App is been created

### ISSUE THREAD

**Issue by zionnite** [hiennguyen92/flutter_callkit_incoming#448]
Hey man, when the app is on lock screen and once you click on the Accept call but, an instance of the app is been created automatically and it will be stuck on the splashscreen

**Comment by hiennguyen92** [comment]
https://github.com/hiennguyen92/flutter_callkit_incoming/blob/590d0396d48012f504b9f28d9d113ed7318d0531/example/android/app/src/main/AndroidManifest.xml#L8
i think you need to set android:launchMode="singleInstance" for your android application.

**Comment by hann-yun** [comment]
how about to write on README.md about this option?

**Comment by hiennguyen92** [comment]
https://github.com/hiennguyen92/flutter_callkit_incoming?tab=readme-ov-file#-installation
