### ISSUE TITLE
Error on android

### ISSUE THREAD

**Issue by bilalgodesto** [hiennguyen92/flutter_callkit_incoming#449]
Using latest version of the package.

Getting error on android

```
E/CallkitIncomingReceiver(25105): null
E/CallkitIncomingReceiver(25105): java.lang.NullPointerException
E/CallkitIncomingReceiver(25105): 	at com.hiennv.flutter_callkit_incoming.CallkitIncomingBroadcastReceiver.sendEventFlutter(CallkitIncomingBroadcastReceiver.kt:211)
E/CallkitIncomingReceiver(25105): 	at com.hiennv.flutter_callkit_incoming.CallkitIncomingBroadcastReceiver.onReceive(CallkitIncomingBroadcastReceiver.kt:134)
E/CallkitIncomingReceiver(25105): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4375)
E/CallkitIncomingReceiver(25105): 	at android.app.ActivityThread.access$1600(ActivityThread.java:256)
E/CallkitIncomingReceiver(25105): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2102)
E/CallkitIncomingReceiver(25105): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/CallkitIncomingReceiver(25105): 	at android.os.Looper.loopOnce(Looper.java:201)
E/CallkitIncomingReceiver(25105): 	at android.os.Looper.loop(Looper.java:288)
E/CallkitIncomingReceiver(25105): 	at android.app.ActivityThread.main(ActivityThread.java:7870)
E/CallkitIncomingReceiver(25105): 	at java.lang.reflect.Method.invoke(Native Method)
E/CallkitIncomingReceiver(25105): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/CallkitIncomingReceiver(25105): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

````

<details><summary>flutter doctor</summary>[✓] Flutter (Channel stable, 3.16.0, on macOS 14.1.1 23B81 darwin-arm64, locale en-US)
    • Flutter version 3.16.0 on channel stable at /Users/bilalrabbi/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db7ef5bf9f (3 months ago), 2023-11-15 11:25:44 -0800
    • Engine revision 74d16627b9
    • Dart version 3.2.0
    • DevTools version 2.28.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/bilalrabbi/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/bilalrabbi/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.14.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.86.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.82.0

[✓] Connected device (5 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android 12 (API 32) (emulator)
    • sdk gphone64 arm64 (mobile) • emulator-5556                        • android-arm64  • Android 12 (API 32) (emulator)
    • iPhone (mobile)             • 00008030-001004D80146802E            • ios            • iOS 17.1.1 21B91
    • iPhone 15 Pro (mobile)      • EE6B84E8-4092-497E-9033-9F330AC515B4 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-2 (simulator)
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 121.0.6167.160

[✓] Network resources
    • All expected network resources are available.</details>

**Comment by zionnite** [comment]
have you tried updating the minimum sdk and target sdk?

**Comment by hann-yun** [comment]
Any Updated?
