### ISSUE TITLE
App disappear when i click Recent Button

### ISSUE THREAD

**Issue by yoer** [hiennguyen92/flutter_callkit_incoming#451]
I am using your **flutter_callkit_incoming** for displaying offline push notifications in an Android app. 

When I kill the app and receive an offline push notification while the **phone is locked**, I click 'accept' to launch the app. 
But when I then click the **Recent Button** at the bottom of the phone, the app's **disappear**! However, the app is **still running**.
But, even though the app is still running in the background, the App is not visible.

I am currently using the latest version, but the problem still persists

https://github.com/hiennguyen92/flutter_callkit_incoming/assets/11307627/ae76cdc8-2def-4bca-8bd2-3f693aa13529

**Comment by yoer** [comment]
It seems like it's caused by the **startActivity** triggered by the AcceptClick function in CallkitIncomingActivity.kt.

**Comment by hiennguyen92** [comment]
https://github.com/hiennguyen92/flutter_callkit_incoming/blob/590d0396d48012f504b9f28d9d113ed7318d0531/android/src/main/AndroidManifest.xml#L18
I'm not sure what the problem, but you can try removing this line or set false. Please let me know the results once you try it.

**Comment by yoer** [comment]
after remove `excludeFromRecents`，`App disappear when click Recent Button` had **fixed**.

However, **new problems** have arisen.
it will launch **two identical apps** when clicking on the desktop app again.


https://github.com/hiennguyen92/flutter_callkit_incoming/assets/11307627/f230beb3-e2cb-41e3-877b-cd1606234999

**Comment by hiennguyen92** [comment]
@yoer please make sure set `android:launchMode="singleInstance"`
https://github.com/hiennguyen92/flutter_callkit_incoming/blob/590d0396d48012f504b9f28d9d113ed7318d0531/example/android/app/src/main/AndroidManifest.xml#L8

**Comment by yoer** [comment]
after chagne android:launchMode="singleInstance"，launch two identical apps  had fixed, but the callkit view does not disappear now

https://github.com/hiennguyen92/flutter_callkit_incoming/assets/11307627/18e87bb0-1b65-48c7-8041-5f3e2c3ad755

**Comment by hiennguyen92** [comment]
Can you can add again excludeFromRecents?

**Comment by yoer** [comment]
> @yoer please make sure set `android:launchMode="singleInstance"`
> 
> https://github.com/hiennguyen92/flutter_callkit_incoming/blob/590d0396d48012f504b9f28d9d113ed7318d0531/example/android/app/src/main/AndroidManifest.xml#L8

The final solution is this, just need set `android:launchMode="singleInstance"` in App Android Project

**Comment by yoer** [comment]
thanks a lot, awesome

**Comment by haninhn** [comment]
manifest   <activity
            android:name=".MainActivity"
            android:exported="true"
            android:noHistory="true"
            android:showWhenLocked="true"
            android:turnScreenOn="true"
            android:launchMode="singleTask"
            android:usesCleartextTraffic="true"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|
            smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">.     main:     `@pragma('vm:entry-point')
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  if (message.data.containsKey("callId")) {
    print("_firebaseMessagingBackgroundHandler ${message.data}");
    String callId = message.data["callId"];
    String conversationId = message.data["conversationId"];
    String userName = message.data["userName"];
    String userId = message.data["userId"];
    String userProfilePic = message.data["userProfilePic"];
   await CallKitService().showCallkitIncoming(const Uuid().v4(), userProfilePic, userName,  userId, callId,conversationId);
  }else{
    NotificationService().handleNotificationPayload(message.data);
  }
  // Retrieve the initial message if available
  RemoteMessage? initialMessage = await FirebaseMessaging.instance.getInitialMessage();
  if (initialMessage != null) {
    if (!message.data.containsKey("callId")) {
      NotificationService().handleNotificationPayload(initialMessage.data);
      final oldNotifCount = await NotificationsCountHandler.getNotificationsCount();
      await NotificationsCountHandler.updateNotificationsCount(oldNotifCount  + 1);

    }else{
      print("background");
      NavigationService.instance.pushNamedIfNotCurrent(AppRoute.callingPage,
          args: [
            message.data["callId"],
            message.data["conversationId"]
          ]);
    }


  }}
    // The following handler is called or click, when App is in the background.
  FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);

  RemoteMessage? initialMessage = await FirebaseMessaging.instance.getInitialMessage();
  if (initialMessage != null) {
    NotificationService().handleNotificationPayload(initialMessage.data);
  }

  FirebaseMessaging.onMessageOpenedApp.listen((RemoteMessage message) async {
    print("lanch from background");
    // Handle message opened when app is in background
    if (!message.data.containsKey("callId")) {
      NotificationService().handleNotificationPayload(message.data);
    }else{
      NavigationService.instance.pushNamedIfNotCurrent(AppRoute.callingPage,
          args: [
            "callId",
            "conversationId"
          ]);
    }

  });

  SystemChrome.setSystemUIOverlayStyle(const SystemUiOverlayStyle(statusBarColor: Colors.transparent));
  SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp])
      .then((_) {
    runApp(const MyApp());
  });
}

class MyApp extends StatefulWidget {

  const MyApp({super.key});

  @override
  _MyApp createState() => _MyApp();
}

class _MyApp extends State<MyApp> with WidgetsBindingObserver{
  String textEvents = "";

  @override
  void initState() {
    super.initState();

    WidgetsBinding.instance.addObserver(this);
    //CallKitService().getCurrentCall();
    //CallKitService().checkAndNavigationCallingPage();
   // Set up  CallKit listener for incoming CALL events
    CallKitService().listenerEvent(onEvent);
  } @override
  void dispose() {
    SocketManager.dispose();
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

  void onEvent(CallEvent event) {
    print("ebent is $event");
    if (!mounted) return;
    setState(() {
      textEvents += '${event.toString()}\n';
      print("ebent is $textEvents");

    });
  }.  call kit service import 'package:flutter_callkit_incoming/entities/android_params.dart';
import 'package:flutter_callkit_incoming/entities/call_kit_params.dart';
import 'package:flutter_callkit_incoming/entities/ios_params.dart';
import 'package:flutter_callkit_incoming/entities/notification_params.dart';
import 'package:flutter_callkit_incoming/flutter_callkit_incoming.dart';
import 'package:flutter_callkit_incoming/entities/call_event.dart';
import 'package:http/http.dart';
import 'AppRoute.dart';
import 'navigation_service.dart';

class CallKitService{
  Future<void> showCallkitIncoming(String uuid, String userProfilePic, String calledName,  String userId, String callId ,String conversationId) async {
    final params = CallKitParams(
      id: uuid,
      nameCaller: '$calledName calling you',
      appName: 'Callkit',
      avatar: userProfilePic,
      handle: '0123456789',
      type: 0,
      duration: 30000,
      textAccept: 'Answer',
      textDecline: 'Decline',
      missedCallNotification: const NotificationParams(
        showNotification: true,
        isShowCallback: false,
        subtitle: 'Missed call',
        callbackText: 'Call back',
      ),
      extra: <String, dynamic>{'name':calledName,'userId': userId, 'calledId': callId, 'conversationId':conversationId},
      headers: <String, dynamic>{'apiKey': 'Abc@123!', 'platform': 'flutter'},
      android: const AndroidParams(
          isCustomNotification: true,
          isShowLogo: false,
          ringtonePath: 'system_ringtone_default',
          backgroundColor: '#ffffff',
          backgroundUrl: 'assets/test.png',
          actionColor: '#4CAF50',
          textColor: '#000000',
          incomingCallNotificationChannelName: "Incoming call",
          missedCallNotificationChannelName: "Missed Call"

      ),
      ios: const IOSParams(
        iconName: 'CallKitLogo',
        handleType: 'generic',
        supportsVideo: true,
        maximumCallGroups: 2,
        maximumCallsPerCallGroup: 1,
        audioSessionMode: 'default',
        audioSessionActive: true,
        audioSessionPreferredSampleRate: 44100.0,
        audioSessionPreferredIOBufferDuration: 0.005,
        supportsDTMF: true,
        supportsHolding: true,
        supportsGrouping: false,
        supportsUngrouping: false,
        ringtonePath: 'system_ringtone_default',
      ),
    );
    await FlutterCallkitIncoming.showCallkitIncoming(params);
  }


  Future<dynamic> getCurrentCall() async {
    // Check current call from pushkit if possible
    var calls = await FlutterCallkitIncoming.activeCalls();
    print("getCurrentCall$calls");

    if (calls is List) {
      if (calls.isNotEmpty) {
        print('DATA: $calls');
        String _currentUuid = calls[0]['id']; // Declare _currentUuid as String
        return calls[0];
      } else {
        String _currentUuid = ""; // Declare _currentUuid as String
        return null;
      }
    }
  }


  Future<void> requestHttp(content) async {
      get(Uri.parse('https://webhook.site/2748bc41-8599-4093-b8ad-93fd328f1cd2?data=$content'));
    }

    Future<void> listenerEvent(void Function(CallEvent) callback) async {
      try {
        FlutterCallkitIncoming.onEvent.listen((event) async {
          print('HOME: $event');
          print('event! type: ${event!.event}');

          switch (event.event) {
            case Event.actionCallIncoming:
            // TODO: received an incoming call
            print("in incoming call");
              break;
            case Event.actionCallStart:
             // TODO: started an outgoing call
             // TODO: show screen calling in Flutter
              break;
            case Event.actionCallAccept:
              navigateToCallingPage(event.body);
             await FlutterCallkitIncoming.getDevicePushTokenVoIP();

             break;
            case Event.actionCallDecline:
            // TODO: declined an incoming call
              await requestHttp("ACTION_CALL_DECLINE_FROM_DART");
              break;
            case Event.actionCallEnded:
            // TODO: ended an incoming/outgoing call
              break;
            case Event.actionCallTimeout:
            // TODO: missed an incoming call
              break;
            case Event.actionCallCallback:
              print("call back");

              break;
            case Event.actionCallToggleHold:
            // TODO: only iOS
              break;
            case Event.actionCallToggleMute:
            // TODO: only iOS
              break;
            case Event.actionCallToggleDmtf:
            // TODO: only iOS
              break;
            case Event.actionCallToggleGroup:
            // TODO: only iOS
              break;
            case Event.actionCallToggleAudioSession:
            // TODO: only iOS
              break;
            case Event.actionDidUpdateDevicePushTokenVoip:
            // TODO: only iOS
              break;
            case Event.actionCallCustom:
              break;
          }
          print("actiiooooonnnnCaaaaalll");

          callback(event);
        });
      } on Exception catch (e) {
        print("Caaaaalll ui exceptionnnn $e");
      }
    }
  Future<void> navigateToCallingPage(Map<String, dynamic> callDetails) async {
      String callId = callDetails['extra']['calledId'];
      String conversationId = callDetails['extra']['conversationId'];
      if (callId.isNotEmpty) {
        {

          print("should navigate to call screeeen");
          NavigationService.instance.pushNamedIfNotCurrent(AppRoute.callingPage,
              args: [
                callId,
                conversationId
              ]);
        }
      } else {
        print("Unable to navigate to call screen. Missing userId or callId.");
      }
  }


  Future<void> checkAndNavigationCallingPage() async {
    // var currentCall = await getCurrentCall();
    // print("cheeekl$currentCall");

    // if (currentCall != null) {
    //   print("should navigate to call screeeen");
    //   print("on resumeeee");
    //   // NavigationService.instance.pushNamedIfNotCurrent(AppRoute.callingPage,
    //   //     args: [
    //   //       "Hamza",
    //   //       "657b35ac801d21a3f24076fe",
    //   //       "6561112e85af8ed4b0fde19f"
    //   //     ]);
    // }
  }

}

**Comment by hiennguyen92** [comment]
@haninhn i think, please make sure call endAllCall(); when app kill

**Comment by haninhn** [comment]
Okkk, I will trai  it now. plz dont go i need you

**Comment by haninhn** [comment]
i put this in main. `  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    if (state == AppLifecycleState.paused || state == AppLifecycleState.detached) {
      CallKitService().endAllCalls();
    }
  }.  and this in call kit service  
`  Future<void> endAllCalls() async {
    print("app killed");
    try {
      await FlutterCallkitIncoming.endAllCalls();
    } on PlatformException catch (e) {
      print('Failed to end all calls: ${e.message}');
    } 
  }`.    the function colled. but note worked  correctry in the resume state i get the last call again

**Comment by haninhn** [comment]
class _MyApp extends State<MyApp> with WidgetsBindingObserver{
  String textEvents = "";

  @override
  void initState() {
    super.initState();

    WidgetsBinding.instance.addObserver(this);
    //CallKitService().getCurrentCall();
    //CallKitService().checkAndNavigationCallingPage();
   // Set up  CallKit listener for incoming CALL events
    CallKitService().listenerEvent(onEvent);
  }
  @override
  void dispose() {
    SocketManager.dispose();
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }
  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    if (state == AppLifecycleState.paused || state == AppLifecycleState.detached) {
      CallKitService().endAllCalls();
    }
  }.      iput it in main but dont work correctly
