### ISSUE TITLE
［feature requirement］can add a configuration that does not display full screen when the Android lock screen.

### ISSUE THREAD

**Issue by yoer** [hiennguyen92/flutter_callkit_incoming#454]

**Comment by hiennguyen92** [comment]
please using 2.0.0+2, Add props `isShowFullLockedScreen` on Android props

**Comment by yoer** [comment]
Thanks a lot!!

**Comment by AhmadFalahian** [comment]
i have same issue but i can't find isShowFullLockedScreen

**Comment by sivavj** [comment]
> i have same issue but i can't find isShowFullLockedScreen

Future<void> _requestNotificationPermissions() async {
  PermissionStatus status = await Permission.notification.status;
  if (!status.isGranted || status.isDenied || status.isPermanentlyDenied) {
    await FlutterCallkitIncoming.requestFullIntentPermission();
  }
}

// Use this method to request fullscreen intent on the lock screen.
