### ISSUE TITLE
[ios] why i can't custom the call  ui in ios 

### ISSUE THREAD

**Issue by haninhn** [hiennguyen92/flutter_callkit_incoming#455]
why i can't custom the call  ui in ios

**Comment by hiennguyen92** [comment]
Call UI is Callkit provider by system iOS.

**Comment by haninhn** [comment]
Is this step necessary for iOS in my Flutter project, "Configure VoIP Push Notifications in the Xcode Project (Swift) in Setup Pushkit for IOS." @hiennguyen92 https://github.com/hiennguyen92/flutter_callkit_incoming/blob/master/PUSHKIT.md

**Comment by zionnite** [comment]
@hiennguyen92 
is there away to show my app after the user accepted the call from callkit screen??
i'm seriously in need of this solution now
