### ISSUE TITLE
I got this error on Android 

### ISSUE THREAD

**Issue by sokphengcheang** [hiennguyen92/flutter_callkit_incoming#458]
WHen press on incoming call notification and the the notification disappear but the ringtone still playing.
It happened sometimes

**Comment by sokphengcheang** [comment]
![Screenshot 2024-02-23 at 11 40 01](https://github.com/hiennguyen92/flutter_callkit_incoming/assets/27798903/b660a635-8fdb-4cf1-a403-3d5738088c19)

**Comment by sokphengcheang** [comment]
![Uploading Screenshot 2024-02-23 at 12.04.52.png…]()

**Comment by sokphengcheang** [comment]
![Screenshot 2024-02-23 at 12 04 52](https://github.com/hiennguyen92/flutter_callkit_incoming/assets/27798903/2a2d7320-e8fa-42bd-868b-9c0fd003df7b)

**Comment by hiennguyen92** [comment]
ok. let me check and upadte it

**Comment by sokphengcheang** [comment]
> ok. let me check and upadte it
Thanks you very much.

**Comment by hiennguyen92** [comment]
please using 2.0.0+2
