### ISSUE TITLE
Not showing in Android

### ISSUE THREAD

**Issue by dk-dsndr27** [hiennguyen92/flutter_callkit_incoming#466]
Hi @hiennguyen92 
On Android, do we need to add some code in native like iOS?

**Comment by Nazeer-Nageb** [comment]
@dk-dsndr27 
Did I work with you on ios?
If I worked with you on ios, contact me to share ideas, I worked with me on android, but it didn't work on ios

**Comment by dk-dsndr27** [comment]
@Nazeer-Nageb of course work properly

btw, how about terminate state on Android?

**Comment by Nazeer-Nageb** [comment]
@dk-dsndr27 
There is no code to add native in android 
Share your code with me to tell you what problem  
And tell me in ios how to use file Voip.pem

**Comment by dk-dsndr27** [comment]
@Nazeer-Nageb 
i'm only had with terminated state on Android
for iOS, you have to create with APNs notification, not with FCM

**Comment by Nazeer-Nageb** [comment]
@dk-dsndr27 
I'm use fcm in android  and 
I had no problem showing call  in func onbackground 
but in ios 
I didn't know how to use the Voip.pem file
Is there another way to receive and send a call, and how can I learn this method?

**Comment by dk-dsndr27** [comment]
I have problem on terminate state on Android
Background state and terminated state I think that a different think's bro @Nazeer-Nageb 

you have to set .pem/.p12 file in your backend, i think every frameworks have a different APNs documentation

**Comment by datpt11** [comment]
same android 14
