### ISSUE TITLE
Instant conversion of call notification to missed call

### ISSUE THREAD

**Issue by Usama9999** [hiennguyen92/flutter_callkit_incoming#47]
if the user on other side has declined the call. then at the same time there should be missed call notification on other side

**Comment by hiennguyen92** [comment]
if declined you should push back to the device(caller) here and end the current call.

**Comment by Usama9999** [comment]
> if declined you should push back to the device(caller) here and end the current call.

Is didn't understand. can you please explain it

**Comment by hiennguyen92** [comment]
@Usama9999 can you explain better the error you are getting?

**Comment by hiennguyen92** [comment]
if you need to show more miss call notification, you can use (v 1.0.1+5)
```
await FlutterCallkitIncoming.showMissCallNotification(params);
```
