### ISSUE TITLE
in version 2.0.2+2 Error: 'hideCallkitIncoming' is already declared in this scope.

### ISSUE THREAD

**Issue by cofirazak** [hiennguyen92/flutter_callkit_incoming#473]
Xcode build done.                                           52.3s
Failed to build iOS app
Could not build the precompiled application for the device.

`Error (Xcode): ../../.pub-cache/hosted/pub.dev/flutter_callkit_incoming-2.0.2+2/lib/flutter_callkit_incoming.dart:137:17: Error: 'hideCallkitIncoming' is already declared in this scope.`

Error running application on iPhone

<img width="1440" alt="Screenshot 2024-03-05 at 13 14 58" src="https://github.com/hiennguyen92/flutter_callkit_incoming/assets/2613578/8bae55eb-1eda-4f7a-96e4-58802ce3d194">
<img width="1440" alt="Screenshot 2024-03-05 at 13 15 11" src="https://github.com/hiennguyen92/flutter_callkit_incoming/assets/2613578/2537af03-59d6-490f-a426-2b3d8db50b4f">

**Comment by hiennguyen92** [comment]
sorry, please update 2.0.3.
