### ISSUE TITLE
How to stop ringing Iphone when remote ended 

### ISSUE THREAD

**Issue by NyamdavaaUrt** [hiennguyen92/flutter_callkit_incoming#474]
In IOS Native, one should use reportCall(with:endedAt:reason:) function to stop ringing. 

The problem is, I also have to handle this case on android phone, which means I need curl request like the following:

curl -v \
-d '{"aps":{"alert":"Hien Nguyen Call"},"id":"44d915e1-5ff4-4bed-bf13-c423048ec97a","nameCaller":"Hien Nguyen","handle":"0123456789","isVideo":true}' \
-H "apns-topic: com.hiennv.testing.voip" \
-H "apns-push-type: voip" \
--http2 \
--cert VOIP.pem:'<passphrase>' \
https://api.development.push.apple.com/3/device/<device token>

What payload should I use to reportcall ended

**Comment by afl-dev** [comment]
up
