### ISSUE TITLE
Not able to add padding to nameCaller

### ISSUE THREAD

**Issue by CloudIQTechnologies** [hiennguyen92/flutter_callkit_incoming#476]
when we click the call notification from notification bar, it navigate to full screen incoming call screen and showing the "nameCaller" without padding. how to add padding to the "nameCaller" ?
screenshot attached.
![Screenshot_1709710483](https://github.com/hiennguyen92/flutter_callkit_incoming/assets/130963789/8ee232c1-0c26-4ded-b3b9-ee6d68b44f05)

**Comment by hiennguyen92** [comment]
lib does not provide edit incoming screen. you can update it here in locally.
https://github.com/hiennguyen92/flutter_callkit_incoming/blob/5b8705cff267435025bd51ac5c7c85bb1afb1f24/android/src/main/res/layout/activity_callkit_incoming.xml#L63

**Comment by CloudIQTechnologies** [comment]
@hiennguyen92 Thanks, android:paddingLeft="20dp"
can you fix this issue in the next release ?

**Comment by hiennguyen92** [comment]
Ok. However, you can add it locally.
