### ISSUE TITLE
Background and terminated app accept call button not working 

### ISSUE THREAD

**Issue by karan-encanto** [hiennguyen92/flutter_callkit_incoming#482]
When the Accept button is clicked in background and terminated state, the data received in the push notification gets cleared.

**Comment by MrAzimzadeh** [comment]
Hello, How did you solve the problem?

**Comment by MrAzimzadeh** [comment]
> When the Accept button is clicked in background and terminated state, the data received in the push notification gets cleared.

Hello, How did you solve the problem?
