### ISSUE TITLE
IOS VOIP push Extra not being transfered

### ISSUE THREAD

**Issue by beebobox** [hiennguyen92/flutter_callkit_incoming#49]
Hi.
First of all. Thank you so much for this plugin. With the addition of the VOIP push functionality it is the perfect addition for my project :)

In my server backend, i populate the extra property like this:
```
Dictionary<String, string> Extra = new Dictionary<string, string>();
Extra.Add("USER_UID", "testUserUid");
Extra.Add("QUE_UID", "testQue");
Extra.Add("TOKEN", "Testtoken");

var push = new ApplePush(ApplePushType.Voip)
                .SendToDevelopmentServer()
                .AddVoipToken(VoipToken)
                .AddCustomProperty("alert", "testalert", true)
                .AddCustomProperty("id", Guid.NewGuid().ToString())
                .AddCustomProperty("nameCaller", "testcaller")
                .AddCustomProperty("handle", "12345")
                .AddCustomProperty("isVideo", true)
                .AddCustomProperty("extra", Extra);
```
But when the event ACTION_CALL_INCOMMING is triggered, the extra property is empty.
I have also tried with a Dictionary<String, Object>, but no avail.
Is this a bug, or am i using the extra property wrong?

br.
Jacob

**Comment by hiennguyen92** [comment]
Yes, let me update. I think I'll need a little update here
https://github.com/hiennguyen92/flutter_callkit_incoming/blob/c29e3d86b17d09121d1af324f553ecfdd49c9b5a/example/ios/Runner/AppDelegate.swift#L68

**Comment by beebobox** [comment]
Thanx :)
