### ISSUE TITLE
IOS VOIP push: where to initialize callevent listener so that it is called in terminated state

### ISSUE THREAD

**Issue by beebobox** [hiennguyen92/flutter_callkit_incoming#51]
Hi

Android:
When app is terminated: i place initialize the eventlistener inside the firebase background callback, and it works like a charm :)
When app is active or not in view: everything works fine 

IOS:
When the app is terminated.: the eventlistener is never called no matter where i place it,
When app is active or not in view: everything works fine

Is it possible to make a background initializer like the android firebase background callback, that is called when the app recieves the VOIP push notification, but before the callkit is displayed, so that the incommingcall events is fired?
or can i place the event initialization somewhere else?

br. Jacob

**Comment by hiennguyen92** [comment]
Please use onEvent in the app widget(root widget)

**Comment by hiennguyen92** [comment]
@beebobox you should listen for the event in the app widget. because when receiving VOIP app will automatically activate and will launch the first App widget

**Comment by beebobox** [comment]
Thanx for the feedback :)
I ended up solving it by placing it two different places to handle the terminated state.
on Android: Inside the onbackgroundMessage callback of Firebase messaging:
```

Future<void> _firebaseMessagingBackgroundHandler(firebase_msg.RemoteMessage message) async {
 await firebase_core.Firebase.initializeApp(options: firebase_options.DefaultFirebaseOptions.currentPlatform);
  print("Handling a background message: ${message.messageId}");
  **clShared.appManager.incommingCallListenerEvent();**
  clShared.appManager.processNotificationData(message.data, false);
} 
```

On IOS:  The console.app revealed that my root widget didnot get called on incoming call in terminated state, so i placed in just before:

  ```
**clShared.appManager.incommingCallListenerEvent();**
  runApp( MyApp());
```
br. Jacob
