### ISSUE TITLE
Android endAllCalls not removing incoming call

### ISSUE THREAD

**Issue by marcoberetta96** [hiennguyen92/flutter_callkit_incoming#52]
When there is an incoming call and I use `FlutterCallkitIncoming.endAllCalls()` I expect this to disappear.

![](https://user-images.githubusercontent.com/11749393/155419674-aa6848d7-5509-45c6-a988-337fe77b35da.png)

This does not happen on Android.
It works fine on iOS.

**Comment by kmoreau** [comment]
i have the same case.

FlutterCallkitIncoming.activeCalls()
activeCalls => []

**Comment by hiennguyen92** [comment]
Please check with version 1.0.1+3

**Comment by marcoberetta96** [comment]
I confirm this issue is solved

**Comment by kmoreau** [comment]
I confirm too, thx !
