### ISSUE TITLE
Full screen call in lockscreen

### ISSUE THREAD

**Issue by AhmadFalahian** [hiennguyen92/flutter_callkit_incoming#526]
I have written a code that shows the following screen when the android phone is locked and turned off, and when I unlock the phone it is full screen. How can I make the call to be full screen on the lock screen?
![photo_2024-05-03_18-07-35](https://github.com/hiennguyen92/flutter_callkit_incoming/assets/87113603/99c61fe0-cacf-495a-9fda-f6c0d85948c3)

**Comment by tgh1701** [comment]
Same issue

**Comment by hiennguyen92** [comment]
please update last version for request permisstion full intent screen for android 14+
please make sure call `requestFullIntentPermission `
