### ISSUE TITLE
In the debug build, the lock screen call is working, but in the release, especially on Samsung, its not working.

### ISSUE THREAD

**Issue by RahimaShapla** [hiennguyen92/flutter_callkit_incoming#527]
flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.6, on macOS 14.1.1 23B81 darwin-arm64, locale en-BD)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] IntelliJ IDEA Community Edition (version 2023.3.6)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!
```
I followed the GitHub example, and Firebase Messaging is working perfectly. I am receiving the notification, and the call is coming through, but it's not showing on the lock screen in the release build (in **samsung**). However, in the debug build, it's working as expected.

**Comment by RahimaShapla** [comment]
I had to manually allow permission from the settings. After that its working.

**Comment by fabiocody** [comment]
Could you post your settings? I'm still struggling with this issue

- OneUI 6.1
- flutter_callkit_incoming 2.0.4+1

Thank you
