### ISSUE TITLE
could not load PEM client certificate

### ISSUE THREAD

**Issue by AyaAdel283** [hiennguyen92/flutter_callkit_incoming#53]
Hello @hiennguyen92 , I got this error while sending notification using Curl 

`curl -v \                                                                                      58 ↵ sharaf@Ahmeds-MacBook-Pro
-d '{"aps":{"alert":"Hien Nguyen Call"},"id":"44d915e1-5ff4-4bed-bf13-c423048ec97a","nameCaller":"Hien Nguyen","handle":"0123456789","isVideo":true}' \
-H "apns-topic: com.morecreatives.qure.voip" \
-H "apns-push-type: voip" \
--http2 \
--cert VOIP.pem:'passphrase' \
https://api.development.push.apple.com/3/device/\59245fccb2bba096ac20e9ea28fb42948a8ecf555401a306f045f0142108fa89`
The pem file exists on desktop

**Comment by hiennguyen92** [comment]
please make sure you have the .pem file and passphrase.

**Comment by AyaAdel283** [comment]
Yes, It is OK now Thank you @hiennguyen92 . But unfortunately `extra` is always empty

**Comment by hiennguyen92** [comment]
For extra, i will update later

**Comment by AyaAdel283** [comment]
Ok, also we need to add avatar attribute

**Comment by hiennguyen92** [comment]
@AyaAdel283 If you use swift you can try like this

```
var info = [String: Any?]()
  info["id"] = "44d915e1-5ff4-4bed-bf13-c423048ec97a"
  info["nameCaller"] = "Hien Nguyen"
  info["handle"] = "0123456789"
  info["type"] = 1
  //.... avatar, extra...
SwiftFlutterCallkitIncomingPlugin.sharedInstance?.showCallkitIncoming(flutter_callkit_incoming.Data(args: info), fromPushKit: true)

```

**Comment by AyaAdel283** [comment]
It's OK now thanks @hiennguyen92
