### ISSUE TITLE
TelecomConnectionService, was not found in the project or the libraries ,

### ISSUE THREAD

**Issue by mansilogic** [hiennguyen92/flutter_callkit_incoming#534]
when i add in androidmanifest.xml this code of permission

 <service
            android:enabled="true"
            android:exported="true"
            android:name="com.hiennv.flutter_callkit_incoming.telecom.TelecomConnectionService"
            android:permission="android.permission.BIND_TELECOM_CONNECTION_SERVICE">
            <intent-filter>
                <action android:name="android.telecom.ConnectionService" />
            </intent-filter>
        </service>
        
 i got this error TelecomConnectionService, was not found in the project or the libraries

**Comment by hiennguyen92** [comment]
Please using new version.
