### ISSUE TITLE
In Android 14 the Incoming Call Screen does not appear when the screen is locked.

### ISSUE THREAD

**Issue by governedbyprudence** [hiennguyen92/flutter_callkit_incoming#544]
After updating to Android 14, I have encountered an issue where the incoming call screen does not appear when the screen is locked. This behavior is different from previous versions of Android, where the incoming call screen would be displayed regardless of the screen's lock state, allowing users to easily see and answer incoming calls.
Thank you in advance.

Edit: I have checked that this function does work on Android 14, but only in debug mode.

**Comment by JosephKalash** [comment]
even Android 13
previously it was working but unfortunately not anymore.

**Comment by JosephKalash** [comment]
the issue is with permission in (other permissions setting) called show on lock screen we should allow it

**Comment by governedbyprudence** [comment]
@JosephKalash Could you elaborate about the permission you are talking about ? I went to settings  for the app but did not find any such setting.

**Comment by fdeveloper786** [comment]
@JosephKalash It is not permission issue.It has been prevented from Android.User can't see this feature in full screen even it will be alarm as well. Below is the reference link.

[https://source.android.com/docs/core/permissions/fsi-limits#:~:text=To%20prevent%20ad%20spam%20and,provide%20calling%20and%20alarm%20functionalities]

**Comment by phamlinhk49kmt01** [comment]
i have the same problem. The device vibrates but does not display

**Comment by governedbyprudence** [comment]
Hi @fdeveloper786. I dont think it is disabled for android 14, as it is not mentioned anywhere in the documentation for full screen intents and because whatsapp is able to show a full intent notification when a call is incoming. I think there is some misconfiguration in code somewhere and it can be fixed. I am trying to find it myself :).

**Comment by JosephKalash** [comment]
I have app on store use call functionality, and the store asked that so he can enable it by default. but the issue for me is that permission.

**Comment by governedbyprudence** [comment]
@JosephKalash Yes. And what you said is correct. Xiaomi and Realme phones do not have that permission in settings.

**Comment by phamlinhk49kmt01** [comment]
> @JosephKalashĐúng. Và điều bạn nói là đúng. Điện thoại Xiaomi và Realme không có quyền đó trong cài đặt.

I have an error on samsung galaxy fold

**Comment by sunil-singh-chaudhary** [comment]
> @JosephKalash Yes. And what you said is correct. Xiaomi and Realme phones do not have that permission in settings.

hi what do you mean by permission in setting which permission is that can you please reply i got stuck on realme phone where no screen showing

**Comment by JosephKalash** [comment]
@sunil-singh-chaudhary if you go to the app settings > other permissions, you will find one permission called "shows in lock screen" you have to enable this one so the call can be shown in lock screen

**Comment by reduxdj** [comment]
I have a galaxy and this is not a permission problem, the issue for me is the lock screen shows correctly once, then all subsequent calls the lockscreen does not show.

**Comment by eduardothiesen** [comment]
Galaxy S23 with Android 14 not working as well

**Comment by dvolkovich** [comment]
Confirming bug, Samsung S22 / Android 14 not waking, lock screen notifications are allowed

**Comment by Farhathullah-Najeeb** [comment]
same issue , any update??

**Comment by Spyspyspy** [comment]
Same here, android 14. But in debug session it works, in release - not.

**Comment by Spyspyspy** [comment]
Found a solution, will provide a fix later. In my case the problem was, when device was locked and the call started, it ringed and made a vibration, but didn't to wake a screen. I think that I fixed itt.

**Comment by hiennguyen92** [comment]
please update last version for request permisstion full intent screen for android 14+
