### ISSUE TITLE
[iOS Release] Doesn't show incoming call in iOS while it in background mode in release mode but works in debug mode.

### ISSUE THREAD

**Issue by AmangeldiyevSultan** [hiennguyen92/flutter_callkit_incoming#554]
When I run my app via USB it work fine. Data come from websocket and after that I show incoming call if needed even if app in background mode
But after deploy my app to testflight it work only if Im in app, in foreground mode

**Comment by kevin4dhd** [comment]
Did you implement it with fcm? I'm using fcm and it doesn't work in testflight
