### ISSUE TITLE
full screen when incoming call in my device not showing full 

### ISSUE THREAD

**Issue by sunil-singh-chaudhary** [hiennguyen92/flutter_callkit_incoming#560]
hi i have implemented this lib 

working fine but what i see is in My MI phone it is not showing callscreen as fullscreen 
either locked or minimized only showing alert notification and in oneplus and honor phone working fine 

is we have to do anything extra to work it

**Comment by sunil-singh-chaudhary** [comment]
ok i have solve some issue on the above question 
1, added     android:launchMode="singleTask"
            android:showWhenLocked="true" 
then i dont need to unlock my phone it will open direactly 

but still finding about chat can i open or have an option in future to customized it not only for audio video but chat too 

one more thing is this library is free or not because i have an option for 
 headers: <String, dynamic>{'apiKey': 'Abc@123!', 'platform': 'flutter'}, 

hera why api key little confuse pls help

**Comment by sunil-singh-chaudhary** [comment]
for some one who didnt find above question answer pls add   isShowLogo: false, for removing callkit title

**Comment by DanielDiaz18** [comment]
I had the same issue. after request the fullScreenIntentPermission in the class AndroidFlutterNotificationsPlugin of the flutterLocalNotificationsPlugin now it works.

**Comment by hiennguyen92** [comment]
please update last version for request permisstion full intent screen for android 14+
