### ISSUE TITLE
iOS activeCalls response missing `accepted`

### ISSUE THREAD

**Issue by vasilich6107** [hiennguyen92/flutter_callkit_incoming#567]
There is no accepted bool for response from `activeCalls` method

android
<img width="455" alt="image" src="https://github.com/user-attachments/assets/6cef3593-90d7-4c98-b170-618029d09def">

iOS
<img width="373" alt="image" src="https://github.com/user-attachments/assets/007ec6c0-b1de-4900-a1d4-b8d50c17375d">

**Comment by hiennguyen92** [comment]
please check last version.
