### ISSUE TITLE
endcall not working in IOS

### ISSUE THREAD

**Issue by deepaksuthar23086** [hiennguyen92/flutter_callkit_incoming#572]
while accept call from background and trying to end call from  custom screen then endcall is not working and throwing following errors (IOS)
Error requesting transaction: Error Domain=com.apple.CallKit.error.requesttransaction Code=4 "(null)"

i am using this method to end call
   await FlutterCallkitIncoming.endCall(id);

**Comment by Y-tezda** [comment]
did you manage to fix this ?

**Comment by deepaksuthar23086** [comment]
it's working, I solved this issue

**Comment by anhkhoa1208py** [comment]
help me fix this issues, same uuid but Error requesting transaction: Error Domain=com.apple.CallKit.error.requesttransaction Code=4 "(null)"

**Comment by deepaksuthar23086** [comment]
There is a reason for the call end function not working. The uuid we are sending is wrong, Please take call details from activeCall() function. Get current call uuid from call details, After that pass it in uuid endcall() function and then see what is the result.

**Comment by anhkhoa1208py** [comment]
It works correctly on the first call, but on the second and subsequent calls, it always encounters an error. I tried using FlutterCallkitIncoming.endAllCalls();, but it still didn’t work.

**Comment by anhkhoa1208py** [comment]
it's working, I solved this issue. Because i use jitsit

**Comment by deepaksuthar23086** [comment]
wow, that good

**Comment by Dalziel83** [comment]
Hi @deepaksuthar23086, @anhkhoa1208py can you guys guide me how to fix it? 
Current my application still show Error Domain=com.apple.CallKit.error.requesttransaction Code=4 "(null)" 
i'm trying await FlutterCallkitIncoming.endCall(id); and endAllCall();
but two ways still throw this message
