### ISSUE TITLE
Build failed on simulator xcode 

### ISSUE THREAD

**Issue by kmoreau** [hiennguyen92/flutter_callkit_incoming#58]
Hello,

I would like to know why the library does not work when I run on an iOS simulator?
Is it possible that in this case, we abstract to be able to launch the project anyway? (even without the function activated) 

It's possible to update VALID_ARCHS on your project to not trigger this below issue ?

Xcode's output:
↳
    ld: framework not found flutter_callkit_incoming
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in parallel
    warning: None of the architectures in ARCHS (x86_64) are valid. Consider setting ARCHS to $(ARCHS_STANDARD) or updating it to include at least one value from VALID_ARCHS (arm64, arm64e, i386, x86_64) which is not in EXCLUDED_ARCHS (x86_64). (in target 'flutter_callkit_incoming' from project 'Pods')
    

In real devices, it's works :)

**Comment by hiennguyen92** [comment]
Callkit framework can only work on real device. (doesn't work with simulatar)
