### ISSUE TITLE
The app opens in a new thread.

### ISSUE THREAD

**Issue by sanjidbillah** [hiennguyen92/flutter_callkit_incoming#586]
When the app is already open, it opens a new thread, resulting in two threads running simultaneously. Additionally, when I receive a notification, it triggers multiple calls.

https://github.com/hiennguyen92/flutter_callkit_incoming/blob/fd7dd0d7fc748925b1d30f6152f98b70a7e81c1a/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/CallkitIncomingActivity.kt#L295-L300

**Comment by TheauLep** [comment]
Hello, is there any way to avoid multiple threads ?

**Comment by sanjidbillah** [comment]
Use this in your manifest :
`android:launchMode="singleInstance"`
