### ISSUE TITLE
Call notification is duplicated on android 

### ISSUE THREAD

**Issue by SayedShalan** [hiennguyen92/flutter_callkit_incoming#59]
When Am accepting or decline a call, it sends another call notification

**Comment by hiennguyen92** [comment]
please explain more. Do you have any video records or screenshots? it will help me a lot. thank

**Comment by SayedShalan** [comment]
https://user-images.githubusercontent.com/73942450/157719421-3ecc46f3-e35d-45a3-9179-dbbcd004c365.mp4

**Comment by SayedShalan** [comment]
Also am sure that the data message is coming only once on my `firebaseMessagingBackgroundHandler` and `onMessageReceived` for FCM.

`  static sendAndroidCallNotification(Map<String, dynamic> payload)async{
    if(payload['event'] == 'doctorCanceled') {
      var params = <String, dynamic>{'id': payload['notificationId']};
      await FlutterCallkitIncoming.endCall(params);
      return;
    }
    var params = <String, dynamic>{
      'id': payload['notificationId'],
      'nameCaller': payload['doctorName'],
      'appName': 'Qure - كيـور',
      'avatar': payload['avatar'] ?? 'https://i.pravatar.cc/100',
      'handle': payload['body'],
      'type': 1, // 0 for audio call - 1 for video call
      'duration': 40000,
      'extra': payload,
      'headers': <String, dynamic>{
        'apiKey': 'Abc@123!',
        'platform': 'flutter'
      },
      'android': <String, dynamic>{
        'isCustomNotification': true,
        'isShowLogo': false,
        'ringtonePath': 'system_ringtone_default',
        'backgroundColor': '#49357F',
        'background':  payload['avatar'] ?? 'https://i.pravatar.cc/500',
        'actionColor': '#4CAF50'
      }
    };
    FlutterCallkitIncoming.showCallkitIncoming(params);
  }`
  
  `// FCM background callback
Future<void> firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  await FirebaseHelper.init();
  /// Check if is Call Notification then send call (For android Only) *****************************
  if(message.data.containsKey(DeepLinkHandler.collectionKey) &&
      message.data[DeepLinkHandler.collectionKey] == Collections.reservationsCalls &&
      Platform.isAndroid) {
    // callkitCallbackStream.asBroadcastStream().firstWhere((element) => element?.name == CallEvent.ACTION_CALL_DECLINE).then((value){
    //   if(value == null) return;
    //   DeepLinkHandler.updateReservationCallStatus(value.body['extra']['id'] as String);
    // });
    CallKitAndroid.sendAndroidCallNotification(message.data);
    return;
  }
}`

**Comment by hiennguyen92** [comment]
```callkitCallbackStream.asBroadcastStream().firstWhere((element) => element?.name == CallEvent.ACTION_CALL_DECLINE).then((value){ // if(value == null) return; // DeepLinkHandler.updateReservationCallStatus(value.body['extra']['id'] as String); // }); CallKitAndroid.sendAndroidCallNotification(message.data); return; } }```
The problem may lie here. you should only show the notification here, not listen to the DECLINE event.

**Comment by SayedShalan** [comment]
If it is Ok with you. Please can you send me an android example that all cases (App terminated -> Reject and so on …) ?

**Comment by hiennguyen92** [comment]
Please check with version 1.0.1+3

Example using FCM: https://github.com/hiennguyen92/flutter_callkit_incoming/blob/master/example/lib/main.dart

**Comment by SayedShalan** [comment]
The duplication still exists

**Comment by hiennguyen92** [comment]
You should check with my example. It works without duplicate.

**Comment by hiennguyen92** [comment]
This problem may be related to Xiaomi MIUI launcher

**Comment by niteshneupane** [comment]
> This problem may be related to Xiaomi MIUI launcher

This issue still exists on other OEM (Samsung).
