### ISSUE TITLE
:flutter_callkit_incoming         Suggestion: add 'tools:replace="android:exported"' to <receiver> element at AndroidManifest.xml:38:9-49:20 to override.

### ISSUE THREAD

**Issue by Anuj01111** [hiennguyen92/flutter_callkit_incoming#594]
/Users/apple/Downloads/Godiets android/android/app/src/debug/AndroidManifest.xml:41:13-36 Error:
        Attribute receiver#com.hiennv.flutter_callkit_incoming.CallkitIncomingBroadcastReceiver@exported value=(true) from [:flutter_callkit_incoming] AndroidManifest.xml:41:13-36
        is also present at [:flutter_callkit_incoming_yoer] AndroidManifest.xml:41:13-37 value=(false).
        Suggestion: add 'tools:replace="android:exported"' to <receiver> element at AndroidManifest.xml:38:9-49:20 to override.

**Comment by hiennguyen92** [comment]
please make sure using only this package(not using flutter_callkit_incoming_yoer)
