### ISSUE TITLE
Navigate to my callscreen

### ISSUE THREAD

**Issue by morfair** [hiennguyen92/flutter_callkit_incoming#6]
What rigth way to navigate to my callscreen page when app is in terminated state? ACTION_CALL_ACCEPT fired before the application starts.

**Comment by hiennguyen92** [comment]
you can show it via PushKit(pushRegistry...iOS) and push notification(Firebase....Android)

**Comment by morfair** [comment]
@hiennguyen92 
For this user should tap (click) on Push Notification for some firebase_messaging callback fired. But user tab on Answer button, no firebase_messaging fired (like FirebaseMessaging.onMessage)

**Comment by hiennguyen92** [comment]
For iOS, voip push service is required to run when the app terminates. also for android it will work fine with FCM

**Comment by morfair** [comment]
Ok, I think I will check `FlutterCallkitIncoming.activeCalls()` length on my SplashscreenPage, and if it `> 0` then navigate to CallscreenPage.
Otherwise `await FirebaseMessaging.instance.getInitialMessage()` returns `null` because I do not tap notification on Android's top bar, but tap Answer.

**Comment by hiennguyen92** [comment]
@morfair for firebase i think you can use FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler)which will call func `...plugin.showIncomingCallkit`

**Comment by morfair** [comment]
@hiennguyen92 
Yes, I do that!
And I see your plugin's screen with Answer/Reject buttons. But when I tap Answer button, my app starting with HomePage. I have not any data for check and redirect to CallscreenPage. Even `FlutterCallkitIncoming.activeCalls()` returns `[]` after app cold start (from terminated state).

**Comment by hiennguyen92** [comment]
@morfair thanks. i will update it. i got issue.

**Comment by hiennguyen92** [comment]
@morfair please using `FlutterCallkitIncoming.activeCalls()` (v1.0.0+6)

**Comment by anusha-chromosis** [comment]
when app in terminated stater, we are showing showIncoming callkit from firebase background  handler, on accept and reject of the how can we things works, because event listners does not work.
