### ISSUE TITLE
iconName not display 

### ISSUE THREAD

**Issue by kmoreau** [hiennguyen92/flutter_callkit_incoming#60]
Hello,

I put my iconName 'AppIcon' and i have only a white square :/ 
In your demo app, no icon is display too.

Need additional settings ? 
My iOS side contains Runner (with AppDelegate) /NSE/ShareExtension

**Comment by hiennguyen92** [comment]
@kmoreau should it be `Images.xcassets/CallKit Logo` from `Images.xcassets` 

https://github.com/hiennguyen92/flutter_callkit_incoming/tree/master/example/ios/Runner/Images.xcassets

**Comment by kmoreau** [comment]
I try 'AppIcon' & 'Assets.xcassets/AppIcon' in my case but it's doesn't work :/

**Comment by kmoreau** [comment]
Hello,

I try to update my 'Assets.xcassets' but not work.
I created new 'Images.xcassets' with Logo inside but i have 'three dots' icon instead of my icon (before I had nothing (vacuum) so there is better !)

details screenshot : 
![IMG_0027](https://user-images.githubusercontent.com/3499154/158162506-f439700a-aa1e-4e6e-8032-5d7ff072ebcc.jpg)
<img width="183" alt="Capture d’écran 2022-03-14 à 12 18 50" src="https://user-images.githubusercontent.com/3499154/158162512-718a9e9a-27ec-4361-a1a0-21287bb41212.png">
<img width="495" alt="Capture d’écran 2022-03-14 à 12 18 33" src="https://user-images.githubusercontent.com/3499154/158162514-300d90d5-f26a-4ecb-88b7-f8a22b3a0caf.png">
<img width="654" alt="Capture d’écran 2022-03-14 à 12 18 02" src="https://user-images.githubusercontent.com/3499154/158162515-58c72d16-47ac-48b0-a9b5-f121b30f2438.png">
