### ISSUE TITLE
Execution failed for task ':flutter_callkit_incoming:compileReleaseKotlin'.

### ISSUE THREAD

**Issue by Asmitta-01** [hiennguyen92/flutter_callkit_incoming#606]
I have updated my project (new feature) and now i'm getting this error:
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_callkit_incoming:compileReleaseKotlin'.
> 'compileReleaseJavaWithJavac' task (current target is 1.8) and 'compileReleaseKotlin' task (current target is 17) jvm target compatibility should be set to the same Java version.
  Consider using JVM toolchain: https://kotl.in/gradle/jvm/toolchain


* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 27s
Running Gradle task 'assembleRelease'...                           28,6s
Gradle task assembleRelease failed with exit code 1
```
I understand i should maybe downgrade but i can't, to stay with the new flutter features i need to be up to date. Is there a way to fix this please ? 
I found this: https://stackoverflow.com/questions/77317993/compiledebugjavawithjavac-task-current-target-is-1-8-and-compiledebugkotlin, but it is not working.

**Comment by Asmitta-01** [comment]
Anybody have a suggestion please ?

**Comment by Asmitta-01** [comment]
I found a workaround.
Update the build.gradle of the package, file location: `C:\Users\xxx\AppData\Local\Pub\Cache\hosted\pub.dec\[package_name]\android\build.gradle` with 
```gradle
android {
   ...

   // Add these ---------------

   compileOptions {
       sourceCompatibility JavaVersion.VERSION_17
       targetCompatibility JavaVersion.VERSION_17
   }

   kotlinOptions {
       jvmTarget = '17'
   }
   
   // ----------------
}
```

**Comment by yoer** [comment]
> I found a workaround. Update the build.gradle of the package, file location: `C:\Users\xxx\AppData\Local\Pub\Cache\hosted\pub.dec\[package_name]\android\build.gradle` with
> 
> ```groovy-gradle
> android {
>    ...
> 
>    // Add these ---------------
> 
>    compileOptions {
>        sourceCompatibility JavaVersion.VERSION_17
>        targetCompatibility JavaVersion.VERSION_17
>    }
> 
>    kotlinOptions {
>        jvmTarget = '17'
>    }
>    
>    // ----------------
> }
> ```

@hiennguyen92 

Please help to fix it. 

This brother’s method solved the problem of error reporting.
