### ISSUE TITLE
(Question) What is the best way to handle incoming when app terminated.

### ISSUE THREAD

**Issue by sokpheng** [hiennguyen92/flutter_callkit_incoming#62]
Hi sorry for this dumb question, but I currently I'm using FCM onBackgroundMessage to handle both background and terminated state. Is there a method that executes once only when the application first starts beside onBackgroundMessage?

**Comment by hiennguyen92** [comment]
Android, you can use FCM.
iOS, you must set up VoIP

**Comment by sokpheng** [comment]
I have setup VoIP following your instruction. And then call 
          await FlutterCallkitIncoming.showCallkitIncoming(params);
inside onBackgroundMessageHandler FCM as android ?

**Comment by hiennguyen92** [comment]
FCM using for Android only.
ussing Push VoIP for IOS

**Comment by hiennguyen92** [comment]
using terminal send Push VoIP:

```
curl -v \
-d '{"aps":{"alert":"Hien Nguyen Call"},"id":"44d915e1-5ff4-4bed-bf13-c423048ec97a","nameCaller":"Hien Nguyen","handle":"0123456789","isVideo":true}' \
-H "apns-topic: com.hiennv.testing.voip" \
-H "apns-push-type: voip" \
--http2 \
--cert VOIP.pem:'<passphrase>' \
https://api.development.push.apple.com/3/device/<device token>
```

**Comment by sokpheng** [comment]
Understand Thankyou.

**Comment by phuchuynh81qn** [comment]
@hiennguyen92  have an error when using fcm to show fake calls when the app is in the terminal but when opening the app the second time it still goes to the call listening screen.
I checked the error and it seems that getCurrentCall is not cleared after shutting down the app, the activeCall function always returns a value and I can't navigate it. Is there any way that when shutting down the app, you can clear the previous call in FlutterCallkitIncoming.activeCalls()? on Android?
