### ISSUE TITLE
VOIP sometime not working. (IOS only)

### ISSUE THREAD

**Issue by sokpheng** [hiennguyen92/flutter_callkit_incoming#63]
- When I deleted the app and re-install it did not work.
- Sometimes it work and I uploaded it to Testflight, after downloading from Testflight it did not work again.

**Comment by hiennguyen92** [comment]
this is beyond the scope of this package. however, you should make sure to push voip to the correct device token. because when you reinstall device token will change. device token will be different between testflight and local test (may need to switch using sandbox mode to production mode)

**Comment by sokpheng** [comment]
Mostly I build from VSCode it works fine, however, if I build in Xcode it does not work isn't related to cache issues?

**Comment by marcoberetta96** [comment]
@sokpheng did you find what the problem was?
I cannot use VOIP with Testflight.
Already using a production certificate.

**Comment by SagarDhiman018** [comment]
Hi there. it is providing the development token constantly not production. please help.
