### ISSUE TITLE
I try to navigate to callScreen but it not working

### ISSUE THREAD

**Issue by sokpheng** [hiennguyen92/flutter_callkit_incoming#64]
here is the error Unhandled Exception: You are trying to use contextless navigation without a GetMaterialApp or Get.key.

I handle from FCM onBackgroundMessageHandler.

![Screen Shot 2022-03-15 at 11 01 54 AM](https://user-images.githubusercontent.com/27798903/158303878-c5fcd9f2-92ba-4791-a962-90973dcaf73b.png)

![Screen Shot 2022-03-15 at 11 03 06 AM](https://user-images.githubusercontent.com/27798903/158304014-f72c6522-4f97-44c7-9b55-c0dd0f0a20ed.png)

![2022-03-15 10 58 41](https://user-images.githubusercontent.com/27798903/158303721-f1977a1b-8238-4839-a2c2-4df762fe65a8.jpg)

**Comment by hiennguyen92** [comment]
Could you be more specific about the problem you're having?

**Comment by hiennguyen92** [comment]
@sokpheng you should learn more about getx, I don't have much experience with it.

**Comment by sokpheng** [comment]
I wonder if I'm using your package in the correct place because every time the notification alert I can't make navigation, as in the image above.

**Comment by faisalmushtaq007** [comment]
@hiennguyen92 @sokpheng I am having same issue, i need help
When app is in background and i accept the call, it doesnt navigate to screen.

**Comment by sokpheng** [comment]
I'm doing something like this from navigatorKey.
  Navigator.of(navigatorKey.currentState!.context).push(
              MaterialPageRoute(
                builder: (context) => CallScreen(
               
                ),
              ),
            );

**Comment by sokpheng** [comment]
I'm doing like this. Navigator.of(navigatorKey.currentState!.context).push(MaterialRoute here).

**Comment by hiennguyen92** [comment]
@faisalmushtaq007 i think you need navigation to calling screen here(because when the event is called the App widget has not been rendered yet. so it might not be possible to natigation to the new page.)
https://github.com/hiennguyen92/flutter_callkit_incoming/blob/9bd849d2a8c82cf1f79e9fc0d3f8dc11dec5e282/example/lib/main.dart#L138

(update example)

**Comment by hiennguyen92** [comment]
I just updated version 1.0.1+7 please check example

**Comment by zionnite** [comment]
am still facing similar challenges despise the fact that am using version 1.0.1+7

anyone able to resolve this?
