### ISSUE TITLE
endCall()/endCalls() trigger DECLINE event on iOS

### ISSUE THREAD

**Issue by ozalisky** [hiennguyen92/flutter_callkit_incoming#65]
Package version 1.0.1+3

**Comment by hiennguyen92** [comment]
if the call has accepted/answer, endcalls will return ENDED
If the call is not accepted, it will return DECLINE at endcalls

**Comment by ozalisky** [comment]
Thank you for your response.

I'm using `flutter_callkit_incoming` just to show incoming call notification. After user accepts the call - app calls `FlutterCallkitIncoming.endAllCalls()` method to hide everything.  

Maybe it's possible to add another method or optional parameter not to trigger DECLINE event?

**Comment by hiennguyen92** [comment]
you can listen for ENDED and DECLICE with the same codebase.

**Comment by hiennguyen92** [comment]
Or you can use FlutterCallkitIncoming.endCall(params) , then you can add more params with props ```extra``` then you can check it with listener to see if it is correct

**Comment by hiennguyen92** [comment]
Or you can fork and then fix the line
https://github.com/hiennguyen92/flutter_callkit_incoming/blob/222a550cc558f908a5a28f55b783f092d4cc8ce3/ios/Classes/SwiftFlutterCallkitIncomingPlugin.swift#L394
DECLINE ->ENDED

**Comment by ozalisky** [comment]
Thank you.

**Comment by AAkira** [comment]
I don't think it is appropriate to call `ACTION_CALL_DECLINE` in `FlutterCallkitIncoming.endAllCalls()` event.
