### ISSUE TITLE
App Name not modified

### ISSUE THREAD

**Issue by ljsharp** [hiennguyen92/flutter_callkit_incoming#68]
I modified default app name to my desired name but it is not updated. 
Code is shown below.
   ```
var params = <String, dynamic>{
      'id': _currentUuid,
      'nameCaller': widget.user.name!,
      'handle': widget.user.completeNumber,
      'appName': 'Welcome to VWChat',
      'type': 1,
      'extra': {
        "receiverName": user.name!,
        "receiver": user.completeNumber!,
        "receiverImage": user.imageUrl ?? "user.png",
        "receiverIsoCode": user.isoCode,
        "receiverNumber": user.number,
        "senderName": widget.user.name!,
        "sender": widget.user.completeNumber!,
        "senderImage": widget.user.imageUrl!,
      },
      'ios': <String, dynamic>{'handleType': 'number'}
    };
```
What should I do?

**Comment by hiennguyen92** [comment]
@ljsharp for iOS > 14 Apple removed it (default is App name will be used)

**Comment by abhinandan-chakraborty** [comment]
@hiennguyen92 unfortunately, this issue still happening in android (full screen) on top it's always showing "CallKit" instead of the app name.

**Comment by sunil-singh-chaudhary** [comment]
did you find any solution to replace it with our appname pls reply

**Comment by sunil-singh-chaudhary** [comment]
did you find any solution to replace it with our appname pls reply

**Comment by hiennguyen92** [comment]
@sunil-singh-chaudhary you can hide it with isShowLogo: false,
or you may need to change this image in source code https://github.com/hiennguyen92/flutter_callkit_incoming/blob/master/android/src/main/res/drawable-xxxhdpi/ic_logo.png
I will try to add a properties for it in the next version.
