### ISSUE TITLE
The both incoming call screen and push notification are displayed

### ISSUE THREAD

**Issue by mdusko** [hiennguyen92/flutter_callkit_incoming#70]
Hello

I use your example...
When the application is terminated or running in the background, when I send an FCM notification, the both incoming call screen and push notification are displayed.
It's a mistake or I use it wrong? Thanks

Tested on Android 12 and Android 10

https://user-images.githubusercontent.com/65610208/159960629-da2222fa-5b84-4470-9b61-d08291fcd496.mov

**Comment by hiennguyen92** [comment]
please make sure send push notification only data(without notification).

**Comment by mdusko** [comment]
Thanks for the answer and clarification/explanation.

**Comment by obitodarky** [comment]
> please make sure send push notification only data(without notification).

I didn't understand this, where am I supposed to avoid sending notification and instead just send data? 
I'm getting the same issue

**Comment by hiennguyen92** [comment]
@obitodarky https://stackoverflow.com/questions/37966544/how-to-disable-showing-notification-when-it-it-comes-to-the-system-tray

can only send push notification without props "notification" from API(not dashboard)

**Comment by lamdev99** [comment]
@hiennguyen92 
Your comment is so appreciate, it helps me solve my issue which took me 2 days of investigation 🙇
