### ISSUE TITLE
The phone does not stop ringing after "decline" all incoming calls

### ISSUE THREAD

**Issue by mdusko** [hiennguyen92/flutter_callkit_incoming#71]
Hello,
If I receive multiple FCM messages, and for example, I "Decline" all calls, the phone still rings (until I close the app). 
Tested on Android 12 and Android 10.

https://user-images.githubusercontent.com/65610208/159968358-d62d5e19-23be-4960-8e5f-fa9aca9ca93a.mov

**Comment by Altereyo** [comment]
Having the same issue, did you resolve this?

**Comment by hiennguyen92** [comment]
ok. let me check

**Comment by simbik** [comment]
@hiennguyen92 Are you checked?) Have same problem.

**Comment by hiennguyen92** [comment]
@simbik @Altereyo @mdusko I just updated version 1.0.1+6, this issue has been fixed.

**Comment by simbik** [comment]
@hiennguyen92 Thank you =)

**Comment by mdusko** [comment]
@hiennguyen92 Thank you, I'll test and if there are any problems, I'll let you know.
