### ISSUE TITLE
(Question) Custom action when user press "Decline" button? 

### ISSUE THREAD

**Issue by mdusko** [hiennguyen92/flutter_callkit_incoming#72]
Is it possible to start the app (if the app is terminated) or focus the app in the foreground (if the app is in the background) when the user clicks the "Decline" button?

For example, if the user "Decline" the call, I need to start the app and allow the user to add the reason why the call was rejected?

Thank you for your help

**Comment by hiennguyen92** [comment]
@mdusko that's possible for Android. however, the iOS Callkit framework doesn't allow to open the app when in decline. so I can't add it. you will still get the event when you decline

**Comment by mdusko** [comment]
Thanks for the answer and clarification/explanation.
