### ISSUE TITLE
Launch app after accepting the call if app is terminated or in background ? IOS

### ISSUE THREAD

**Issue by SayedShalan** [hiennguyen92/flutter_callkit_incoming#75]
Please I need your help, Sometimes when I accept call from terminated or background state it isn't launch the app ? The uuid is unique for each call.

**Comment by SayedShalan** [comment]
It occurred on IOS not android. The app doesn't launch after accepting the call .

**Comment by hiennguyen92** [comment]
@SayedShalan you must use push VoIP for the app to be active when receiving push VoIP
https://github.com/hiennguyen92/flutter_callkit_incoming/blob/master/PUSHKIT.md

**Comment by faisalmushtaq007** [comment]
@SayedShalan i am having the same issue, i am checking on android device and when i accept the call, it doesnt navigate. Please help

**Comment by hiennguyen92** [comment]
@faisalmushtaq007 I will deploy version fix it tonight

**Comment by faisalmushtaq007** [comment]
@hiennguyen92 Thankyou sir, it means a lot. I am very much stressed because of this

**Comment by hiennguyen92** [comment]
@faisalmushtaq007 I just updated version 1.0.1+6, this issue has been fixed.

**Comment by SayedShalan** [comment]
This Fix is on android or IOS or both ?

**Comment by hiennguyen92** [comment]
@SayedShalan for iOS using Callkit framework, using Callkit's flow. The app automatically activates when receiving Push VoIP. All call screens will use Callkit's. 
-only Audio: Only using Calkit screen.(locked screen -> accept -> passcode input -> Callkit screen)
-Video -> Only using Calkit screen(iOS <=13).(locked screen -> accept -> passcode input -> Callkit screen). Open app when unlock passcode(iOS > 13).(locked sceen -> accept -> passcode input -> auto open app)

**Comment by SayedShalan** [comment]
OK

**Comment by brijeshbodariya** [comment]
@hiennguyen92 when i have using IOS version 16 and call receive in terminate state app not open.
