### ISSUE TITLE
IOS active call give only id

### ISSUE THREAD

**Issue by sadaqatdev** [hiennguyen92/flutter_callkit_incoming#76]
How we are process the call in ios only it give [{id: 1D52A94F-28B2-4E7B-9263-2E8C9120C74B}] this no extra data we are getting?

**Comment by marcoberetta96** [comment]
I have the same problem.
It happens only when the app is launched from background by tapping on the call notification.
The method `FlutterCallkitIncoming.activeCalls()` correctly gives the call, but only the ID is provided.
All other information passed to `showCallkitIncoming` seems to be lost.

**Comment by hiennguyen92** [comment]
@marcoberetta96 I just updated version 1.0.1+6, this issue has been fixed.

**Comment by sadaqatdev** [comment]
working thank you
