### ISSUE TITLE
Navigate to a specific screen after accepting the call if app is terminated or in background ? Android

### ISSUE THREAD

**Issue by faisalmushtaq007** [hiennguyen92/flutter_callkit_incoming#78]
I am not able to navigate to any screen. Also there's isnt any good example where you have used navigation as well

**Comment by hiennguyen92** [comment]
I just updated version 1.0.1+6, this issue has been fixed.
when accepted, auto open app. using event `ACTION_CALL_ACCEPT` for navigation to ...

**Comment by faisalmushtaq007** [comment]
@hiennguyen92 Can you please add a new screen to your example and the navigate to it. Please

**Comment by faisalmushtaq007** [comment]
@hiennguyen92 Sir i am getting null on context when i navigate to a specific screen
 case CallEvent.ACTION_CALL_ACCEPT:
          // TODO: accepted an incoming call
          // TODO: show screen calling in Flutter
          log("show screen calling in Flutter");
          log(message.data.toString()); 
         
        Navigator.push(
            navigatorKey.currentContext!, // getting null here!
            MaterialPageRoute(
                builder: (context) => VideoCallScreen(
                      agoraToken: message.data['body'],
                    )));
          break;

**Comment by hiennguyen92** [comment]
I think you can use as suggested in the link below. should use navigation without context

https://stackoverflow.com/questions/52962112/how-to-navigate-without-context-in-flutter-app

**Comment by hieplee2997** [comment]
@hiennguyen92 there is still one more error. if I click "Declined" button in fullscreen notification, application will be killed, in android
Can you check this error? Thank you

**Comment by hiennguyen92** [comment]
@hieplee2997 decline event, the app won't open.

**Comment by hiennguyen92** [comment]
@faisalmushtaq007 i think you need navigation to calling screen here(because when the event is called the App widget has not been rendered yet. so it might not be possible to natigation to the new page.)

https://github.com/hiennguyen92/flutter_callkit_incoming/blob/9bd849d2a8c82cf1f79e9fc0d3f8dc11dec5e282/example/lib/main.dart#L138

**Comment by hieplee2997** [comment]
> @hieplee2997 decline event, the app won't open.

but at that moment, my app is openning

**Comment by faisalmushtaq007** [comment]
navigation doesnt work in release mode of app, in debug its working fine. Please take a look

**Comment by hiennguyen92** [comment]
i think you can try turning off
-minifyenabled false
-shrinkResources false
-proguard

**Comment by hiennguyen92** [comment]
I just updated version 1.0.1+7 please try again.

**Comment by hiennguyen92** [comment]
you can try new version 1.0.2

**Comment by zionnite** [comment]
@hiennguyen92 , what I discover about this is that, during the terminated state or lock state, the `ACTION_CALL_ACCEPT` and `ACTION_CALL_ENDED` are never triggered.

the End Call will dismiss the incoming call notification
the Accept call will relaunch the app without triggering the `ACTION_CALL_ACCEPT`

**Comment by vertiria** [comment]
> @hiennguyen92 , what I discover about this is that, during the terminated state or lock state, the `ACTION_CALL_ACCEPT` and `ACTION_CALL_ENDED` are never triggered.
> 
> the End Call will dismiss the incoming call notification the Accept call will relaunch the app without triggering the `ACTION_CALL_ACCEPT`

I also struggle with this issue. Any workaround?

**Comment by CHA7R1K** [comment]
> > @hiennguyen92 , what I discover about this is that, during the terminated state or lock state, the `ACTION_CALL_ACCEPT` and `ACTION_CALL_ENDED` are never triggered.
> > the End Call will dismiss the incoming call notification the Accept call will relaunch the app without triggering the `ACTION_CALL_ACCEPT`
> 
> I also struggle with this issue. Any workaround?

I end up following #51 and it solve an issue. :)
