### ISSUE TITLE
Calling endCall() doesn't end a call on iOS

### ISSUE THREAD

**Issue by ozalisky** [hiennguyen92/flutter_callkit_incoming#79]
Calling `FlutterCallkitIncoming.endCall()` doesn't end a callKIt call. The green line at the top of the screen is present.

package version `1.0.1+5` & `1.0.1+6`

endAllCalls() works well.

**Comment by hiennguyen92** [comment]
ok. let me check

**Comment by hiennguyen92** [comment]
please make sure same id call(uuid)

**Comment by suhail600** [comment]
> please make sure same id call(uuid)

@hiennguyen92 call aslo not ends in android in profile mode , but ends in debug mode , in profile mode the currentuUid turns null , please fix this please , in debug mode its working .

and another thing to your note ,
black screen issue and relaunch app in debug mode , but its working in profile mode , please fix these bugs

**Comment by zionnite** [comment]
try the new package version 1.0.2, its fixed on the current package
