### ISSUE TITLE
How to hide callkitIncoming?

### ISSUE THREAD

**Issue by morfair** [hiennguyen92/flutter_callkit_incoming#8]
When an incoming call comes, I call `FlutterCallkitIncoming.showCallkitIncoming()`. But if remote side cancels the call, how can I hide the callkitIncoming? Maybe need `FlutterCallkitIncoming.hideCallkitIncoming()`?

**Comment by hiennguyen92** [comment]
Hi @morfair 

I just fixed it at version 1.0.0+5
please using `FlutterCallkitIncoming.endCall(...)` or `FlutterCallkitIncoming.endAllCalls()`
