### ISSUE TITLE
Need to add extra data in callkit

### ISSUE THREAD

**Issue by Edman-99** [hiennguyen92/flutter_callkit_incoming#80]
I need pass call extra data to my IOS device by apn callkit. But idk where add.

**Comment by Edman-99** [comment]
ps. Sorry for my english

**Comment by hiennguyen92** [comment]
Hi @Edman-99 
https://github.com/hiennguyen92/flutter_callkit_incoming/blob/e09b5cfeb3b23d33a757dcd0d2f0cb397b207dbe/example/ios/Runner/AppDelegate.swift#L68

data.extra = .....

**Comment by Edman-99** [comment]
@hiennguyen92 ok thanks, what about Android how i can make with terminate state in Android can you have example how to connect ?
