### ISSUE TITLE
what is the right Package Logic (flutter callkit incoming)

### ISSUE THREAD

**Issue by zionnite** [hiennguyen92/flutter_callkit_incoming#81]
Hello sir,

> your package is one of the best and most updated and most promising packages.

however, I have some issues on my end, my issue is about getting the right understanding of how am to effectively use your awesome package.

**This is what I want to achieve**
I want my user to be able to call another user;
when the app is in the background or killed, the app should be brought to the foreground

**What I don't quite understand are the following**

1. in my app, I have the user fetched from an API, how do I send a notification from my app to fcm?
2. in your example code while did you pass a null value to `ListenerEvent(null)`

```
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  print("Handling a background message: ${message.messageId}");
  listenerEvent(null);
  showCallkitIncoming(Uuid().v4()); //'5c3ab1f0-8750-42eb-8d29-ad28e3d7f336');
}
```
3. How is iOS supposed to listen to an Incoming call from firebase fcm

please point me in the right direction, am actually learning.

Thank you  @hiennguyen92  for everything you are doing!

**Comment by zionnite** [comment]
so in this case how do we send notifications to the respective device, iOS and android alike?

**Comment by ycherniavskyi** [comment]
@zionnite, you definitely miss some points about push notifications and their use cases. You can't send them directly from one phone to another. Push notifications are sent from the server your phone is connected via some signaling protocol.

**Comment by zionnite** [comment]
@hiennguyen92 @ycherniavskyi 

Thanks so much for ur reply.

Now I understand what I will do now.

I was very skeptic because I don't know how to work with firebase, this is actually my first time to use them.

So what I intend to now is to use firebase cloud function, at least I understand restAPI and how to use it on the server side.

From the nodejs server side send a push notifications to the respective device.

Use FCM to push to Android, while I Use VoIP to push to iOS (thanks @hiennguyen92  for this).



I understand how the client side will listen on Android but for iOS not so much sure.


Anyway, thank you very much for your contribution and pls I will reach out again when I found any difficulties.


Thanks again

**Comment by abdo400** [comment]
@zionnite Hi, have you managed to send a VoIP and handle it? If so, how please?

**Comment by zionnite** [comment]
> @zionnite Hi, have you managed to send a VoIP and handle it? If so, how please?

Up till now, have not been able to do that,

It's really discouraging how Apple set this parameters

**Comment by abdo400** [comment]
Check this
https://github.com/hiennguyen92/flutter_callkit_incoming/issues/146
