### ISSUE TITLE
Passing the NSDictionary in Crashes the app 

### ISSUE THREAD

**Issue by itsthetaste** [hiennguyen92/flutter_callkit_incoming#82]
getting an error when passing in the payloadDictionary in ios

let data = flutter_callkit_incoming.Data(args:payload.dictionaryPayload as NSDictionary)
SwiftFlutterCallkitIncomingPlugin.sharedInstance?.showCallkitIncoming(data, fromPushKit: true)

Could not cast value of type '__NSCFNumber' (0x1dac78610) to 'NSString' (0x1dac75c00).
2022-04-11 09:49:02.395648-0700 Runner[7409:1263130] Could not cast value of type '__NSCFNumber' (0x1dac78610) to 'NSString' (0x1dac75c00).

the issue appears to be in here

    @objc public convenience init(args: NSDictionary) {
        var argsConvert = [String: Any?]()
        for (value, key) in args {
            argsConvert[key as! String] = value
        }
        self.init(args: argsConvert)
    }

I believe it should be 

for (key, value) in args

as stepping through with a debugger, its trying to convert the "value" (0.005) for my audioSessionPreferredIOBufferDuration into a string

**Comment by hiennguyen92** [comment]
I just updated version 1.0.1+7
