### ISSUE TITLE
Navigate to a specific screen after accepting the call if app is terminated or in background 

### ISSUE THREAD

**Issue by faisalmushtaq007** [hiennguyen92/flutter_callkit_incoming#84]
the navigation does work for debug app but doesnt work when app is in release mode. Please take a look , its becoming so hectic

**Comment by hiennguyen92** [comment]
@faisalmushtaq007 can you give me platform has issue?

**Comment by faisalmushtaq007** [comment]
@hiennguyen92 what sir?

**Comment by hiennguyen92** [comment]
What platform are you having problems with?

**Comment by faisalmushtaq007** [comment]
@hiennguyen92 currently i tested on android.

**Comment by faisalmushtaq007** [comment]
@hiennguyen92 have you checked?

**Comment by hiennguyen92** [comment]
strangely, I can't reproduce this issue. i using example

**Comment by hiennguyen92** [comment]
I just updated version 1.0.1+7 please try again. (check example)

**Comment by faisalmushtaq007** [comment]
@hiennguyen92 still release mode is having issue. When i tap on accept, it only opens the app but doesnt take to the desired screen. In debug mode working fine

**Comment by hiennguyen92** [comment]
this maybe you can log sentry to debug it.  once the app is opened.  navigation to a special screen you have to check on your own app to be clear.

**Comment by hiennguyen92** [comment]
I just published v1.0.1+8, please check again.

I will double check the release mode issue.

**Comment by hiennguyen92** [comment]
you can try new version 1.0.2(check example)
