### ISSUE TITLE
Crash when accept call in iOS, when app is in background or terminate

### ISSUE THREAD

**Issue by ProgFatimaMaher** [hiennguyen92/flutter_callkit_incoming#85]
App state: background or terminate
Issue scenario:
when mobile is unlock and call alert and press accept the call, it causes a crash
but when the mobile locked and call alert you can accept call without problem

**Comment by faisalmushtaq007** [comment]
@ProgFatimaMaher I am having some issue when app is in release mode. Do you face any issue like that??

**Comment by ProgFatimaMaher** [comment]
@faisalmushtaq007  Yes, when accept call cause crash and close the app

**Comment by faisalmushtaq007** [comment]
@ProgFatimaMaher i am in so trouble because of this. And i have to deliver my app in few days. I dont understand what to do. Do u have any idea?

**Comment by ProgFatimaMaher** [comment]
@faisalmushtaq007  I need help to fix this problem, If there is any code to solve it !!
I try many ways to make calls in iOS, when I use this package I face this crash and don't know how to handle it.

**Comment by hiennguyen92** [comment]
strangely, I can't reproduce this issue.

**Comment by zionnite** [comment]
can you provide your flutter repository for this?

**Comment by hiennguyen92** [comment]
@zionnite i using example https://github.com/hiennguyen92/flutter_callkit_incoming/tree/master/example

**Comment by zionnite** [comment]
sir, i sent you an email, can you please respond to it?

**Comment by hiennguyen92** [comment]
I tested on Example. however, can't reproduce the crash

**Comment by ycherniavskyi** [comment]
@ProgFatimaMaher Also, it would be great if you could provide more info about your environment: OS type, OS version, phone model, etc.

**Comment by itsthetaste** [comment]
@ProgFatimaMaher also specific detail about the crash.  you should be able to get them from the console application on your Mac.  See the section at the bottom.

https://developer.apple.com/documentation/xcode/acquiring-crash-reports-and-diagnostic-logs
