### ISSUE TITLE
What is the reason to encrypt/decrypt handle data for iOS?

### ISSUE THREAD

**Issue by ycherniavskyi** [hiennguyen92/flutter_callkit_incoming#91]
Just looking throw the source code of the plugin. See the section with encrypt/decrypt handle data for the iOS part and can't grasp the reason for this functionality.
Could anyone please explain it to me?

**Comment by hiennguyen92** [comment]
Normal handling would be social profiles in phone book history.  (Usually apps will use the internal id here) i use it to save some caller info.  it will be used when you start a call from history phone book.

**Comment by ycherniavskyi** [comment]
I see. Thank you for the answer.
