### ISSUE TITLE
Specific Page not opening when app is on background and other issues

### ISSUE THREAD

**Issue by zionnite** [hiennguyen92/flutter_callkit_incoming#92]
Hello sir, 
thank you very much for the package and thanks for your constant maintainability of the package.

sir, I encounter some issues while using the package one of the issues is that

1) when the app is in the background, when I click on `ACTION_CALL_ACCEPT` it only opens the app but it does not take me to the specific page

2) Sometimes, the notification is duplicated, I wonder what might be wrong!

3) every time I received an Incoming call, the **ringing-tone** conflicted with the **notification tone**

4) This is very strange, sometimes the accept button does not work, I have to click it multiple times before it opens the app, whereas sometimes when I click on the accept button, the notification badge of the `flutter_callkit_incoming` will disappear to the notification tray.

5) I went to my app setting and intentionally force stop the app, so I sent a push notification to my device but the device did not come up. Is this part of the package? does it suppose to happen this way?

Am currently using version `flutter_callkit_incoming: ^1.0.1+7`

**Device Details**
Device Name : **Tecno Spark 7p**
Device Model: **Tecno KF7j**
Android version: 11

**Comment by hiennguyen92** [comment]
I just published v1.0.1+8, please check again.

I'm not sure about the issues you reported above. but I'll check it out

**Comment by hiennguyen92** [comment]
you can try new version 1.0.2

**Comment by zionnite** [comment]
Current Package resolved 
Question 1,
Question 2,
Question 4.


Question 3 and Question 5 are yet to be resolved!

**Comment by zionnite** [comment]
https://github.com/hiennguyen92/flutter_callkit_incoming/issues/93#issuecomment-1113899123

The app is only able to receive incoming call notifications only on the condition when the app is open in the foreground or background but when the app is terminated or killed or remove from the recent app, the app no longer receives incoming call notification


it was working fine on 1.0.1.+7

**Comment by zionnite** [comment]
@hiennguyen92

**Comment by hiennguyen92** [comment]
Issue 3, i wil check it.
Issue 5, please check logging for make sure has received notification. (if you sure that be sure received push notification via loggging, that is bug of this package.)

**Comment by zionnite** [comment]
Mr @hiennguyen92 , 
when I killed my app, I won't be able to see the log on the console

If I minimize the app, Yes I will receive incoming notification
if my phone is in a lock state, Yes I will receive an incoming notification
if am on other app like WhatsApp or Facebook, Yes I will receive incoming notification
if am right on the app, Yes I will receive an incoming notification



but if my app is removed from recent app, I will not receive any incoming notification
if my app is killed or terminated, I will not receive any incoming notification

**Comment by hiennguyen92** [comment]
Please search it on Google with 'android not receive notification when close app'. Looks like it has something to do with push notifications

**Comment by zionnite** [comment]
> Please search it on Google with 'android not receive notification when close app'. Looks like it has something to do with push notifications

I just discovered what happened why incoming calls was not showing.


The app was asking for permission to draw over the device.

So when I grant it permission, it started showing incoming calls.



But there is a **BUG**

When I removed the app from recent open app and when the device it's in lock state, when I accept a call or Decline a call, it just reload the App.




Secondly, is there a way to just display the incoming notification without asking permission to draw over the device?


Please check this Sir!
@hiennguyen92

**Comment by hiennguyen92** [comment]
1. please check https://github.com/hiennguyen92/flutter_callkit_incoming/blob/5ca15b339bca4f593ef1b09c9737130c1c122542/example/lib/main.dart#L83

https://github.com/hiennguyen92/flutter_callkit_incoming/blob/5ca15b339bca4f593ef1b09c9737130c1c122542/example/lib/main.dart#L115

(https://github.com/hiennguyen92/flutter_callkit_incoming/blob/5ca15b339bca4f593ef1b09c9737130c1c122542/example/lib/home_page.dart#L220

Here are 3 positions that may need you to check

**Comment by hiennguyen92** [comment]
library doesn't need "draw over other apps permission"

**Comment by zionnite** [comment]
> 1. please check https://github.com/hiennguyen92/flutter_callkit_incoming/blob/5ca15b339bca4f593ef1b09c9737130c1c122542/example/lib/main.dart#L83
> 
> https://github.com/hiennguyen92/flutter_callkit_incoming/blob/5ca15b339bca4f593ef1b09c9737130c1c122542/example/lib/main.dart#L115
> 
> (https://github.com/hiennguyen92/flutter_callkit_incoming/blob/5ca15b339bca4f593ef1b09c9737130c1c122542/example/lib/home_page.dart#L220
> 
> Here are 3 positions that may need you to check
> 

Thanks, I will take a look and respond ASAP

**Comment by zionnite** [comment]
> library doesn't need "draw over other apps permission"
> 

I will send you screenshots immediately so you understand what I meant, first I will need  uninstall the app and reinstall so I can show you the draw over permission it's asking for


Thanks again @hiennguyen92

**Comment by zionnite** [comment]
```
Unhandled Exception: type 'List<Object?>' is not a subtype of type 'String'
#0      _MyAppState.getCurrentCall (package:prayer_buddy/main.dart:314:34)
```

**Comment by zionnite** [comment]
i have update my code, by adding
1) 
**class _MyAppState extends State<MyApp> with `WidgetsBindingObserver `{**

2) 

```
 @override
  void initState() {
    super.initState();
    _uuid = Uuid();
    initFirebase();
    WidgetsBinding.instance?.addObserver(this);
    checkAndNavigationCallingPage();
  }
```

3)

```
getCurrentCall() async {
    //check current call from pushkit if possible
    var calls = await FlutterCallkitIncoming.activeCalls();
    final objCalls = json.decode(calls);
    if (objCalls is List) {
      if (objCalls.isNotEmpty) {
        print('DATA: $objCalls');
        this._currentUuid = objCalls[0]['id'];
        return objCalls[0];
      } else {
        this._currentUuid = "";
        return null;
      }
    }
  }

  checkAndNavigationCallingPage() async {
    var currentCall = await getCurrentCall();
    if (currentCall != null) {
      NavigationService.instance
          .pushNamedIfNotCurrent(AppRoute.callingPage, args: currentCall);
    }
  }

  @override
  Future<void> didChangeAppLifecycleState(AppLifecycleState state) async {
    print(state);
    if (state == AppLifecycleState.resumed) {
      //Check call when open app from background
      checkAndNavigationCallingPage();
    }
  }

  @override
  void dispose() {
    WidgetsBinding.instance?.removeObserver(this);
    super.dispose();
  }
```

I have done all these Yet the Accept Button and Decline button its ignore (working) when the app is in the terminate state or removed from recent App


though  `checkAndNavigationCallingPage()` AND  `didChangeAppLifecycleState()` are working perfectly well

have tested this in multiple scene but the exact issue still persist.

**Comment by zionnite** [comment]
After updating my code with the **WidgetsBindingObserver**, **checkAndNavigationCallingPage()** and **didChangeAppLifecycleState()** i observe keenly the following when the app its in terminate state or removed from recent app

1) The Decline Button only dismisses the incoming notification but `CallEvent.ACTION_CALL_DECLINE` is never fired

2) The Accept Button, only opens the app but `CallEvent.ACTION_CALL_ACCEPT` is never fired, though `checkAndNavigationCallingPage()` will take me to the route I want


please see to it sir @hiennguyen92

**Comment by zionnite** [comment]
![Screenshot_20220501-160803.jpg](https://user-images.githubusercontent.com/10984801/166152247-0724896a-cd55-4f77-9317-31fb91433ec8.jpg)


@hiennguyen92 , This is what am talking about, the incoming call wouldn't display over lock state except I grant it permission

**Comment by zionnite** [comment]
@hiennguyen92 , I have run this package more that 572 times.

1) I discovered that, duplicate of incoming call still persist.

2) When call it's pick within less that 5secs it does not navigate to specific page, I will tripple check on this to be accurate on my findings


3) on Terminated state, incoming notification it's not received, pls check my above reply, it still does appear.

The only way to receive incoming call notification was to pass the title and the message payload via the push notifications and adding this will result to having notification in the notification trays.

Pls check on this again sir

@hiennguyen92

**Comment by zionnite** [comment]
@hiennguyen92

**Comment by zionnite** [comment]
Hello @hiennguyen92 ,

Any hope for this?

**Comment by zionnite** [comment]
> After updating my code with the **WidgetsBindingObserver**, **checkAndNavigationCallingPage()** and **didChangeAppLifecycleState()** i observe keenly the following when the app its in terminate state or removed from recent app
> 
> 1. The Decline Button only dismisses the incoming notification but `CallEvent.ACTION_CALL_DECLINE` is never fired
> 2. The Accept Button, only opens the app but `CallEvent.ACTION_CALL_ACCEPT` is never fired, though `checkAndNavigationCallingPage()` will take me to the route I want
> 
> please see to it sir @hiennguyen92

this is very much persisting sir.

@hiennguyen92  please take a look at it sir!

**Comment by hiennguyen92** [comment]
1. i will check it(android)
2. app from terminated state to open app. you will not receive the event because the Flutter Engine is not attached. so can only check through `checkAndNavigationCallingPage`

**Comment by zionnite** [comment]
> 1. i will check it(android)
> 2. app from terminated state to open app. you will not receive the event because the Flutter Engine is not attached. so can only check through `checkAndNavigationCallingPage`

Where is the logic there?

I have to show the incoming notification call again via `checkAndNavigationCallingPage`

Can you please clearify me on this? @hiennguyen92

**Comment by zionnite** [comment]
> ![Screenshot_20220501-160803.jpg](https://user-images.githubusercontent.com/10984801/166152247-0724896a-cd55-4f77-9317-31fb91433ec8.jpg)
> 
> 
> @hiennguyen92 , This is what am talking about, the incoming call wouldn't display over lock state except I grant it permission.
> 
> How can we resolved this.
> 
> Plenty Thanks Master @hiennguyen92 

You didn't say anything about this @hiennguyen92

**Comment by hiennguyen92** [comment]
https://github.com/hiennguyen92/flutter_callkit_incoming/blob/5ca15b339bca4f593ef1b09c9737130c1c122542/example/lib/main.dart#L102

**Comment by zionnite** [comment]
> https://github.com/hiennguyen92/flutter_callkit_incoming/blob/5ca15b339bca4f593ef1b09c9737130c1c122542/example/lib/main.dart#L102
> 
> 

I can't really understand your reply.


**According to you app from terminated state to open, I will not receive the event because the flutter engine is not attached, so I can only check through 
`checkAndNavigationCallingPage`**


That's not it and I don't think you get my question.


App does open in terminated state but the issue is that the function tied to `EVENT_CALL_END` and `EVENT_CALL_ACCEPT` it's never triggered.

Fine, the app show the incoming notification on terminated state, when I click on it, it open the app but the button it's not fired.


If I have to used `checkAndNavigationCallingPage`
I will pass a function to get the current call function but I can't seem to know if the user has accepted the call or Ignored it because the function was not triggered, showing the incoming call notification via the `checkAndNavigationCallingPage` sounds not intelligent because the user just saw the incoming call in the Terminated state and yet again face with the incoming call notification again.


I don't know if I misunderstood your point.

Please help me to understand what am to do 


Thanks @hiennguyen92

**Comment by suhail600** [comment]
@hiennguyen92  bro nothing is working in terminated state or in background with listenerEvent , can u do something to store a value to device storage in the listenerEvent , that might be helpful , so that users can navigate with that data from any where without context and other hussles

**Comment by zionnite** [comment]
@hiennguyen92 we are stuck here😭

**Comment by hiennguyen92** [comment]
please check with https://github.com/hiennguyen92/flutter_callkit_incoming/blob/5ca15b339bca4f593ef1b09c9737130c1c122542/example/lib/main.dart#L102

**Comment by hiennguyen92** [comment]
Once you accept the call(terminated), the call will be saved. you can call `var calls = await FlutterCallkitIncoming.activeCalls();` to check accepted call(it will be cleared when endCall(...)

**Comment by zionnite** [comment]
> Once you accept the call(terminated), the call will be saved. you can call `var calls = await FlutterCallkitIncoming.activeCalls();` to check accepted call(it will be cleared when endCall(...)

@hiennguyen92 

Bruh, u are not getting my point.


When phone is in terminated State, when u click on the accept call, it relaunch the app and the block of code inside the `EVENT_ACCEPT_CALL`  it's never fired

**Comment by zionnite** [comment]
> Once you accept the call(terminated), the call will be saved. you can call `var calls = await FlutterCallkitIncoming.activeCalls();` to check accepted call(it will be cleared when endCall(...)

Nevertheless, I will try this options.

I would get back to you ASAP regarding this 


Thank you master @hiennguyen92

**Comment by zionnite** [comment]
> Once you accept the call(terminated), the call will be saved. you can call `var calls = await FlutterCallkitIncoming.activeCalls();` to check accepted call(it will be cleared when endCall(...)

@hiennguyen92 
Missed call are also saved too


Can you please check?

**Comment by hiennguyen92** [comment]
miss call will not be saved. (Save when receiving call and automatically remove when time out event)

**Comment by zionnite** [comment]
![Uploading Screen Shot 2022-06-01 at 10.29.10 AM.png…]()

**Comment by waqadArshad** [comment]
> Current Package resolved Question 1, Question 2, Question 4.
> 
> Question 3 and Question 5 are yet to be resolved!

@zionnite Hi, how did you handle background call notification ACCEPT event navigation. CAn you please help me with that? I', stuck. Thanks

**Comment by zionnite** [comment]
do you mean background or terminated state??

**Comment by waqadArshad** [comment]
In both, because right now I am testing this in the background state but I'm also going to test it in the terminated state afterwards.
