### ISSUE TITLE
on IOS if flutter app is closed ACTION_CALL_DECLINE (and other events) aren't received in dart code

### ISSUE THREAD

**Issue by jonathantawfik** [hiennguyen92/flutter_callkit_incoming#94]
While our app is closed we receive a VOIP push, the call banner is shown and the pushRegistry fires and event that calls the flutter_callkit_incoming showCallkitIncoming function.  All this swift code is run but the flutter part of the app doesn't start up.  If answer call is pressed the flutter app launches and we can check active calls to start the call with no problems.  On the other hand if user presses hang up then CXEndCallAction is triggered and in flutter_callkit_incoming the following code runs :
```
self.sendEvent(SwiftFlutterCallkitIncomingPlugin.ACTION_CALL_START, self.data?.toJSON()) 
```
this line should throw an event in the dart code but since the app is not launched it has not effect.  After this the banner disappears but the app is not launched, this means that we cannot send a reject call to the caller and his app keeps ringing.  Also on the recipient since no dart code is running there is no way for the recipient of the call to receive a cancel call message from the caller.  How can we execute code from our flutter app as soon as showCallkitIncoming is called?  Is it possible to run flutter code in the background without launching the complete app? Is flutter_callkit_incoming launching the app when the answer button is pressed by the user?

**Comment by hiennguyen92** [comment]
I just published v1.0.1+8, please check again.
once you decline you will have about 3 seconds to call the api before the app is closed.

https://github.com/hiennguyen92/flutter_callkit_incoming/blob/542c69ba4b956141423352f2fc885ff2eae08c58/example/lib/home_page.dart#L225
