### ISSUE TITLE
how do i end an incoming call

### ISSUE THREAD

**Issue by zionnite** [hiennguyen92/flutter_callkit_incoming#95]
take an example, 
`User A` initiates a call
`User B` phone is Ringing, but immediately `User A` hangs up, 
`User B` incoming call notification disappear 

how do I achieve this?

thanks!

**Comment by hiennguyen92** [comment]
Use A hang up => call api => backend send push voip to User B end call and show miss notification

**Comment by zionnite** [comment]
Oooh hoo,

Am confused 🤔

😐

**Comment by zionnite** [comment]
@hiennguyen92 I don't understand a thing @ycherniavskyi  just said.

guys pls explain

**Comment by zionnite** [comment]
I did it like this, now am not receiving an incoming call despise data is been output on the console that data arrive in the device


```
      if (notifyType == 'call') {
        showCallkitIncoming(
          uuid: this._currentUuid,
          call_msg: call_msg,
          call_from: call_from,
          call_from_full_name: call_from_full_name,
          call_from_image: call_from_image,
          call_to: call_to,
          call_to_full_name: call_to_full_name,
          call_to_image: call_to_image,
          call_type: call_type,
          call_channel: call_channel,
        );
      } else if (notifyType == 'hang_up') {
        endCurrentCall(this._currentUuid);
      }
```


am I doing something wrong @hiennguyen92 @ycherniavskyi

**Comment by zionnite** [comment]
After reasoning what you said for hours, I was able to understand what you met
for there to be an hang_up
`User A` would have to initiate the `API`, from the `API` send a push notification  to `User B` and end the call, and show Missed call notification

I did just that I discovered that the code below did not end an Incoming call, it only silenced **the Vibration and the ringing tone**

```
var params = <String, dynamic>{'id': this._currentUuid};
  await FlutterCallkitIncoming.endCall(params);
```

**Comment by zionnite** [comment]
@hiennguyen92, Please take a look at the above comment sir

**Comment by zionnite** [comment]
okay, i was able to resolve that by ending all Calls
`await FlutterCallkitIncoming.endAllCalls();`

**Comment by TN888** [comment]
But Firebase push notification doesn't fire when the call is in full screen. Anyone got a solution?
