### ISSUE TITLE
Disable missed call notifications

### ISSUE THREAD

**Issue by Altereyo** [hiennguyen92/flutter_callkit_incoming#96]
Hi, i want to disable missed call notifications, can u add it to params?
Much appreciated

**Comment by hiennguyen92** [comment]
I just published v1.0.1+8, please check again.

using `isShowMissedCallNotification`: false inside Android props

**Comment by Altereyo** [comment]
@hiennguyen92 thanks!
What about ios?

**Comment by hiennguyen92** [comment]
IOS using default by Callkit.
