### ISSUE TITLE
phone vibrates even in silent mode

### ISSUE THREAD

**Issue by suhail600** [hiennguyen92/flutter_callkit_incoming#98]
@hiennguyen92 ringing in debug mode ok, vibrating in vibrating mode ok , but its vibrating in silent mode too , how can I solve this.

**Comment by hiennguyen92** [comment]
I just published v1.0.1+8, please check again.

**Comment by suhail600** [comment]
> I just published v1.0.1+8, please check again.

@hiennguyen92 yes , its solved

**Comment by suhail600** [comment]
its solved in this update.

**Comment by sunil-singh-chaudhary** [comment]
hi @hiennguyen92 phone is in do not distrub mode and sound is playing whne get fcm notification pls help what wrong in that
