### ISSUE TITLE
Too many PendingIntent created

### ISSUE THREAD

**Issue by tcc13** [hiennguyen92/flutter_callkit_incoming#99]
Exception thrown:  
E/AndroidRuntime(22850): FATAL EXCEPTION: lowpool[2]
E/AndroidRuntime(22850): Process: com.google.android.gms.persistent, PID: 22850
E/AndroidRuntime(22850): java.lang.SecurityException: Too many PendingIntent created for uid 10187, aborting Key{broadcastIntent pkg=com.google.android.gms/com.google.android.gms.clearcut intent=act=ACTION_BOGUS pkg=com.google.example.invalidpackage cmp=com.google.example.invalidpackage/BogusClass flags=0x0 u=0} requestCode=0
E/AndroidRuntime(22850): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2376)
E/AndroidRuntime(22850): 	at android.os.Parcel.createException(Parcel.java:2360)
E/AndroidRuntime(22850): 	at android.os.Parcel.readException(Parcel.java:2343)
E/AndroidRuntime(22850): 	at android.os.Parcel.readException(Parcel.java:2285)
E/AndroidRuntime(22850): 	at android.app.IActivityManager$Stub$Proxy.getIntentSenderWithFeature(IActivityManager.java:6850)
E/AndroidRuntime(22850): 	at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:588)
E/AndroidRuntime(22850): 	at android.app.PendingIntent.getBroadcast(PendingIntent.java:571)
E/AndroidRuntime(22850): 	at aned.<init>(:com.google.android.gms@220920028@22.09.20 (100400-434869283):3)
E/AndroidRuntime(22850): 	at anef.<init>(:com.google.android.gms@220920028@22.09.20 (100400-434869283):0)
E/AndroidRuntime(22850): 	at andg.m(:com.google.android.gms@220920028@22.09.20 (100400-434869283):4)
E/AndroidRuntime(22850): 	at andg.e(:com.google.android.gms@220920028@22.09.20 (100400-434869283):5)
E/AndroidRuntime(22850): 	at andg.g(:com.google.android.gms@220920028@22.09.20 (100400-434869283):5)
E/AndroidRuntime(22850): 	at wft.c(:com.google.android.gms@220920028@22.09.20 (100400-434869283):6)
E/AndroidRuntime(22850): 	at wft.a(:com.google.android.gms@220920028@22.09.20 (100400-434869283):3)
E/AndroidRuntime(22850): 	at wdl.f(:com.google.android.gms@220920028@22.09.20 (100400-434869283):124)
E/AndroidRuntime(22850): 	at agxl.en(:com.google.android.gms@220920028@22.09.20 (100400-434869283):1)
E/AndroidRuntime(22850): 	at agxx.run(:com.google.android.gms@220920028@22.09.20 (100400-434869283):5)
E/AndroidRuntime(22850): 	at cdcy.run(:com.google.android.gms@220920028@22.09.20 (100400-434869283):2)
E/AndroidRuntime(22850): 	at xvv.c(:com.google.android.gms@220920028@22.09.20 (100400-434869283):6)
E/AndroidRuntime(22850): 	at xvv.run(:com.google.android.gms@220920028@22.09.20 (100400-434869283):7)
E/AndroidRuntime(22850): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(22850): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(22850): 	at yaz.run(:com.google.android.gms@220920028@22.09.20 (100400-434869283):0)
E/AndroidRuntime(22850): 	at java.lang.Thread.run(Thread.java:923)
E/AndroidRuntime(22850): 	Suppressed: cddk:
E/AndroidRuntime(22850): 		at tk_trace.40-LogOperation(Unknown Source:0)
E/AndroidRuntime(22850): 		at tk_trace.clearcut-ClearcutLoggerChimeraService-IClearcutLoggerService_0(Unknown Source:0)
E/AndroidRuntime(22850): Caused by: android.os.RemoteException: Remote stack trace:
E/AndroidRuntime(22850): 	at com.android.server.am.PendingIntentController.incrementUidStatLocked(PendingIntentController.java:441)
E/AndroidRuntime(22850): 	at com.android.server.am.PendingIntentController.getIntentSender(PendingIntentController.java:165)
E/AndroidRuntime(22850): 	at com.android.server.am.ActivityManagerService.getIntentSenderWithFeature(ActivityManagerService.java:6042)
E/AndroidRuntime(22850): 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3094)
E/AndroidRuntime(22850): 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2977)
E/AndroidRuntime(22850):

flutter doctor:
[✓] Flutter (Channel stable, 2.10.2, on macOS 12.1
    21C52 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices
    (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.66.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

**Comment by hiennguyen92** [comment]
I cannot reproduce this issue and seems unrelated to this library.
